### PR TITLE
LPS-136075 Change xml definition's xsd version to 7.4

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Story: [LPS-136075](https://issues.liferay.com/browse/LPS-136075)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @MarinhoFeliphe,

Can you update to 7.4 the others definitions we provide OOTB?

Thc

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
