### PR TITLE
LPD-37540

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
Hey @carolmariaabb, can you check the CI results? If everything is ok, please forward the PR to Brian.

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
Hey @tinatian , did you try to write an integration test to cover this bug?

**Comment by tinatian** [comment]
@guilhermedcamacho This issue can not be covered by integration test as the condition to trigger this is first request on a first start of portal. However, you can add integration test to only cover the changed part by verifying if it has correct threadlocals.

**Comment by guilhermedcamacho** [comment]
@tinatian Got it, thanks for the explanation. I'll discuss this with @carolmariaabb

**Comment by carolmariaabb** [comment]
https://github.com/liferay-workflow/liferay-portal/pull/1246

**Pull request closed without merging**
