### PR TITLE
[TS] LPS-162388 Cannot mark notification from workflow as read if user is not a reviewer or similar

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-workflow team,

This PR is a proposed solution for the issue [LPS-162388](https://issues.liferay.com/browse/LPS-162388) about not being able to mark certain notifications as read (regression of [LPS-146463](https://issues.liferay.com/browse/LPS-146463)).

The problematic situation the PR solves is described in [LPS-162388](https://issues.liferay.com/browse/LPS-162388). In short, an asset under a workflow has been submitted and a user is notified but they don't have the permission to assign it to themselves or anything else. Although there's a notification badge says there's an unread message, the notification itself shows as read, so the notification badge doesn't go away.

Description of the solution:

- The problem was in the use of the method `isApplicable`. This method is related to the attribute `applicable` in `UserNotificationFeedEntry` and was introduced in [LPS-77880](https://issues.liferay.com/browse/LPS-77880) to handle ephemeral notifications for withdrawn submissions. The idea is that non-applicable notifications are totally non-interactive: they're marked as read, have no link and have no actions. (The name is not the best one, unfortunately.)

- For the use case in [LPS-162388](https://issues.liferay.com/browse/LPS-162388) we don't want to be so drastic: the notification should be marked as unread and should have actions associated to it to mark it as read and deleted. 

- The solution proposed removes the overwriting of `isApplicable` in `WorkflowTaskUserNotificationHandler` to leave as default (`true`) but will use the same underlying logic to obtain the link: if the user is not allowed they should get no link to go further. 

- The rest of the relevant code doesn't need to change: 
  - `BaseUserNotificationHandler` or `NotificationsManagementToolbarDisplayContext` will work as they are. 
  - The JSP `user_notification_entry.jspf` will also work as is: since the notfication is applicable now it will try check if the link is empty and if so, will set it to the current URL (so that clicking on it just marks the notification as read). It will also print the body and the action 3-menu (to mark as read/unread and delete).

- Since `isApplicable` has been moved in the local method `_shouldHaveLink`, the associated test `testIsApplicable` in `WorkflowTaskUserNotificationHandlerTest` is removed and `testValidWorkflowTaskIdShouldReturnLink` is split in two tests depending on whether the user is allowed or not.

Note:

- This is the simplest solution I could come up with. Another approach I considered involved adding another attribute in `UserNotificationFeedEntry` in the style of `applicable` and leaving the implementation of `isApplicable` as is. The problem I see with it is that we're changing the semantics of `applicable` which is supposed to be used for totally non-interactive notifications. We'd also need several other changes in the code making that approach more complicated.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hello @ricardocousolr,

Could you please rename the name of [this method](https://github.com/liferay-workflow/liferay-portal/pull/852/files#diff-d3f2717fd78fab0c31ddf547f097c81e8cd32398666f4f48501d4b4977d2ed72R248) to something like `_isNotifiable` because I believe Brian won't accept the name '_shouldHaveLink'.

Thanks for your contribution and for the details provided!!

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hello @ricardocousolr,

Sorry for the late reply,

Could you please rename the name of [this method](https://github.com/liferay-workflow/liferay-portal/pull/852/files#diff-d3f2717fd78fab0c31ddf547f097c81e8cd32398666f4f48501d4b4977d2ed72R248) to something like `_isNotifiable` because I believe Brian won't accept the name `_shouldHaveLink`.

Thanks for your contribution and for the details provided!!

**Comment by ricardocousolr** [comment]
HI @MarinhoFeliphe,

I'll rename the method and resend a clean PR.

**Comment by ricardocousolr** [comment]
New pr here: https://github.com/liferay-workflow/liferay-portal/pull/861

**Pull request closed without merging**
