### PR TITLE
LPS-128297 Display timers property only in Task Nodes

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Closing because it's not ready yet. @MarinhoFeliphe send a new one after applying the backend part. Thx

**Pull request closed without merging**
