### PR TITLE
LPS-162890 It's not possible to change the script language when using Kaleo Designer Diagram

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-162890

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:sf

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Hi @daiazius, great job :) But we have some other places that need to be updated too. In the assignments configuration, we have the assignment type "Scripted Assignment" and in the actions configuration, with type reassignment, we have the "Scripted Reassignment" reassignment type. We also have the "Scripted Recipient" in the recipient types inside Notifications configuration. In all these places, we are only considering the Groovy language, and we need to display the Select you added inside Actions configuration. Thank you!

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/831

**Pull request closed without merging**
