### PR TITLE
LPS-134557 Add WorkflowTaskAssignableUsersResource's integration test

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
Just started reviewing :)

**Pull request closed without merging**
