### PR TITLE
LPS-176070 Wrap component in a div

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi team!

I'm sending this PR because we plan to start using `liferay-portal-workflow:status` taglib in our components, and we have noticed that the react component is not wrapped in a `div`.

This could cause the taglib removing all sibling markup when being used in other `jsp`'s, so I'm just wrapping the component in a `div`.

Please let me know what you think, thanks! 😄

### CODE REVIEW

**Comment by DiegoHu97** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @sandrodw3, I think it would be better to change the file [WorkflowStatus.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-taglib/src/main/resources/META-INF/resources/workflow_status/js/WorkflowStatus.js), replacing the wrapper `<> </>` with `<div> </div>` and the result would be the same :)

**Comment by sandrodw3** [comment]
> Hi @sandrodw3, I think it would be better to change the file [WorkflowStatus.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-taglib/src/main/resources/META-INF/resources/workflow_status/js/WorkflowStatus.js), replacing the wrapper `<> </>` with `<div> </div>` and the result would be the same :)

Hi @naraandrade! I don't think it would be the same. The thing is the `react:component` taglib was done that way, it removes the sibling markup, doesn't matter what the react component itself has inside, the `div` needs to be placed outside the taglib (you can see it in other usages in portal). Please let me know what you think, thanks! 😄

**Comment by naraandrade** [comment]
> > Hi @sandrodw3, I think it would be better to change the file [WorkflowStatus.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-taglib/src/main/resources/META-INF/resources/workflow_status/js/WorkflowStatus.js), replacing the wrapper `<> </>` with `<div> </div>` and the result would be the same :)
> 
> Hi @naraandrade! I don't think it would be the same. The thing is the `react:component` taglib was done that way, it removes the sibling markup, doesn't matter what the react component itself has inside, the `div` needs to be placed outside the taglib (you can see it in other usages in portal). Please let me know what you think, thanks! smile

Oh, I understand. Thanks for explaining that! If that's the case, it's all good for me. I'm going to forward this PR. Thanks for the contribution!

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
