### PR TITLE
[7.4 Only] LPS-123492 Adjust max height of table when alert is displayed

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:app-builder

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by gabrielpramos — APPROVED** [review]

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:forward

**Pull request closed without merging**
