### PR TITLE
LRQA-59848 Fix Calendar#DELETED_CALENDAR_SUCCESS_MESSAGE path selector

### PR DESCRIPTION
**Pull request by albinojunior**
/cc @rodrigocunhaa

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
