### PR TITLE
[7.4 only] LPS-122386

### PR DESCRIPTION
**Pull request by albinojunior**
**Story:** [LPS-111511](https://issues.liferay.com/browse/LPS-111511) | /cc @gabrielpramos @naraandrade

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:stop

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
Hey @rodrigocunhaa, I have updated the selectors to fix the `AppBuilder#ViewFieldSetsInTableView` test case, it were failing because were clicking on new others elements and broken the test flow. 

See [1430cc5](https://github.com/liferay-workflow/liferay-portal/pull/112/commits/1430cc5193af352ef943b07c84719d13bccec9b1).

**Comment by rodrigocunhaa** [comment]
ci:test:app-builder

**Comment by rodrigocunhaa** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
Thanks @albinojunior , I've also commented to run the App Builder and Workflow suite to make sure that there is no other tests being affected.

**Comment by rodrigocunhaa** [comment]
The test that failed for `ci:test:app-builder` is not related to this PR. This test has been falling for a while. I'll add it to quarantine and inform them.

**Comment by rodrigocunhaa** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
The tests that failed for `ci:test:workflow` is not related to this PR.

**Comment by gabrielpramos** [comment]
needs rebase from [this pr](https://github.com/liferay-workflow/liferay-portal/pull/111)

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielpramos** [comment]
this PR was rebased to [PR-124](https://github.com/liferay-workflow/liferay-portal/pull/124)

**Pull request closed without merging**
