### PR TITLE
LPS-133815 Enable sort by user creator

### PR DESCRIPTION
**Pull request by ramonmsp**
Story: [ LPS-130218](https://issues.liferay.com/browse/LPS-130218)

### CODE REVIEW

**Comment by ramonmsp** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/402

**Pull request closed without merging**
