### PR TITLE
LPS-137220 Fix getSortingURL to prevent double click to order list on first render

### PR DESCRIPTION
**Pull request by jotascript**
Issue: [LPS-137220](https://issues.liferay.com/browse/LPS-137220)

### CODE REVIEW

**Review by rafaprax — APPROVED** [review]

**Review by ramonmsp — APPROVED** [review]

**Comment by ramonmsp** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Review by rafaprax — APPROVED** [review]

**Pull request closed without merging**
