### PR TITLE
LPS-137845 Change logic of how to select the transitions source and target handles

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-136249](https://issues.liferay.com/browse/LPS-136249)

### CODE REVIEW

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by jotascript** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by ramonmsp — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
