### PR TITLE
LPS-133371 Adjust columns title and items alignment

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by ramonmsp — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
