### PR TITLE
LPD-2275 Fix construction of the timers sidebar when adding a ScriptedReassignment timer

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://liferay.atlassian.net/browse/LPD-2275

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
Starting review :shipit:

**Comment by igor-franca** [comment]
LGTM! :dancer:

**Comment by igor-franca** [comment]
ci:test:workflow

**Comment by igor-franca** [comment]
ci:test:workflow-metrics

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
After comparing with the daily testing routine, the tests did not indicate any failures caused by the PR modifications. 👍🏾

**Comment by igor-franca** [comment]
Waiting for the relevant result :hourglass_flowing_sand:

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
