### PR TITLE
[TS] LPS-125426 - fix potential vulnerability in currentURL

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPP-39658
https://issues.liferay.com/browse/LPS-125426

Per [PTR-2139](https://issues.liferay.com/browse/PTR-2139), sending this fix in for a potential XSS vulnerability.

CC: @achaparro: FYI, since I'll be out on PTO.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@liferay-workflow Is there any update on this review?

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
