### PR TITLE
LRQA-59704 Fix wrong locators and Remove test out of quarantine

### PR DESCRIPTION
**Pull request by albinojunior**
/cc @rodrigocunhaa

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Review by rodrigocunhaa — APPROVED** [review]

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
Hey @rodrigocunhaa, this ci failure does not seem to be related with this PR. Can you take a look at this?

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Updated here: https://github.com/liferay-workflow/liferay-portal/pull/184

**Pull request closed without merging**
