### PR TITLE
LPD-31858 setDisabled to true after the first click

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-31858](https://liferay.atlassian.net/browse/LPD-31858)

The bug can only be reproduced using slow3G, and Playwright does not support this network configuration, which is why I am not implementing a test to cover this fix. This decision was aligned with the TL.  
In the future, we intend to migrate this component, which will allow us to implement a unit test on the front end.

cc @marcelabc 

[LPD-31858]: https://liferay.atlassian.net/browse/LPD-31858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by linolaoj — APPROVED** [review]
Hi @vngoliveira, it looks good to me. Can you please edit the commit message to make clear that we are not adding a test because this change is only adding the loading element to the page.

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by igor-franca** [comment]
> Hi @vngoliveira, it looks good to me. Can you please edit the commit message to clarify that we are not adding a test because this change only adds the loading element to the page?
> 
> @igor-franca, do you agree that we don't need a test for this change?

Hey @linolaoj, Nathaly talked to me yesterday about this decision to send this fix without a functional test. She informed me that this decision was aligned with other team members.

Furthermore, from what I could research, the bug can only be reproduced using slow3G and playwright does not support this network configuration.

There is a way to simulate this slowness, but as it is not officially provided by the library, I don't know if it would be a safe path to follow.

**Comment by vngoliveira** [comment]
ci:foward

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
