### PR TITLE
LPS-188748 Temporarily ignore test

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://liferay.atlassian.net/browse/LPS-195656

Temporarily ignoring test until a fix for https://liferay.atlassian.net/browse/LPS-164188 is sent.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
As Patricia said, it's temporarily, a follow-up PR must be sent using the approach suggested here:

https://github.com/liferay-core-infra/liferay-portal/pull/3935#issuecomment-1482047017

**Comment by MarinhoFeliphe** [comment]
Hey @patriciajeanperez,

Your changes look good to me, but I noticed the issue is still present ([see](https://testray.liferay.com/home/-/testray/case_results/2421141995?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2421141690%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)),

I'm not sure but based on the conversation we had I believe the only way to fix it is ignoring/fixing all tests that are using creating a company and are not deleting it properly, so my questions are:

1 - Is my assumption above right?
2 - If so, do you think this PR should be forward? I mean, I believe we can handle this on our side by forwarding this PR and wait for other teams to resolve this on their side as well, but as far as I see [here](https://liferay.atlassian.net/browse/LPS-164188) there are a lot of tests that are facing this issue.

Thank you!

**Comment by patriciajeanperez** [comment]
Thanks for checking, @MarinhoFeliphe! I was mainly ignoring the Upgrades one because that error will show up in every Upgrades PR but I went ahead and ignored the ones you linked too. 

You're right, the other failures will be on the other teams to ignore and/or fix. At least for our side, these are the only affected tests I know of.

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
Hey @patriciajeanperez could you please use the LPS-188748 in the commit message?

your changes look good to me, as soon as you change the commit message you can forward this PR to Brian,

Thank you!

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward:force

**Pull request closed without merging**
