### PR TITLE
LPS-166781 Allow having more than two notification types

### PR DESCRIPTION
**Pull request by naraandrade**
Related issue: [LPS-166781](https://issues.liferay.com/browse/LPS-166781)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by naraandrade** [comment]
Sent directly to Brian: https://github.com/brianchandotcom/liferay-portal/pull/125858

**Pull request closed without merging**
