### PR TITLE
LPD-18469 Fix test LocalFile.WorkflowPageRevision#StatusIsPendingAfterSubmitForWorkflow

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-18469](https://liferay.atlassian.net/browse/LPD-18469)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
