### PR TITLE
LPD-20847 test fix NEXT_PAGINATION_BUTTON path in WorkflowReassignModal

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-20847](https://liferay.atlassian.net/browse/LPD-20847)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:workflow

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by vngoliveira** [comment]
ci:foward

**Comment by marcelabc** [comment]
ci:forward

**Pull request closed without merging**
