### PR TITLE
LPS-144856 Remove unnecessary functions

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-141713](https://issues.liferay.com/browse/LPS-141713)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by MariMalta** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here #710

**Pull request closed without merging**
