### PR TITLE
LPD-15433 Verify the user permissions to edit a Kaleo Definition by the API

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-15433](https://liferay.atlassian.net/browse/LPD-15433)
Hi team!
I worked to fix an issue related to a user who, without the proper permission, is able to edit by the `/v1.0/workflow-definitions/save` endpoint a Workflow Definition.
In my solution, I tried to verify the user's permissions to allow or not allow the command's execution.
Thank you for your attention and review. Feel free to ask me about this PR.

### CODE REVIEW

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hi @vngoliveira,

This **Resource** layer is not supposed to check permissions, the proper layer to perform such validations is the **Service** layer, but for kaleo definition we're checking permissions on DefaultWorkflowDeployer ([see](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal-workflow/portal-workflow-kaleo-definition-impl/src/main/java/com/liferay/portal/workflow/kaleo/definition/internal/deployment/DefaultWorkflowDeployer.java#L57)).

The easy fix is about moving the `_checkPermissions` method to be executed inside `_addOrUpdateKaleoDefinition`, but the proper fix is about creating a service layer for kaleo definition entity (you can do this setting true to `remote-service` [here](https://github.com/liferay/liferay-portal/blob/f8d3e79fe33c56da134ab88a7002694dce741628/modules/apps/portal-workflow/portal-workflow-kaleo-service/service.xml#L121) and executing `gradlew buildService`), afoter this you have to create these two methods below in the generated file `KaleoDefinitionServiceImpl`:

**1 - addKaleoDefinition:**

here you have to call:

```java
_kaleoDefinitionLocalService.addKaleoDefinition(
  name, title, definition.getDescription(), definition.getContent(), 
  scope, 1, serviceContext);
```

but before call this method you have to check permission by using this method below:

```java
private void _checkPermissions(ServiceContext serviceContext)
throws PrincipalException {

PermissionChecker permissionChecker =
	PermissionThreadLocal.getPermissionChecker();

if ((permissionChecker == null) ||
	!GetterUtil.getBoolean(
		serviceContext.getAttribute("checkPermission"), true)) {

	return;
}

_portletResourcePermission.check(
	permissionChecker, serviceContext.getScopeGroupId(),
	ActionKeys.ADD_DEFINITION);
}
```

**2 - updateKaleoDefinition:**

Call:

```java
_kaleoDefinitionLocalService.updatedKaleoDefinition(
	kaleoDefinition.getKaleoDefinitionId(), title,
	definition.getDescription(), definition.getContent(), 
	serviceContext);
```

but before check permission as well by using the same method (`_checkPermissions`).

After this you have to call the method from **Service** instead **LocalService** on `DefaultWorkflowDeployer`, this way we're following the architecture design of liferay-portal.

Feel free to reach me if you have any doubts,

Thank you!

**Comment by marcelabc** [comment]
Hey @MarinhoFeliphe 
I aligned with @vngoliveira to send the PR without all the test scenarios because this PR was classified as High Priority for this week. The missing test scenarios will be cover in a separate subtask, okay?

**Comment by MarinhoFeliphe** [comment]
Agreed @marcelabc, thanks for letting me know.

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hey @vngoliveira I forgot to sent the change in service.xml ([this one](https://github.com/liferay/liferay-portal/blob/f8d3e79fe33c56da134ab88a7002694dce741628/modules/apps/portal-workflow/portal-workflow-kaleo-service/service.xml#L121)),

please create a commit with the change below and put in a commit before the buildService one.

`<entity local-service="true" name="KaleoDefinition" remote-service="false">`

Thank you!

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/1066

Good job @vngoliveira!! :tada:

**Pull request closed without merging**
