### PR TITLE
[7.4 Only] LPS-122713 Increase coverage of Entry files

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-105491](https://issues.liferay.com/browse/LPS-105491)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:app-builder

**Review by albinojunior — APPROVED** [review]
LGTM!

**Comment by rafaprax** [comment]
LGTM

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
