### PR TITLE
[7.4 Only] LPS-122779 Apply shortCutButton in EditAppStepContent

### PR DESCRIPTION
**Pull request by gabrielpramos**
story [LPS-105493](https://issues.liferay.com/browse/LPS-105493)
cc @albinojunior @rafaprax @interaminense

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:app-builder

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:app-builder

**Review by albinojunior — APPROVED** [review]
LGTM!

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
LGTM

**Comment by gabrielpramos** [comment]
ci:forward

**Pull request closed without merging**
