### PR TITLE
[7.4 Only] LPS-123201 Remove scroll edge when scroll is not enable yet

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-105491](https://issues.liferay.com/browse/LPS-105491)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:app-builder

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:app-builder

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielpramos** [comment]
ci:forward

**Pull request closed without merging**
