### PR TITLE
LPS-141069 Apply Instance Tracker on Kaleo Forms' kebab

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Story: [LPS-140647](https://issues.liferay.com/browse/LPS-140647)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Review by rafaprax — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Pull request closed without merging**
