### PR TITLE
LPS-136357 Create WorkflowInstanceTracker component

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-133990](https://issues.liferay.com/browse/LPS-133990)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by jotascript** [comment]
Just started reviewing :)

**Comment by jotascript** [comment]
Just started reviewing :)

**Review by jotascript — APPROVED** [review]

**Review by rafaprax — APPROVED** [review]

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Review by ramonmsp — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
