### PR TITLE
[7.4 only] LPS-124585 Build rest

### PR DESCRIPTION
**Pull request by rafaprax**
Story https://issues.liferay.com/browse/LPS-121226

/cc @gabrielpramos @albinojunior @naraandrade

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci::forward

**Comment by albinojunior** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/170

**Pull request closed without merging**
