### PR TITLE
LPS-200375

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Allow users select Collections of type Calendar Event, also map fields to different editable fields in fragments.

Proposed Solution
-----
Implements the following interfaces for CalendarBooking class

- InfoItemFormProvider
- InfoItemFieldValuesProvider
- InfoItemDetailsProvider
- InfoItemObjectProvider

Please let me know if you have any question.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
Hi @ealonso thanks for your contribution,

I'll review this as soon as possible this week.

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by ealonso** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
Taking a look,

sorry for the late reply

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM, thanks for your contribution @ealonso

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
