### PR TITLE
LPD-34235 Use the httpServletRequest before it gets recycled

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
## Related tickets

- https://liferay.atlassian.net/browse/LPD-34235

## Motivation

_"java.lang.IllegalStateException: The request object has been recycled and is no longer associated with this facade"_ is being thrown at [WikiPageLocalServiceImpl._getDiffsURL](https://github.com/liferay/liferay-portal/blob/master/modules/apps/wiki/wiki-service/src/main/java/com/liferay/wiki/service/impl/WikiPageLocalServiceImpl.java#L2396-L2405), at this moment the request is already recycled due to the asynchronicity of workflow graph walker.

## Proposed Solution

Fetch the data before the request is recycled instead of forcing this operation to be synchronous by passing the `waitForCompletion` as true.

## Test

`WorkflowWiki#ApproveFrontPageUserEdit` is already covering this use case

## Related

- https://github.com/brianchandotcom/liferay-portal/pull/152869

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi @MarinhoFeliphe , those changes look good to me. Can you just edit the commit message to add the info that the issue is already covered by the test WorkflowWiki#ApproveFrontPageUserEdit?

**Review by linolaoj — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Comment by linolaoj** [comment]
ci:forward:force

**Pull request closed without merging**
