### PR TITLE
LPS-188243 - The footer must be stable

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-188243](https://liferay.atlassian.net/browse/LPS-188243)

### CODE REVIEW

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @Artartur, thanks for the contribution :) Your fix works fine, but I don't see the need to use the media query here, you can apply that rule without checking the resolution of the screen. I suggest you place it right above the margin top for the button holder, like this:
```
    .button-holder {
	    position: fixed;
    }

    .button-holder,
    .sheet {
	    margin-top: 20px;
    }
}
```

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:workflow

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
Just started reviewing :)

**Pull request closed without merging**
