### PR TITLE
LPS-134562 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
ci:forward

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/105918

**Pull request closed without merging**
