### PR TITLE
LPS-135714 Intermittent index_not_found_exception for Workflow indices

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LPS-135714

Merge AddIndexesWorkflowMetricsPortalInstanceLifecycleListener/ReindexWorkflowMetricsPortalInstanceLifecycleListener. We don't have control over activation order of PortalInstanceLifecycleListener, having separate PortalInstanceLifecycleListeners could allow reindex happens before creation which leads to "index_not_found_exception" exception.

ci:test:workflow has already been tested in: https://github.com/joshchong/liferay-portal/pull/654#issuecomment-1414501475
and
https://github.com/joshchong/liferay-portal/pull/654#issuecomment-1416431594

I have analyzed the tests and confirmed that the failures are unrelated.

cc @shuyangzhou

### CODE REVIEW

**Comment by joshchong** [comment]
Manually aborting the workflow test run since it was already run with these changes.

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
@joshchong @shuyangzhou 

Looks good to me! thanks for your contribution!

thanks to run workflow's tests I just ran workflow metrics' tests only to make sure that  everything is fine!

Best Regards,
Feliphe

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Pull request closed without merging**
