### PR TITLE
LPS-136072 Add Account on role type options

### PR DESCRIPTION
**Pull request by ramonmsp**
Story: [LPS-135888](https://issues.liferay.com/browse/LPS-135888)

### CODE REVIEW

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:workflow

**Comment by ramonmsp** [comment]
ci:stop

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:workflow

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:workflow

**Comment by ramonmsp** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by naraandrade — APPROVED** [review]

**Comment by ramonmsp** [comment]
ci:forward

**Pull request closed without merging**
