### PR TITLE
LPS-126594 Apply IconWIthPopover in SelectFormView

### PR DESCRIPTION
**Pull request by gabrielpramos**
story: [LPS-124979](https://issues.liferay.com/browse/LPS-124979)

cc: @naraandrade @rafaprax

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
