### PR TITLE
LPS-125455 Set max height to properties table so the overflow:auto property can work as expected

### PR DESCRIPTION
**Pull request by naraandrade**
cc: @albinojunior @gabrielpramos

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:sf

**Review by albinojunior — APPROVED** [review]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
