### PR TITLE
Complete Workflow activity is not displayed in 7.1 - 7.4 compared to 7.0

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

If the workflow logs are listed by task instead of instance, not the complete history will be shown.

Thank you and best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD, thanks for bring up this question for us.

This [fix](https://github.com/brianchandotcom/liferay-portal/pull/81764/commits/43bbb6f2d1b0efaddc3370aee076388abe0e6654) was applied because the _Last Activity Date_ column on _My Workflow Tasks_ showed the Instances' last activity.

`public Date getLastActivityDate(WorkflowTask workflowTask) throws PortalException {

	WorkflowLog workflowLog = _getWorkflowLog(workflowTask);

	if (workflowLog != null) {
		return workflowLog.getCreateDate();
	}

	return null;
}`

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

Thanks for the explanation!
Is there an alternative way to fix the current issue?
Perhaps we could extend the API with a getWorkflowLogs method the fetches the logs by workflow instance?

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD

Today we can view all activities on _My Submissions_,

I'll bring up this question to product team.

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD, sorry for delay!

I talked the product team and they decided keep the current behaviour. In Their opnion, this information should be separate as it provides different value to different users. Also having all the instance activities listed in my workflow tasks could be confusing / overwhelming to a user who simply needs to approve a piece of content.

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

Thank you for your answer!
I'm closing the pull request.

**Pull request closed without merging**
