### PR TITLE
[TS] LPS-201025 Wrong translation of titles in Workflow Metrics

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
The translations of the process titles in the Workflow Metrics widget may become mixed up if fewer languages are available than at the time when the processes were indexed. For example, the value meant for the US English translation may end up to be actually the French translation.
This is because the [ProcessUtil._toLanguageTag](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-metrics-rest-impl/src/main/java/com/liferay/portal/workflow/metrics/rest/internal/dto/v1_0/util/ProcessUtil.java#L95) method returns the language tag of the default locale if the locale associated with the `languageId` parameter is not available.

Proposed Solution
========
The `ProcessUtil._toLanguageTag` method should return _null_ if the locale is not available. Then, the `titleMap` will only have entries for the available locales.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-201025

Thank you and best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada: thanks for your contribution!

**Comment by davisaints** [comment]
Comparison with [workflow metrics](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1699451587730&testrayRunIdA=2454518582&testrayRunIdB=2454555824) suite and acceptance.

No regressions found!

**Comment by davisaints** [comment]
ci:forward:force

**Pull request closed without merging**
