### PR TITLE
LPS-120973 Fix entry edit button visualization in others apps

### PR DESCRIPTION
**Pull request by gabrielpramos**
cc @albinojunior

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
@gabrielpramos , Let's hold on this PR since it is not related to a blocker ticket. I added the "on hold" label on that.

**Comment by inacionery** [comment]
ci:forward

**Pull request closed without merging**
