### PR TITLE
LPD-28216 Evaluating user permissions on Workflow task notifications

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-28216

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:playwright

**Comment by carolmariaabb** [comment]
@rijema @danvb112  there are no unique failures in this PR, with the exception of

```
logged user must be able to see workflow task at least from a read-only perspective
``` 

which is failing on CI with the same error as 

```
send user back to my workflow tasks page after assign another user to review
```

which is already failing on Master.

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
CI Failures are not related! :tada:

**Comment by danvb112** [comment]
ci:forward:force

**Comment by rijema** [comment]
Tears of joy streamed down my face, ngl. Thank you @carolmariaabb @danvb112 .

**Comment by carolmariaabb** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/153211

**Pull request closed without merging**
