### PR TITLE
LPS-179185 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira: https://liferay.atlassian.net/browse/LPS-179185

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:sf

**Review by seltong — APPROVED** [review]
LGTM :tada:

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM, thanks @leilanyaragao for your contribution

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/144216

**Pull request closed without merging**
