### PR TITLE
LPS-120450 Update functional tests

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Hey @naraandrade, 

Could you please check these failures? LocalFile.WorkflowMetrics#ViewWorkloadByAssigneePage and LocalFile.WorkflowMetrics#ViewPerformanceByAssigneePage

It seems to be real to me.

Thanks!

**Comment by naraandrade** [comment]
> Hey @naraandrade,
> 
> Could you please check these failures? LocalFile.WorkflowMetrics#ViewWorkloadByAssigneePage and LocalFile.WorkflowMetrics#ViewPerformanceByAssigneePage
> 
> It seems to be real to me.
> 
> Thanks!

I'll check it now, thanks :)

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Hey @naraandrade,

Two more failures. LocalFile.WorkflowMetrics#VerifyFilterTopStepPerformance and LocalFile.WorkflowMetrics#ViewSLABreachesOfTopSteps 

Could you please check it?

Thanks!

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
test comment

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
Hey @rodrigocunhaa and @gabrielpramos could you please see this PR? 

Thanks!

**Review by rodrigocunhaa — APPROVED** [review]

**Review by gabrielpramos — APPROVED** [review]

**Comment by albinojunior** [comment]
ci:forward

**Comment by albinojunior** [comment]
ci:forward

**Pull request closed without merging**
