### PR TITLE
LPS-187195 Source views exhibits description when network connection is slow

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-187195

### CODE REVIEW

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @alinedoleron, I noticed an issue while going back and forth from the diagram view to the source view and also remembered that we forgot to add the loading indicator in the source view. I solved those two point here: https://github.com/alinedoleron/liferay-portal/pull/247. Can you squash those changes in this PR? Thanks :)

**Comment by alinedoleron** [comment]
> Hi @alinedoleron, I noticed an issue while going back and forth from the diagram view to the source view and also remembered that we forgot to add the loading indicator in the source view. I solved those two point here: [alinedoleron#247](https://github.com/alinedoleron/liferay-portal/pull/247). Can you squash those changes in this PR? Thanks :)

Thank you, @naraandrade! I'll do that!

**Comment by alinedoleron** [comment]
ci:stop

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by alinedoleron** [comment]
ci:test:workflow

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
