### PR TITLE
LPS-136568 Use the site defaul lang as defaul lang in the cal event creation form

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:calendar

**Comment by rafaprax** [comment]
Thx @robertoDiaz

**Comment by seltong** [comment]
Just started reviewing :)

**Review by seltong — APPROVED** [review]
Nice!

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/468

**Pull request closed without merging**
