### PR TITLE
LPS-201214 Replace AUI() usages in portal-workflow-kaleo-forms-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-201214)

## Steps

**Case 1: Export Kaleo Form**

- Go to Content & Data > Kaleo Forms Admin
- Create a Kaleo Form
- In the processes view > Click on ellipsis > Export 
- See the modal
Screenshot 2023-11-10 at 14 29 50

**Case 2: Change Kaleo Form fields**

- With the Kaleo From created 
- In the processes view > Click on ellipsis > edit
- Go to Fields tab > click on "view fields" of any of the fields row > see preview modal shows
- Click on any field ellipsis > Choose > see "Selected Field Set" changes

https://github.com/liferay-echo/liferay-portal/assets/91208451/6e8d6e72-8a68-4e3f-a219-e932e3ad9acc

**Case 3: Change Kaleo assigned form**

- With the Kaleo From created 
- In the processes view > Click on ellipsis > edit
- Go to Forms tab > Click on the form ellipsis > Unassign form > See that in the Form row, the form dissapears
- Click on the form ellipsis > Edit Form > see modal appears
https://github.com/liferay-echo/liferay-portal/assets/91208451/b10d92c1-f512-4705-964f-6dbf4b3b9149

**Case 4: Change Kaleo workflow**

- With the Kaleo From created 
- In the processes view > Click on ellipsis > edit
- Go to Workflow tab > Add a workflow
- Click on the workflow ellipsis > Edit > see modal appears
- Click on the workflow ellipsis > Choose > see "Selected Workflow: " changes

https://github.com/liferay-echo/liferay-portal/assets/91208451/940985e8-5e48-4794-bf37-78ba372b2252

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:kaleo-forms

**Comment by MarinhoFeliphe** [comment]
Hello @DiegoHu97, I'm gonna review your changes as soon as possible in the next week.

Thanks for your contribution!

**Comment by MarinhoFeliphe** [comment]
Hello @DiegoHu97 there are some unique failures related to your changes, could you please take a look at them?

[CPKaleoformsadmin#EditSingleApproverWorkflowViaSourceTabViaAddProcess](https://testray.liferay.com/reports/production/logs/2023-11/test-1-35/test-portal-acceptance-pullrequest(master)/4921/functional-tomcat90-mysql57-jdk8/0/15/LocalFile.CPKaleoformsadmin_EditSingleApproverWorkflowViaSourceTabViaAddProcess/index.html.gz?authuser=0)

[CPKaleoformsadmin#EditUploadedWorkflowViaViewTabViaAddProcess](https://testray.liferay.com/reports/production/logs/2023-11/test-1-35/test-portal-acceptance-pullrequest(master)/4921/functional-tomcat90-mysql57-jdk8/0/16/LocalFile.CPKaleoformsadmin_EditUploadedWorkflowViaViewTabViaAddProcess/index.html.gz?authuser=0)

[CPKaleoformsadmin#AddProcessWithNewFieldSetAndWorkflowViaSourceTab](https://testray.liferay.com/reports/production/logs/2023-11/test-1-35/test-portal-acceptance-pullrequest(master)/4921/functional-tomcat90-mysql57-jdk8/0/12/LocalFile.CPKaleoformsadmin_AddProcessWithNewFieldSetAndWorkflowViaSourceTab/index.html.gz?authuser=0)

I'm checking if the other failures are related as well, but for while I believe makes sense share with you these ones.

Best Regards,
Feliphe

**Comment by DiegoHu97** [comment]
I will take a look, thanks! @MarinhoFeliphe

**Comment by DiegoHu97** [comment]
Hi @MarinhoFeliphe , I just fixed the tests failing, thanks for the review!

**Comment by MarinhoFeliphe** [comment]
Hey @DiegoHu97 nice job!

there are only two functional tests failing that went unnoticed (my fault):

[CPKaleoformsadmin#ViewUnpublishedWorkflowDefinitionsMenulist](https://testray.liferay.com/reports/production/logs/2023-11/test-1-38/test-portal-acceptance-pullrequest(master)/9812/functional-tomcat90-mysql57-jdk8/0/10/LocalFile.CPKaleoformsadmin_ViewUnpublishedWorkflowDefinitionsMenulist/index.html.gz?authuser=0)

[CPKaleoformsadmin#EditCreateTaskForm](https://testray.liferay.com/reports/production/logs/2023-11/test-1-38/test-portal-acceptance-pullrequest(master)/9812/functional-tomcat90-mysql57-jdk8/0/10/LocalFile.CPKaleoformsadmin_EditCreateTaskForm/index.html.gz?authuser=0)

could you please take a look?

let me know if you need any help,

Thank you!!

**Comment by DiegoHu97** [comment]
Hi @MarinhoFeliphe , Could you add the steps to reproduce those tests in the portal (in the UI)? I'm not able to identify the steps looking at the Poshi tests, thanks!

**Comment by MarinhoFeliphe** [comment]
Hey @DiegoHu97, sure, I've recorded a video because the steps are too long:

[CPKaleoformsadmin#EditCreateTaskForm](https://testray.liferay.com/reports/production/logs/2023-11/test-1-38/test-portal-acceptance-pullrequest(master)/9812/functional-tomcat90-mysql57-jdk8/0/10/LocalFile.CPKaleoformsadmin_EditCreateTaskForm/index.html.gz?authuser=0):

this one I believe is related to this page below, if you watch the video you can see that this page is not this way:

image

Steps:

[EditCreateTaskForm_steps.zip](https://github.com/liferay-workflow/liferay-portal/files/13493378/EditCreateTaskForm_steps.zip)

[CPKaleoformsadmin#ViewUnpublishedWorkflowDefinitionsMenulist](https://testray.liferay.com/reports/production/logs/2023-11/test-1-38/test-portal-acceptance-pullrequest(master)/9812/functional-tomcat90-mysql57-jdk8/0/10/LocalFile.CPKaleoformsadmin_ViewUnpublishedWorkflowDefinitionsMenulist/index.html.gz?authuser=0):

This one is related to this page:

image

Steps:

[Uploading ViewUnpublishedWorkflowDefinitionsMenulist.zip…]()

**Comment by DiegoHu97** [comment]
Hey @MarinhoFeliphe , I cannot open [ViewUnpublishedWorkflowDefinitionsMenulist.zip…](https://github.com/liferay-workflow/liferay-portal/pull/1015), could you take a look? Thanks!

**Comment by DiegoHu97** [comment]
@MarinhoFeliphe Hi! I have updated the case [CPKaleoformsadmin#EditCreateTaskForm](https://testray.liferay.com/reports/production/logs/2023-11/test-1-38/test-portal-acceptance-pullrequest(master)/9812/functional-tomcat90-mysql57-jdk8/0/10/LocalFile.CPKaleoformsadmin_EditCreateTaskForm/index.html.gz?authuser=0), the other one works fine in manual test, let's see if CI passes, thanks!

**Comment by MarinhoFeliphe** [comment]
> Hey @MarinhoFeliphe , I cannot open https://github.com/liferay-workflow/liferay-portal/pull/1015, could you take a look? Thanks!

I think it's too big, let's wait for the results of the kaleo-forms suite

**Comment by MarinhoFeliphe** [comment]
Hi @DiegoHu97 sorry for the late reply,

The tests are still failing and I can't pull your changes and help you to fix it because I need to deliver a feature as soon as possible next week :cry:,

so my suggestion is you try to set up your environment to be able to run functional tests in liferay portal it'll help you in this task and in many others.

Thank you!

**Comment by DiegoHu97** [comment]
Hey @MarinhoFeliphe ! I talked to one of our qa and he said that those failing tests are not related with my changes, it was fixed here https://liferay.atlassian.net/browse/LPS-190733, thanks!

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97, there are some failed tests related to your changes found in this run.
https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2472872901

**Comment by Tim-Cao** [comment]
See poshi update here https://github.com/liferay-workflow/liferay-portal/pull/1035

**Comment by seltong** [comment]
Thank you, @Tim-Cao! I will take a look at this ASAP

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-workflow/liferay-portal/pull/1035

**Pull request closed without merging**
