### PR TITLE
LPS-187901  Eliminate the WorkflowEngineManager interface

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi Team,

Forwarded from:https://github.com/liferay-core-infra/liferay-portal/pull/5207

I have submitted this PR to eliminate the WorkflowEngineManager interface, its implementation, and associated utilities. It has been determined that this interface serves no purpose in the current workflow application. You can find more details about this change in [PTR-4161](https://liferay.atlassian.net/browse/PTR-4161).

Additionally, I am seeking assistance regarding an issue related to SF failures as I lack knowledge of this part to know which is the appropriate solution.

Thanks for your review.

Best regards,
Janis.

### CODE REVIEW

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
Hi @JanisZhang sorry for delay,

I'm gonna review this on Monday after ci failures checks,

Thank you!

**Comment by JanisZhang** [comment]
Thanks @MarinhoFeliphe !

**Comment by JanisZhang** [comment]
ci:stop

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
Hello @JanisZhang,

> Additionally, I am seeking assistance regarding an issue related to SF failures as I lack knowledge of this part to know which is the appropriate solution.

I believe the changes (913e774ed7061b7d5d68fdd23566e884267eb3e2 and f68922c4bc24f56b521bc2d861e6c7ab7a113041) will fix the SF issue, but we won't ship them now because it's breaking other functionality.

As soon as I make sure the SF issue is only related to replacing `auy:icon` and `liferay-ui:tabs` we can push your changes without fixing the SF issue.

I've resent [here](https://github.com/liferay-workflow/liferay-portal/pull/978) with a little change related to semantic versioning,

Thanks for your contribution!

**Pull request closed without merging**
