### PR TITLE
LPS-142319 Run fetch function when page/pageSize change

### PR DESCRIPTION
**Pull request by ramonmsp**
Issue: [LPS-142319](https://issues.liferay.com/browse/LPS-142319)

### CODE REVIEW

**Comment by jotascript** [comment]
Just started reviewing :)

**Review by jotascript — APPROVED** [review]

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:stop

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by anabuchmann** [comment]
ci:test:relevant

**Comment by anabuchmann** [comment]
ci:stop

**Comment by anabuchmann** [comment]
ci:forward

**Pull request closed without merging**
