### PR TITLE
[TS] LPS-166206 Encode special characters before decoding it to successfully save notification template

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi Team,

**Issue**
In the workflow definition, when creating a new notification, the (freemarker) template is not saved successfully when it contains a "%" character. Also, when the notification is saved (with or without the special character) and we want to visit that notification again, the page goes blank with an error that is caused by an undefined value [here](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/diagram-builder/components/sidebar/sections/notifications/NotificationsInfo.js#L153-L156).
`utils.js:13 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at getRecipientType (utils.js:13:9)
    at NotificationsInfo (NotificationsInfo.js:154:3)`

LPS: https://issues.liferay.com/browse/LPS-166206

**Fix**
Encoding the content before decoding it.
Null check for Recipient Type

Could you please review it?
Thank you.

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
> Hi @naraandrade
> 
> could you please push this forward?
> 
> Thanks, Roland

Sorry about the delay for reviewing the PR, I will forward it now :)

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
