### PR TITLE
LPS-159995 Fix cannot update notification if language is not English

### PR DESCRIPTION
**Pull request by binhtran92**
Hi guys,
This is related to ticket: https://issues.liferay.com/browse/LPS-159995
Please help to review.
Thank you

### CODE REVIEW

**Comment by binhtran92** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by binhtran92** [comment]
Hi @naraandrade, thank you for reviewing.
I push a new commit to resolve the conflict. 
About the test failure, I don't think it is related to my change.

**Comment by binhtran92** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
@binhtran92 the failures don't seem related to your PR. I'll try `ci:forward` one more time and if it doesn't work you can send the PR directly to Brian.

**Pull request closed without merging**
