### PR TITLE
LPS-138057

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Workflow team,

This may not be the best fix, because we're kind of duplicating logic with https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/view_calendar_menus.jspf#L434-L454.

However, I tried extracting that logic to the calendar_util, but I still couldn't figure out a way to call it from the appropriate spot to get the hidden menu items, and compare it against the list of menu items in the calendar, to determine whether to set "hasMenuItems" to true. So I implemented this fix instead.

Let me know if you know of a better way to fix this.

I tested this with various Role configurations to make sure that the arrow was hidden iff there were no menu items. The one test I didn't do was with the "Other calendars" list, because I was unable to figure out how to add a calendar to the "Other calendars" list. But that logic is pretty straightforward so I'm not too worried about it - basically, if we're in the "Other calendars" list, then "Hide" is always a visible menu item, so we set "hasMenuItems" to true every time.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
ci:help

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by mbowerman** [comment]
Does the test failure mean we need to add a semantic versioning commit (I guess because I added new methods to view_calendar.jsp)? If so, I'm recompiling the latest master now so that I can run `gradlew baseline` against it.

**Comment by mbowerman** [comment]
I rebased my branch to the latest version of master (96b19e314abcd1612ae3ad584f975712c3add94b). I then ran `gradlew baseline` against the `calendar-web` module. However, it didn't make any changes.

**Comment by mbowerman** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
All right @mbowerman , I'm sorting some variables in alphabetical order before to forward to Brian.

Thank you!

**Comment by MarinhoFeliphe** [comment]
resent here [#509](https://github.com/liferay-workflow/liferay-portal/pull/509)

**Pull request closed without merging**
