### PR TITLE
LPS-120643 Update deprecated test

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Review by liferay-workflow — APPROVED** [review]

**Review by rafaprax — APPROVED** [review]

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:close

**Pull request closed without merging**
