### PR TITLE
LPS-176769 Remove the logic to get a value by the key that never existed in class MultiLanguageKaleoTaskAssignmentSelector

### PR DESCRIPTION
**Pull request by W2jx**
https://issues.liferay.com/browse/LPS-176769

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by W2jx** [comment]
Hi @MarinhoFeliphe , looks like you need to re-run ci:forward.

**Comment by MarinhoFeliphe** [comment]
@W2jx sorry for delay,

Resent here: https://github.com/brianchandotcom/liferay-portal/pull/130996

**Comment by MarinhoFeliphe** [comment]
Failures are not related.

**Pull request closed without merging**
