### PR TITLE
[TS] LPS-124808

### PR DESCRIPTION
**Pull request by jonathanmccann**
I tried various ways to get a script tag to run within the title but was unable to do so. If you are able to produce an XSS issue due to removing the escape please let me know and I can revisit the solution.

If there are any questions please let me know.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
