### PR TITLE
[Test Fix] LPD-22390 Fix Calendar functional test failures related to allday events

### PR DESCRIPTION
**Pull request by julschong**
Hi Team,
Issue: https://liferay.atlassian.net/browse/LPD-22389
This came up when I was scanning and reviewing for any CLDR related functional test failures. Though not related to CLDR, I thought it would be good to fix these issues

```
LocalFile.NewEvent#AddAllDayWithRemindersEnabled
LocalFile.EventDetails#EditAllDayReminders
LocalFile.EventDetails#EditAllDay
LocalFile.CalendarConfiguration#ConfigureEventsDisplaySettingsAndViewEvents
LocalFile.CalendarComment#AddToEventAllDay
LocalFile.NewEvent#AddAllDay
LocalFile.NewEvent#AddAllDayWithUserInviteAccept
LocalFile.NewEvent#AddAllDayWithTag
LocalFile.NewEvent#AddAllDayRSVPYes
LocalFile.ManageCalendar#ChangeCalendarTypeForAllDayEvent
LocalFile.EventDetails#EditAllDayWithUserInvite
LocalFile.CalendarLocalization#ViewShowMoreLocalization
```

In [LPS-83034](https://github.com/liferay/liferay-portal/commit/152040bfcf4efbc04ceb75880a742a2123ad1a38#diff-b78040ff5a30d10cbd8b9e6ac19160a19209a70d35003b4ce3e38bdece51c68cR956-R960), when allday check box is checked, it resets the time to 12:00 AM and 11:59pm. But functional tests are still looking for a specific startTime and endTime.
This pull updates accordingly.

I have not tested all of them locally, so we need to look at test results carefully and make sure I didn't break anything unintentionally.

Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:calendar

**Comment by julschong** [comment]
ci:report:https://github.com/liferay-core-infra/liferay-portal/pull/6850

**Comment by julschong** [comment]
ci:report:2558643999

**Comment by julschong** [comment]
checked all thes test cases listed, all passed: https://testray.liferay.com/home/-/testray/case_results/index?testrayBuildId=2558643999

```
LocalFile.NewEvent#AddAllDayWithRemindersEnabled
LocalFile.EventDetails#EditAllDayReminders
LocalFile.EventDetails#EditAllDay
LocalFile.CalendarConfiguration#ConfigureEventsDisplaySettingsAndViewEvents
LocalFile.CalendarComment#AddToEventAllDay
LocalFile.NewEvent#AddAllDay
LocalFile.NewEvent#AddAllDayWithUserInviteAccept
LocalFile.NewEvent#AddAllDayWithTag
LocalFile.NewEvent#AddAllDayRSVPYes
LocalFile.ManageCalendar#ChangeCalendarTypeForAllDayEvent
LocalFile.EventDetails#EditAllDayWithUserInvite
LocalFile.CalendarLocalization#ViewShowMoreLocalization
```

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

@julschong thanks for your contribution!

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
