### PR TITLE
LRQA-59713 Remove test from quarantine

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Review by rodrigocunhaa — APPROVED** [review]

**Comment by rodrigocunhaa** [comment]
@gabrielpramos , the `ViewProcessWithComments` test still failed on `ci:test:workflow` suite. Could you please check it?

**Review by rodrigocunhaa — CHANGES_REQUESTED** [review]
@gabrielpramos , the `ViewProcessWithComments` test still failed on `ci:test:workflow` suite. Could you please check it?

**Comment by rafaprax** [comment]
@gabrielpramos and @rodrigocunhaa any updates about this pr?

Thx

**Comment by gabrielpramos** [comment]
I'll finish this pr and the #76 today, I was working on a subtask from the new story

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Comment by gabrielpramos** [comment]
ci:forward

**Pull request closed without merging**
