### PR TITLE
LPS-138569 Create Join XOR node type component

### PR DESCRIPTION
**Pull request by jotascript**
Issue story: [LPS-138569](https://issues.liferay.com/browse/LPS-138569)

This PR-514(LPS-138569) needs to wait for [PR-513 (LPS-137752)](https://github.com/liferay-workflow/liferay-portal/pull/513) to prevent conflicts.

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by naraandrade — APPROVED** [review]

**Review by ramonmsp — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by rafaprax** [comment]
Hey @anabuchmann, Can you please forward this to BChan manually?

Thx

**Review by rafaprax — APPROVED** [review]

**Comment by anabuchmann** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/106707

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
