### PR TITLE
LPD-16334 Unauthorized access to workflow definition via API

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-16334](https://liferay.atlassian.net/browse/LPD-16334)

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:test:workflow-metrics

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/1150

**Pull request closed without merging**
