### PR TITLE
[7.4 Only] LPS-122712 Enable search empty state to be displayed on workflow step

### PR DESCRIPTION
**Pull request by naraandrade**
Story: LPS-105491 cc: @albinojunior @gabrielpramos

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:app-builder

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:app-builder

**Review by rafaprax — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
