### PR TITLE
LPS-120432 Remove unnecessary useMemo occurrences and improve the metrics pages performance

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Hey @albinojunior,

Conflicting files
modules/dxp/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/components/instance-list-page/modal/instance-details/InstanceDetailsModalBody.es.js

Please resend.

Thanks!

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
