### PR TITLE
LPS-168594 Workflow compatibility with Solr

### PR DESCRIPTION
**Pull request by BryanEngler**
Just wanted to run these changes to the workflow modules by you guys before I forward to bchan.

Let me know if you have any questions or concerns. Thanks!

Test results already available, our QA team is in the process of verifying the workflow-metrics suite - BryanEngler#714 (comment)

https://issues.liferay.com/browse/LPS-168594

### CODE REVIEW

**Comment by xbrianlee** [comment]
`workflow-metrics` failures from https://github.com/BryanEngler/liferay-portal/pull/714#issuecomment-1331648651 don't appear to be related to these changes. See [generate-testray-csv](https://test-1-1.liferay.com/userContent/jobs/generate-testray-csv/builds/2041/testray-results.csv) as well.

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
Hello @BryanEngler,

Just to be on the same page I've just reviewed these three commits below about workflow:

1. https://github.com/liferay-workflow/liferay-portal/pull/860/commits/716728d1eda850fa7f95bc760d321e2b056c14f8
2. https://github.com/liferay-workflow/liferay-portal/pull/860/commits/83826968b918a01a2a3e7beb9d569712f33025f5
3. https://github.com/liferay-workflow/liferay-portal/pull/860/commits/b2daf14adc99711ca6ec250b017e94395e93323d

Your changes looks good to me, but I have one question.

I understood that you want to disable Workflow Metrics based on `searchCapabilities.isWorkflowMetricsSupported()` flag and you've replaced all:

````
@Reference(target = "(search.engine.impl=Elasticsearch)")
private volatile SearchEngineAdapter _searchEngineAdapter;
````

to:

````
@Reference
protected SearchEngineAdapter searchEngineAdapter;
````

But I've checked and I found only [this one](https://github.com/liferay/liferay-portal/blob/2bcdea8afe09f96742943e63ff87a2e1d2c08620/modules/apps/portal-search-solr8/portal-search-solr8-impl/src/main/java/com/liferay/portal/search/solr8/internal/search/engine/adapter/SolrSearchEngineAdapterImpl.java#L49-L48) implementation of SearchEngineAdapter.

So I'd like to know if we have to migrate to Solr search engine to continue using Workflow Metrics or I'm missing something?

Thank you,
Feliphe

**Comment by MarinhoFeliphe** [comment]
@sirfabios or @evanilson-santana 

Could you please double check if [these fails](https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=2090779158) related to Workflow are not related

Thank you,
Feliphe

**Comment by sirfabios** [comment]
Hello @MarinhoFeliphe 
They are not related.

**Comment by MarinhoFeliphe** [comment]
Thank you, @sirfabios

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by BryanEngler** [comment]
@MarinhoFeliphe Thanks for the review.

There is nothing else you guys need to do or migrate. 

We have another implementation of SearchEngineAdapter -> ElasticsearchSearchEngineAdapterImpl

This Elasticsearch SearchEngineAdapter is our default adapter, and it is compatible with workflow, which is why it was previously "required" by target = "(search.engine.impl=Elasticsearch)". Now, either SearchEngineAdapter can satisfy the reference, but in the java logic only the Elasticsearch adapter will function. Ill go ahead and close the PR, if you have any other questions let me know. Thanks again

**Pull request closed without merging**
