### PR TITLE
LPD-28216

### PR DESCRIPTION
**Pull request by carolmariaabb**
@rijema https://liferay.atlassian.net/browse/LPD-28216

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Comment by carolmariaabb** [comment]
ci:stop

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
Note: This was previously approved, it is adding now a commit to use clay taglib.

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Comment by carolmariaabb** [comment]
ci:test:playwright

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Comment by carolmariaabb** [comment]
ci:test:workflow

**Comment by carolmariaabb** [comment]
ci:forward

**Pull request closed without merging**
