### PR TITLE
LPS-173741 Initialize the workflow context to avoid NPE and allow the transition request to succeed

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
@jonathanmccann,

I've tested the endpoint by using these changes that we talked in the PTR, but I noticed that there is another issue, 

the NPE isn't happening anymore, when we perform the request the instance is updated properly but the task gets stuck as PENDING, it's occurring because this endpoint only change the transition but doesn't complete the task and it doesn't make sense.

So if your needs is change a task transition, if so, we're using this another one to do that:

`````
curl -X 'PATCH' \
  'http://localhost:8080/o/headless-admin-workflow/v1.0/workflow-tasks/change-transition' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'x-csrf-token: dJvtEiag' \
  -d '[
  {
    "comment": "foo comment",
    "transitionName": "approve",
    "workflowTaskId": 43257
  }
]
`````

Best Regards,
Feliphe

**Comment by jonathanmccann** [comment]
Thank you, that endpoint seems to work so I will pass that along.

In regards to the current changes, I still feel like they make sense, unless you're thinking of removing this API altogether.

**Comment by MarinhoFeliphe** [comment]
This endpoint is a little bit old (2015) I need to investigate what is its purpose in detail, I'll work under these changes

Thank you!

**Comment by MarinhoFeliphe** [comment]
FYI, https://issues.liferay.com/browse/LPS-174366

**Pull request closed without merging**
