### PR TITLE
LPS-137234 Show asset title label with ellipsis

### PR DESCRIPTION
**Pull request by ramonmsp**

### CODE REVIEW

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:relevant

**Review by jotascript — APPROVED** [review]

**Comment by ramonmsp** [comment]
ci:forward

**Pull request closed without merging**
