### PR TITLE
LPS-125647

### PR DESCRIPTION
**Pull request by yxingwu**
I am not sure it's the right place to review.
The fix of [LPS-125647](https://issues.liferay.com/browse/LPS-125647) and [LPS-125648](https://issues.liferay.com/browse/LPS-125648) are in the same PR. Because both of them need to modify `yarn.lock `

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Review by albinojunior — APPROVED** [review]
Thanks for this fix @yxingwu

**Comment by albinojunior** [comment]
FYI @oliveiraaraujo @matuzalemsteles @diegonvs, also updates the `axios` dependency of the module `dynamic-data-mapping-form-field-type.

**Comment by albinojunior** [comment]
ci:test:workflow

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
