### PR TITLE
LPS-122477 Fix redirect after assigning workflow task to self

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-122477

Notes from @noornajj 
> The issue was the page was not redirecting to the Assigned to Me tab after assigning a workflow task to self.
> I fixed this issue by changing the redirect value in workflow_task_action.jsp from currentURL to redirectURL.toString().

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
This failure here doesn't seem to be related to the fix.
@rafaprax is this PR ok to be forwarded?

**Comment by rafaprax** [comment]
Sorry, @noornajj 

I forgot to forward this.

Thanks for your fix

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
@rodrigocunhaa The unique error here seems related to @noornajj changes. Can you please confirm that?

Thx

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
ci:test:bundle

**Comment by rodrigocunhaa** [comment]
Hi @SamZiemer @noornajj @rafaprax , the test that failed is actually related to this PR. When entering on a task and using the "Assigne To Me" option, the system is redirecting to the "Assigned to me" tab instead of staying inside the task. See:


Bug

**Comment by rafaprax** [comment]
Hey @noornajj,

Can you please fix the broken scenario above and resend?

Thanks

**Pull request closed without merging**
