### PR TITLE
[7.4 Only] LPS-124516 Fix alignment of info icon

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:forward

**Comment by albinojunior** [comment]
ci:forward

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/174

**Pull request closed without merging**
