### PR TITLE
LPD-30650 Allow Workflow admin to see date and user information on history

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPD-30650
Story: https://liferay.atlassian.net/browse/LPD-29233

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:workflow

**Comment by marcelabc** [comment]
ci:test:playwright

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:playwright

**Comment by marcelabc** [comment]
ci:test:workflow

**Comment by marcelabc** [comment]
ci:report:46442250

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:test:workflow

**Comment by marcelabc** [comment]
ci:test:playwright

**Comment by marcelabc** [comment]
ci:report:47213277

**Comment by marcelabc** [comment]
ci:report:47260293

**Comment by marcelabc** [comment]
@danvb112 I think the failures are related. Can you see and fix the poshi tests please?

**Comment by marcelabc** [comment]
Adding the Label Blocked because we will investigate the CI failures. Thank you!

**Comment by danvb112** [comment]
Sent to: https://github.com/liferay-workflow/liferay-portal/pull/1209

**Pull request closed without merging**
