### PR TITLE
LPD-16337 Calendar events are not showing correct times with respect to timezone that use Day light savings

### PR DESCRIPTION
**Pull request by seltong**
Related issue: [LPD-16337](https://liferay.atlassian.net/browse/LPD-16337)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:help

**Comment by marcelabc** [comment]
Hey @MarinhoFeliphe,
Can you review this PR please? :smile: 

cc: @guilhermedcamacho

**Comment by MarinhoFeliphe** [comment]
Hi @marcelabc I'll finish the review tomorrow.

**Comment by MarinhoFeliphe** [comment]
Me and @seltong are investigating another solution because this one is breaking the same use case for non recurrent events,

so I'll close this pull request since the task will be back to in progress.

Thank you!

cc: @marcelabc @samuelromeiro @guilhermedcamacho

**Pull request closed without merging**
