### PR TITLE
LPD-31465 URL change when accessing notification details

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-31465](https://liferay.atlassian.net/browse/LPD-31465)

[LPD-31465]: https://liferay.atlassian.net/browse/LPD-31465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:forward

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
