### PR TITLE
[TS] LPS-193988 Cannot add Task Timer Notification to Workflow Definition

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
If you add any XML script to have Task Timer Notification in Workflow, you can successfully save the Workflow Definition, but the XML you added gets removed.

Adding Task Timer Notification through the Diagram view is currently not implemented (see https://liferay.atlassian.net/browse/LPS-170737#icft=LPS-170737). However, adding it through XML should work. See https://liferay.slack.com/archives/CL8QTMKGQ/p1688556267627419

Proposed Solution
========
[Adding the code to process timer notifications](https://github.com/liferay-workflow/liferay-portal/commit/1d566f5a4fb0cde49c47a026e8d250deb1eb05c8) and [fixing a bug](https://github.com/liferay-workflow/liferay-portal/commit/4f663780e6af4c55fbff013c5c61143fc8af2cab) that caused the generation of empty `<timer-notification>` tags each time the definition is saved almost solves the issue, but upon parsing the definition, the following exception will be thrown:

`com.liferay.portal.kernel.xml.DocumentException: Error on line 255 of document  : cvc-complex-type.2.4.a: Invalid content was found starting with element '{"urn:liferay.com:liferay-workflow_7.4.0":execution-type}'. One of '{"urn:liferay.com:liferay-workflow_7.4.0":recipients}' is expected.`

What I gathered from reading this message and examining XML workflow definitions is that `<recipients>` elements are required to have an `receptionType="to"` attribute if `<execution-type>` is `onAssignment` .

If I add the `receptionType="to"` attribute to the `<recipients>` tag the parsing error won't occur, but instead, the `<timer-notification>` tag won't be processed.
The reason for this is that for `<recipients>` elements having attributes and children elements are [treated as mutually exclusive](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/source-builder/xmlSchemaUtil.js#L123-L143). If the 
`<recipients>` element has an attribute, such as `receptionType="to"`, it's child `<user />` elements won't be processed, rendering the whole `<timer-notification>` as invalid, stopping its processing.

Could you please help me to resolve this dilemma by helpig me to decide whether modifications should be done on the processing side (for example handling the case where elements can have both attributes and children) or on the validation side (so that `<recipients>` elements are not required to have an `receptionType="to"` attribute if `<execution-type>` is `onAssignment`)?

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-193988

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear Team,

I have checked the test failures are they don't seem to be related to the solution.

Please let me know if there are any updates on the review.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by naraandrade** [comment]
> Dear Team,
> 
> I was wondering if you could find the time to review the pull request. Please let me know if you need any help or explanation.
> 
> Thank you and best regards, István

Hi @IstvanD, sorry for the delay! I'll be reviewing this PR today.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Hi @IstvanD, I tested your PR but it does not seem to solve the issue after we return to the Diagram View. The notification timer is removed, even if I don't enter the timer section in the review task (which will override what was defined in the XML, as expected).

About your question:

> Could you please help me to resolve this dilemma by helpig me to decide whether modifications should be done on the processing side (for example handling the case where elements can have both attributes and children) or on the validation side (so that <recipients> elements are not required to have an receptionType="to" attribute if <execution-type> is onAssignment)?

Is expected that we define a reception type every time we use the notification type "email". So I believe the current behavior is current.

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @IstvanD, I tested your PR but it does not seem to solve the issue after we return to the Diagram View. The notification timer is removed, even if I don't enter the timer section in the review task (which will override what was defined in the XML, as expected).

About your question:

> Could you please help me to resolve this dilemma by helpig me to decide whether modifications should be done on the processing side (for example handling the case where elements can have both attributes and children) or on the validation side (so that elements are not required to have an receptionType="to" attribute if is onAssignment)?

It's expected that we define a reception type every time we use the notification type "email". So I believe the current behavior is correct.

**Comment by IstvanD** [comment]
Hi @naraandrade thank you for your feedback.

> I tested your PR but it does not seem to solve the issue after we return to the Diagram View. The notification timer is removed, even if I don't enter the timer section in the review task (which will override what was defined in the XML, as expected).
In the Slack discussion in the description it was stated that

> It's possible to use it directly in the XML, but you would need to update the definition from the source view and avoid going to the diagram to not lose it (sorry for the inconvenience).
If I understand correctly, adding the Timer Notification in the Diagram View will be added as a feature in [LPS-170737](https://liferay.atlassian.net/browse/LPS-170737) and for now, the expected behavior is that it can be added in the XML but it won't be retained when switching to Diagram View.

Please let me know if I am missing something here.

Thank you and best regards,
István

**Comment by naraandrade** [comment]
> Hi @naraandrade thank you for your feedback.
> 
> > I tested your PR but it does not seem to solve the issue after we return to the Diagram View. The notification timer is removed, even if I don't enter the timer section in the review task (which will override what was defined in the XML, as expected).
> > In the Slack discussion in the description it was stated that
> 
> > It's possible to use it directly in the XML, but you would need to update the definition from the source view and avoid going to the diagram to not lose it (sorry for the inconvenience).
> > If I understand correctly, adding the Timer Notification in the Diagram View will be added as a feature in [LPS-170737](https://liferay.atlassian.net/browse/LPS-170737) and for now, the expected behavior is that it can be added in the XML but it won't be retained when switching to Diagram View.
> 
> Please let me know if I am missing something here.
> 
> Thank you and best regards, István

Oh sorry, I did understand one of the steps incorrectly, my mistake. If we just stay at the source view, your fix works fine. I'll approve the PR now.

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by IstvanD** [comment]
Hi @naraandrade thank you for your answer.

If

> It's expected that we define a reception type every time we use the notification type "email"

is it OK to change the logic [here](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/source-builder/xmlSchemaUtil.js#L123-L143) to allow `<user />` elements to be nested in `<recipients receptionType="to">` elements? 

I am asking because of the seemingly faulty behavior I mentioned earlier:

> If I add the receptionType="to" attribute to the <recipients> tag the parsing error won't occur, but instead, the <timer-notification> tag won't be processed.
> The reason for this is that for <recipients> elements having attributes and children elements are [treated as mutually exclusive](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/source-builder/xmlSchemaUtil.js#L123-L143). If the
> <recipients> element has an attribute, such as receptionType="to", it's child <user /> elements won't be processed, rendering the whole <timer-notification> as invalid, stopping its processing.
Could you please help me to resolve this dilemma by helpig me to decide whether modifications should be done on the processing side (for example handling the case where elements can have both attributes and children) or on the validation side (so that <recipients> elements are not required to have an receptionType="to" attribute if <execution-type> is onAssignment)?

**Comment by naraandrade** [comment]
@IstvanD Actually, I just checked the Single Approver definition and there we have some examples of notification with `notification type` "email" that do not required the recipients tag to have the reception type defined... I think we have more than one problem here: 
1. We should be able to define children for recipients that have reception type defined. I don't see a reason why this cannot be allowed.
2. Notifications with type email should always have the reception type defined, unless we're using a default value defined in the frontend or backend to handle the case when it's not there.

Unfortunately, I cannot take much time to investigate this much further, but you could please take a look at how those two points are working on 7.3? We may have introduced those issues during the UI migration for 7.4. Thanks!

**Comment by IstvanD** [comment]
Hi @naraandrade I have force-pushed the changes that allow the `<recipients>` element to both have attributes and child elements.
However, I'm still getting this error on the backend:
`com.liferay.portal.kernel.xml.DocumentException: Error on line 255 of document  : cvc-complex-type.2.4.a: Invalid content was found starting with element '{"urn:liferay.com:liferay-workflow_7.4.0":execution-type}'. One of '{"urn:liferay.com:liferay-workflow_7.4.0":recipients}' is expected.`

I have checked the schema http://www.liferay.com/dtd/liferay-workflow-definition_7_4_0.xsd and found that the `timer-notification` element is of type `task-notification-complex-type` that doesn't have the `execution-type` defined as a potential sub-element.

**Comment by IstvanD** [comment]
Hi @naraandrade I force-pushed additional changes. With these, saving a workflow definition with `timer-notification` elements is possible if it only has sub-elements of `task-notification-complex-type`.

**Comment by naraandrade** [comment]
@IstvanD I'll review it again later today.

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
LGTM!

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
The failures don't seem related to the changes. I'll be forwarding this PR now.

**Comment by naraandrade** [comment]
ci:forward:force

**Comment by naraandrade** [comment]
Just started reviewing :)

**Pull request closed without merging**
