### PR TITLE
LPS-186252 Rename and move to internal.cache directory

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
See: https://github.com/liferay-workflow/liferay-portal/pull/949#issue-1780693273 and https://github.com/liferay-workflow/liferay-portal/pull/949#discussion_r1246830042

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by kristinonias** [comment]
Hi @MarinhoFeliphe and @ricardocousolr 

We have reviewed this PR and it looks good to go!

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Comment by ricardocousolr** [comment]
Thanks, everyone!

**Pull request closed without merging**
