### PR TITLE
LPS-172100 Move the resource-adding/deleting logic for KaleoDefinitionVersion into the LocalServiceImpl to ensure that the resources always do get added/deleted as they should

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-172100](https://issues.liferay.com/browse/LPS-172100)

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
I'll ask for the QA team verify if the failures are related.

Best Regards,
Feliphe

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/128423

**Pull request closed without merging**
