### PR TITLE
LPS-206048 Load content as XML when viewing a workflow definition source on CE mode because it's displaying the legacy UI source view

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Review by guilhermedcamacho — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
ci:stop

**Pull request closed without merging**
