### PR TITLE
LPS-121866 Migrate management toolbar v2 usages in calendar-web

### PR DESCRIPTION
**Pull request by markocikos**
See task details in https://issues.liferay.com/browse/LPS-121866

Test case:
1. Place the calandar widget on a page
2. Open 'Resources' tab
3. Test management toolbar features, see gif on bottom

/cc @jonmak08 @ambrinchaudhary @julien

after

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:calendar

**Comment by markocikos** [comment]
@rafaprax CI failure does not look related to this PR, it's in 'add event' modal :thinking:

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
Thank you @markocikos

**Pull request closed without merging**
