### PR TITLE
LPS-120958 Baseline

### PR DESCRIPTION
**Pull request by rafaprax**
/cc @arboliveira @liferay-search

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:search

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by arboliveira** [comment]
Reviewed; fixed Search related SF problems; forwarding as https://github.com/liferay-search/liferay-portal/pull/41. Thanks @rafaprax!! 😃

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
