### PR TITLE
LPD-24258 - Avoid conflicts with the property Transition.name and the parameter name, the name that should be evaluated here is the one passed as parameter of the method _toTransition.

### PR DESCRIPTION
**Pull request by victorKammerer**
[LPD-24258](https://liferay.atlassian.net/browse/LPD-24258)
This bug was found during a routine analysis. The case still covered by the test: "WorkflowMetricsAllItemsListReassignTasks#BulkReassignConsiderFilteredResultsFromAllItemsPage"

### CODE REVIEW

**Comment by victorKammerer** [comment]
This bug was found during a routine analysis. The case still covered by the test: "WorkflowMetricsAllItemsListReassignTasks#BulkReassignConsiderFilteredResultsFromAllItemsPage"

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hey @victorKammerer these changes looks good to me, but the commit message should be changed, I'd use this:

LPD-24258 - Avoid conflicts with the property `Transition.name` and the parameter `name`, the `name` that should be evaluated here is the one passed as parameter of the method `_toTransition`.

@victorKammerer don't forget to mention in this pull request that a test is already covering this use case.

Thank you!

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hey @victorKammerer could you please try to cover this use case with integration tests, the E2E test (WorkflowMetricsAllItemsListReassignTasks#BulkReassignConsiderFilteredResultsFromAllItemsPage) is catching this case but the proper way to cover this is using integration tests.

please see this example [here](https://github.com/brianchandotcom/liferay-portal/pull/101370/commits/cb573a8f5a99142359f5ebc5d1d36320fe045c5e), first you will have to add the field "transitions" into the array of the method `getAdditionalAssertFieldNames` this method is used to define wich fields will be used in the assertions, after you will have to set create the transitions in the method `randomInstance` this method is used to instantiate a random Transition dto.

@pedro-oliveira446 or @p-albuquerque please help @victorKammerer in case he has any questions.

Thank you!

**Comment by victorKammerer** [comment]
Sure, I'll be doing it! Also, thanks for the insights :)

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/150729

the integration tests for the class `InstanceResourceTest` are performed at ES level, it will lead a bigger effort than imagined before, so since `WorkflowMetricsAllItemsListReassignTasks#BulkReassignConsiderFilteredResultsFromAllItemsPage` is covering this I've forwarded to Brian.

Thank you!

**Pull request closed without merging**
