### PR TITLE
LPS-162888 Change the current step display logic

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-162888

### CODE REVIEW

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @kiwm, for the scenario described in the ticket, the correct fix would be fixing the return of the taskNames from the API (in the endpoint `/v1.0/processes/{processId}/instances/{instanceId}`). We can't receive an array of task names and show just the last item because in some cases the instance is in a stage with parallel tasks, so we should display more than one task at that moment.

**Comment by naraandrade** [comment]
@kiwm Feel free to send another PR later. For now, I'll be closing this one. Thanks :)

**Comment by kiwm** [comment]
Hi, @naraandrade I change the fix to the API but I don't know if is the correct fix. I kinda make the same fix but on the API end. I don't know if this is the right path. what do you think? I change the file /home/me/dev/projects/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-rest-impl/src/main/java/com/liferay/portal/workflow/metrics/rest/internal/resource/v1_0/InstanceResourceImpl.java

**Comment by naraandrade** [comment]
> Hi, @naraandrade I change the fix to the API but I don't know if this is the correct fix. I kinda make the same fix but on the API end. I don't know if this is the right path. What do you think? I change the file /home/me/dev/projects/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-rest-impl/src/main/java/com/liferay/portal/workflow/metrics/rest/internal/resource/v1_0/InstanceResourceImpl.java

Hi @kiwm, it wouldn't be the same fix (just sending the last item of the array). I believe you'll have to investigate the method that gets the current steps to send them in the request and understand why it's returning more than one step since the instance of the workflow is not in more than one step at the same time (which happens when in cases of parallel flows).
You can ask for help to one of the back-end devs of the BPM team (specifically, the Zulu squad).

**Pull request closed without merging**
