### PR TITLE
LPD-15167 getting group from calendar booking

### PR DESCRIPTION
**Pull request by linolaoj**
https://liferay.atlassian.net/browse/LPD-15167

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by linolaoj** [comment]
Hi, I've altered the commit to also apply the same logic to method `_getPortalURLOrCompanyPortalURL`.

**Comment by linolaoj** [comment]
ci:test:workflow

**Comment by linolaoj** [comment]
ci:workflow

**Comment by linolaoj** [comment]
ci:test:calendar

**Comment by linolaoj** [comment]
ci:reevaluate:1377401_15924

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/1059

@linolaoj nice job!! :tada:

**Pull request closed without merging**
