### PR TITLE
LPS-128487 Add margin to calendar's name

### PR DESCRIPTION
**Pull request by MariMalta**

### CODE REVIEW

**Comment by MariMalta** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
@naraandrade Is it ok for you?

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
> @naraandrade Is it ok for you?

Yes, it's ok :)

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
