### PR TITLE
LPS-182005 Updated style to display full title in table

### PR DESCRIPTION
**Pull request by henriquelimadotcom**
https://issues.liferay.com/browse/LPS-182005

### CODE REVIEW

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by Valmir-unicap** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Hi @henriquelimadotcom. I believe this is not a bug. I just left a comment on the ticket explaining why. I'll be closing your PR for now. Thanks for the contribution.

**Pull request closed without merging**
