### PR TITLE
LPS-125148 Fix ActivitySection sizing on Product Menu View

### PR DESCRIPTION
**Pull request by gabrielpramos**
@rafaprax @naraandrade @albinojunior

### CODE REVIEW

**Comment by rafaprax** [comment]
LGTM

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:forward

**Review by albinojunior — COMMENTED** [review]
Hey @gabrielpramos, you could have used just the `p-0` css class for it. But it's ok to me.

**Pull request closed without merging**
