### PR TITLE
LPS-146463 User still has permission to approve a task even after losing permission

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:stop

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @seltong,

The fails are not related.

cc: @anabuchmann

**Comment by MarinhoFeliphe** [comment]
@seltong,

please forward to Brian's repository and describe that the failures thrown by the relevant are unrelated.

Thank you!

**Comment by seltong** [comment]
Forwarded to Brian's repository [here](https://github.com/brianchandotcom/liferay-portal/pull/121891).

**Comment by MarinhoFeliphe** [comment]
Brian's requests: https://github.com/brianchandotcom/liferay-portal/pull/121891#issuecomment-1219829871

**Comment by MarinhoFeliphe** [comment]
cc: @seltong

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Resent here #806

**Pull request closed without merging**
