### PR TITLE
LPS-121134 Not needed

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Comment by inacionery** [comment]
It'll be fixed by https://github.com/liferay-echo/liferay-portal/pull/2442

**Comment by inacionery** [comment]
ci:close

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:forward

**Pull request closed without merging**
