### PR TITLE
[7.4 only] LPS-122385

### PR DESCRIPTION
**Pull request by albinojunior**
**Story:** [LPS-111511](https://issues.liferay.com/browse/LPS-111511) | /cc @gabrielpramos @naraandrade

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:stop

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
LGTM

**Review by gabrielpramos — APPROVED** [review]
LGTM

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielpramos** [comment]
rebased on [this pr](https://github.com/liferay-workflow/liferay-portal/pull/123)

**Pull request closed without merging**
