### PR TITLE
LPS-143315 Display transition info on sidebar when the transition is selected

### PR DESCRIPTION
**Pull request by jotascript**
Story: [LPS-140056](https://issues.liferay.com/browse/LPS-140056)

### CODE REVIEW

**Comment by jotascript** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by naraandrade — CHANGES_REQUESTED** [review]
The error for when the ID field is empty is not being displayed

**Review by naraandrade — APPROVED** [review]

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@jotascript Frontend tests related errors.

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by naraandrade** [comment]
ci:stop

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
