### PR TITLE
LPS-135553 Disable multiple choices for processVersionFilter on PerformanceByStepPage

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
