### PR TITLE
LPS-141719 Add back function to cancel button

### PR DESCRIPTION
**Pull request by jotascript**
Issue: [LPS-141719](https://issues.liferay.com/browse/LPS-141719)

### CODE REVIEW

**Comment by jotascript** [comment]
ci:test:sf

**Review by ramonmsp — APPROVED** [review]

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/109846

**Pull request closed without merging**
