### PR TITLE
LPS-169090 HRG_10 More options button in the Add calendar frame is not visible when the page is at 100% zoom

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related issue: https://issues.liferay.com/browse/LPS-169090

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @ericthmoritsuka, great job with the solution. I just noticed one issue to be fixed too. After we click in the More Options button it changes the title to Hide Options and JAWS is reading it as a link, not a button. Could you fix it as well? Thanks :)

**Comment by ericthmoritsuka** [comment]
Will do. I'll get back to you in a while. Thanks, @naraandrade!

**Comment by ericthmoritsuka** [comment]
I noticed that the margin-top of the More Options button was not the same as Hide Options button, so when we clicked on More Options, Hide Options would appear 1rem below it. I also changed that so More Options would also have the 1rem margin-top.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
@ericthmoritsuka You can send this PR directly to Brian. Please, remember to link here the new PR before closing this one. Thanks :)

**Comment by ericthmoritsuka** [comment]
PR sent here: https://github.com/brianchandotcom/liferay-portal/pull/129845

**Pull request closed without merging**
