### PR TITLE
LPS-107816 Version field should be integer

### PR DESCRIPTION
**Pull request by achaparro**
@jesseyeh-liferay

### CODE REVIEW

**Comment by achaparro** [comment]
ci:close

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@rafaprax the same tests file locally without the changes, is there someone in QA who can verify it?

Thanks.

**Comment by rafaprax** [comment]
Hey @achaparro, to run these tests locally it is required to set `liferay.mode=test` in `system-ext.properties` into your `tomcat-*/webapps/ROOT/WEB-INF/classes` folder.

Thx
/cc FYI @rodrigocunhaa

**Comment by achaparro** [comment]
Hi @rafaprax,

Sorry, I wrote my message really fast :) I meant that @jesseyeh-liferay  and I already tested some of the tests that are failing locally and they failed even without the changes.

@rodrigocunhaa could you check these tests in the CI?

Thanks.

**Comment by rafaprax** [comment]
Hey @achaparro, Did you tested with the `liferay.mode=test` configured in your tomcat(the CI runs with this configuration)? If not, probably almost all of the workflow metrics tests will fail. :)

And these failures seem to be related to these changes. If you take a look at this terms `{"term":{"version":{"value":"1.0"}}`, it is using the old version format.

Thx

**Comment by rafaprax** [comment]
ci:stop

**Comment by rodrigocunhaa** [comment]
Hi all,

I checked on Testray history and those tests only failed on this PR. It is most likely related.

**Comment by achaparro** [comment]
@rodrigocunhaa would you mind to test them locally without these changes? @jesseyeh-liferay and I were able to reproduce them without the changes.

Thanks.

**Comment by rodrigocunhaa** [comment]
@achaparro, do you mean the integration or the Poshi tests?

**Comment by jesseyeh-liferay** [comment]
@achaparro @rodrigocunhaa I ran the integration tests again without the changes from LPS-107816 and noticed the tests passed after setting `liferay.mode=test`. However, with LPS-107816, the tests failed, so I'll take another look.

**Comment by achaparro** [comment]
ok @jesseyeh-liferay thanks

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/375

**Pull request closed without merging**
