### PR TITLE
LPD-30650 Allow Workflow admin to see date and user information on history

### PR DESCRIPTION
**Pull request by danvb112**
Related issue: https://liferay.atlassian.net/browse/LPD-30650
Story: https://liferay.atlassian.net/browse/LPD-29233

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:workflow

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
CI failures are not related!

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
