### PR TITLE
LPS-188748 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira Issue: https://liferay.atlassian.net/browse/LPS-188748

approach suggested here:
https://github.com/liferay-core-infra/liferay-portal/pull/3935#issuecomment-1482047017

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:workflow

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:workflow

**Comment by leilanyaragao** [comment]
ci:test:workflow

**Comment by leilanyaragao** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
Thanks for your contribution!

I just needed to apply the suggested approach in `WorkflowMetricsSLADefinitionVersionLocalServiceTest`

Resent here: https://github.com/liferay-workflow/liferay-portal/pull/997

**Pull request closed without merging**
