### PR TITLE
LPS-122763 Remove deprecated class usage

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

`com.liferay.exportimport.data.handler.base.BaseStagedModelDataHandler`, as opposed to `com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler` adds the IDs of the `ChangesetEntries` to `ChangesetThreadLocal` during export in it's `exportStagedModel` method, so the `ChangesetEntries` will be deleted after publication.

This is necessary for the Export-Import portlet to detect that no `Calendars`, `CalendarResources` and `CalendarBookings` have been added/changed/deleted since the last publish date.

Thank you and best regards,
István

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
