### PR TITLE
LPS-146600

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello,

As discussed on https://issues.liferay.com/browse/PTR-3273

Please let me know if there are any issues with the changes and also feel free to rename and rework the new APIs.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
We are going to take a look at this.

Thank you,
Feliphe

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Hi, @jonathanmccann, could you check this semantic versioning failure? 

```
clean-up-java-processes:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/clean_up_java_processes.sh
[stopwatch] [run.batch.test.setup: 28:12.104 sec]
     [echo] run.batch.test.action.start.timestamp: 08-15-2022 09:00:34:195 PDT
     [echo] Checking for baseline log files.
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 67.1.0
[beanshell] 
[stopwatch] [run.batch.test.action: 8.429 sec]
     [echo] Semantic versioning is incorrect.
      [get] Getting: ${dependencies.url}/archive/test-1-15/test-portal-acceptance-pullrequest-downstream(master)/78582consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220815090042624.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220815090042624.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null359563959.properties
```

**Comment by jonathanmccann** [comment]
@seltong Thank you for catching that. I've updated the branch and will start the test again.

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
I'm taking a look

cc: @seltong and @jonathanmccann

**Comment by MarinhoFeliphe** [comment]
Hi @jonathanmccann,

There are others places that the fix must be applied,

image

My Submissions:

image

I'm working on it.

**Comment by MarinhoFeliphe** [comment]
Resent here: #790

**Pull request closed without merging**
