### PR TITLE
LPD-20145 Blank Page in Workflow Diagram View When Using Taks Timers

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-20145](https://liferay.atlassian.net/browse/LPD-20145)

### CODE REVIEW

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:test:metrics

**Comment by cgmonte** [comment]
ci:test:workflow

**Comment by cgmonte** [comment]
ci:test:workflow-metrics

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow-metrics

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
