### PR TITLE
LPS-146600 Use node's label and transition's label instead of their names when they are present

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
Hi @jonathanmccann,

I finished the fix, I'm just waiting for the relevant's tests

I'm going to run the workflow's tests as well.

Thank you,
Feliphe

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by jonathanmccann** [comment]
@MarinhoFeliphe Thank you for all of the additional changes. Let me know if there is anything else I can do.

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/122115

**Pull request closed without merging**
