### PR TITLE
Replace axios with fetch

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:workflow-metrics

**Comment by jotascript** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:workflow-metrics

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Review by ramonmsp — APPROVED** [review]

**Review by jotascript — APPROVED** [review]

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/109625

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Pull request closed without merging**
