### PR TITLE
LPD-28451 Adjust the payload of the CX workflow actions when it is attached to a non-task node

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPD-28451

### CODE REVIEW

**Review by linolaoj — APPROVED** [review]

**Comment by rijema** [comment]
ci:test:workflow

**Comment by linolaoj** [comment]
ci:test:workflow

**Comment by linolaoj** [comment]
Hi @rijema , can you please check if the tests WorkflowMetricsPerformanceByAssignee#AssigneeNamesBreaksIntoAnotherLine 
WorkflowNotifications#NotificationIsNotAvailableWhenOrderIsDeleted
are related?

**Comment by rijema** [comment]
@victorKammerer could you please run this locally?

**Comment by victorKammerer** [comment]
Both tests failing at master 7e41859f3a108ecd97b0bcbfd1bd1a77ae971473

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
