### PR TITLE
LPS-147421 Recurring event, can't unselect day of week

### PR DESCRIPTION
**Pull request by diogomelo09**
[LPS-147421](https://issues.liferay.com/browse/LPS-147421)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by diogomelo09** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
