### PR TITLE
LPS-120432 Remove unnecessary useMemo occurrences and improve the metrics pages performance

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Hey @albinojunior , please fix the conflicts and resend. Thx

**Pull request closed without merging**
