### PR TITLE
LPS-107816 SF

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @jesseyeh-liferay

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @jesseyeh-liferay, 

When I was reviewing your changes, I realized that it is possible exist in DB `kaleoDefinitionVersion.version` in a floating
point format, please see this chunk of code [KaleoDefinitionVersionUpgradeProcess.java#L136-L142](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/java/com/liferay/portal/workflow/kaleo/designer/web/internal/upgrade/v1_0_1/KaleoDefinitionVersionUpgradeProcess.java#L136-L142). It will likely be an issue for customers running this update. So, maybe you can use a double instead. What do you think? Is it a feasible solution?

Thanks

**Comment by achaparro** [comment]
Hey @rafaprax,

You are suggesting to use Double instead of Integer because we can have versions in a floating point format. However, the purpose of this ticket is to unify the types between _KaleoDefinition_ and _KaleoDefinitionVersion_ since the version type for _KaleoDefinition_ is Integer. So, can we have version in floating point format for _KaleoDefinitionVersion_ and as Integer for _KaleoDefinition_? What the expected behavior right now?

Thanks.

**Comment by achaparro** [comment]
cc/ @jesseyeh-liferay

**Comment by rafaprax** [comment]
HI @achaparro, good questions. My only concern here is about the data that came from the old `KaleoDraftDefinition` table and with keeping our code compatible with that data. I've read about the purpose of this ticket and I totally agree with this. So, I was aware that my suggestion to use a double in `KaleoDefinitionVersion.version` will imply changing the `KaleoDefinition.version` to double as well(sorry for not being clear in the above suggestion).

Now our code only generates integer versions, [KaleoDefinitionLocalServiceImpl.java#L168-L170](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-kaleo-service/src/main/java/com/liferay/portal/workflow/kaleo/service/impl/KaleoDefinitionLocalServiceImpl.java#L168-L170) and [KaleoDefinitionLocalServiceImpl.java#L389-L391](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-kaleo-service/src/main/java/com/liferay/portal/workflow/kaleo/service/impl/KaleoDefinitionLocalServiceImpl.java#L389-L391)

So, taking in account these points, now, I have two possible solutions:

1. Use a double in `KaleoDefinitionVersion.version` and `KaleoDefinition.version`, this can be a waste of DB resources since we just store integers now

2. Use an integer as you proposed but before change the datatype, you need to convert the `KaleoDefinitionVersion.version` from floating point to integer. My first idea was just remove the "." from `KaleoDefinitionVersion.version` and multiply the `KaleoDefinition.version` by 10, when needed.

I'm ok with any option you choose and I'm open to new ideas. What do you think?

Thanks in advance

**Comment by rafaprax** [comment]
Hi @achaparro, 

We don't need to use floating point anymore and I prefer the options 2 as well. 

>_but this is only valid if we don't have two or more decimal digits, is that possible?_

Yest. It is possible. Thanks for catching this..

So, let's go with your suggestion since it covers the scenario that you mentioned.

> Another option is to get all the KaleoDefinitionVersion ordered by version ASC and replace the version by 1,2,3,etc... In this process we have to ensure (update if needed) that the version in KaleoDefinition points the same KaleoDefinitionVersion than before.

Thanks so much guys

/cc @jesseyeh-liferay

**Comment by achaparro** [comment]
We have a plan then @rafaprax !

@jesseyeh-liferay can you modify the upgrade process with the suggested changes?

Thanks!

**Pull request closed without merging**
