### PR TITLE
LPS-133373 Replace native select with clay select

### PR DESCRIPTION
**Pull request by ramonmsp**

### CODE REVIEW

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:workflow

**Comment by ramonmsp** [comment]
ci:test:workflow

**Comment by ramonmsp** [comment]
ci:stop

**Comment by ramonmsp** [comment]
ci:test:workflow

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by ramonmsp** [comment]
ci:test:relevant

**Review by jotascript — APPROVED** [review]

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:stop

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:workflow

**Comment by ramonmsp** [comment]
ci:forward

**Pull request closed without merging**
