### PR TITLE
LPS-121244 Fix transitions updating from previous and next steps

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
@rodrigocunhaa, can you please test this fix?

**Comment by inacionery** [comment]
Hey @albinojunior, 

Could you please add a test to cover this bug?

Thanks!

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
