### PR TITLE
LPS-193485

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
In order to remove old liferay-ui taglibs replace usages around portal.

Proposed solution
----
Removes files and usages, since this logic is never executed, because we are using management toolbar.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
I triggered the tests again because the report was not generated for analysis

**Comment by ealonso** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGMT!

The next step before forwarding these changes is ensure the failures are not related to these changes, a QA engineer will take a look.

Thanks!

**Comment by MarinhoFeliphe** [comment]
QA Team has reviewed the failures and they are not related to these changes,

Thanks for your contribution!

cc: @ealonso

**Pull request closed without merging**
