### PR TITLE
LPS-122596 Populate workflow attributes in the resource command

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:test:bundle

**Comment by rodrigocunhaa** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
