### PR TITLE
LPS-150931 Web Content Translation Page does not display repeatable Fields in Workflow's Notification view

### PR DESCRIPTION
**Pull request by IstvanD**
Related Issue: https://issues.liferay.com/browse/LPS-150931

Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD, could you please send these changes to https://github.com/liferay-zulu/liferay-portal?

this repository is not the official anymore

Thank you!

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe 

Of course, sorry for the mistake.

Regards,
István

**Pull request closed without merging**
