### PR TITLE
LPS-129912 Delete unnecessary hook

### PR DESCRIPTION
**Pull request by ramonmsp**

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Comment by ramonmsp** [comment]
ci:forward

**Comment by rafaprax** [comment]
Hey @rodrigocunhaa ,

If this pr fails due to unrelated errors again, could you forward directly to BChan?

@ramonmsp

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/100854

**Pull request closed without merging**
