### PR TITLE
[TS] LPS-191809 Kaleo Designer's fetch util doesn't account for custom context

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
Setting a custom root context in Liferay can cause errors in Kaleo Designer because the fetch URLs for retrieving users and roles will have the context missing. 

Proposed Solution
========
Including the context in the fetch URLs.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-191809

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Failures are not related. Resent here: https://github.com/brianchandotcom/liferay-portal/pull/138488

**Pull request closed without merging**
