### PR TITLE
LPS-146668 Reorganized the structure of divs in the view_content.jsp file

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue [LPS-146668](https://issues.liferay.com/browse/LPS-146668)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:workflow

**Comment by vngoliveira** [comment]
ci:test:workflow

**Comment by vngoliveira** [comment]
ci:test:workflow

**Comment by vngoliveira** [comment]
ci:test:workflow

**Comment by vngoliveira** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
