### PR TITLE
LPS-121900 Migrate management toolbar v2 usages in portal-workflow modules

### PR DESCRIPTION
**Pull request by markocikos**
@liferay-workflow See details in https://issues.liferay.com/browse/LPS-121900

Test plan: Ensure management toolbar work correctly on
1. Global Menu > Applications > Workflow > Process Builder > Configuration 
1. Global Menu > Applications > Workflow > Submissions
1. **I could't find in UI management toolbar in `definition/view.jsp`**. From the code I would expect that it is the one on Process Builder > Workflows, but it does not react to changes in code. Maybe it's some weird caching issue on my side. As it has `selectable="<%= false %>"`, I have high confidence that the migration is as simple as for the other two.

after

@julien @ambrinchaudhary @jonmak08

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:workflow

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
I added in force-push the management toolbar migration from `portal-workflow/portal-workflow-task-web`, instead of opening new PR for https://issues.liferay.com/browse/LPS-121899. It's a small edition of code and very much related.

I also closed task for migration in [portal-workflow/portal-workflow-kaleo-designer-web](https://issues.liferay.com/browse/LPS-121929), that module seems do no longer exist.

So with this 3-in-1 task, we'll cover migration in `portal-workflow/*` modules.

This is the fourth usage, added in push:
1. Assign a workflow to Blogs on Global Menu > Applications > Workflow > Process Builder > Configuration
1. Add a Blog
1. User menu > My Workflow Tasks 

after

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:workflow

**Review by julien — APPROVED** [review]

**Comment by rafaprax** [comment]
Hey @rodrigocunhaa, Can you please take a look at this and forward if everything is ok?

Thx

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
