### PR TITLE
LPD-15835 Fix WorkflowMetricsAllItemsList#LongUserNameDisplaysEllipsis

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPD-18436](https://liferay.atlassian.net/browse/LPD-18436)

### CODE REVIEW

**Review by gabrielwas — APPROVED** [review]
LGTM

**Comment by gabrielwas** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test:workflow-metrics

**Comment by guilhermedcamacho** [comment]
Hey @larissacribeiro , did you have a chance to check the CI results?
I took a quick look and noticed that the test keeps failing. If you check [ci:test:workflow-metrics - larissacribeiro results](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2542130115&testrayRunId=2542134192), this test [failed](https://testray.liferay.com/home/-/testray/case_results/2542134674?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2542130115%26testrayRunId%3D2542134192%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc).

**Comment by guilhermedcamacho** [comment]
Were you able to successfully run this test locally? If so, maybe it's something related to CI.
Are you going to keep working on this or would you rather close this PR and put this ticket back in the queue?

**Comment by larissacribeiro** [comment]
Yes, @guilhermedcamacho, I took a look yesterday! When you run it locally without any changes, it is failing, which is why I sent an fix, and with it, it works locallly, but it appears it's not necessary. 
I was just waiting for another run I made of `ci:test:workflow-metrics` so I could confirm that the test has been already passing on testray. You can see it [here](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2542515192), the specif test is [passing](https://testray.liferay.com/home/-/testray/case_results/2542517185?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2542515192%26testrayRunId%3D2542517022%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse). 
I've also checked the last [workflow analysis](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2540444478), in which the [test](https://testray.liferay.com/home/-/testray/case_results/2540444597?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2540444478%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse) was already passing as well, and it has been for a while. All testray evidence points to the test working but I'm unsure about the fact that it's failing locally. What do you think?

**Comment by samuelromeiro** [comment]
Closing this PR as the test is not failing in master. 
Aligned with @gabrielwas.

**Pull request closed without merging**
