### PR TITLE
LPS-137163 Add padding inside a textarea in New process page

### PR DESCRIPTION
**Pull request by ramonmsp**

### CODE REVIEW

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:sf

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:forward

**Pull request closed without merging**
