### PR TITLE
[7.4 only] LPS-124401 Baseline

### PR DESCRIPTION
**Pull request by rafaprax**
Story https://issues.liferay.com/browse/LPS-121226

/cc @gabrielpramos @albinojunior @naraandrade

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
cu:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
ci:close

**Comment by albinojunior** [comment]
Resent here #169.

**Pull request closed without merging**
