### PR TITLE
LPS-143799 Remove Feature flag of Workflow Instance Tracker

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Review by naraandrade — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
