### PR TITLE
LPS-134493 Update Lucene dependency version

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:reports

**Review by rafaprax — APPROVED** [review]

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:reports

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
