### PR TITLE
LPS-189112 Deprecate Kaleo Forms

### PR DESCRIPTION
**Pull request by carolmariaabb**
Related Issue: https://liferay.atlassian.net/browse/LPS-189112

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]
@carolmariaabb the changes looks good to me!

the failures seem to be unrelated to these changes,

Thanks for your contribution!

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
I've trigger the tests again to make sure the test below is not a flacky one:

[MastersPageTemplates#EditMasterPageTemplateViaPageEditorLookAndFeel](https://testray.liferay.com/home/-/testray/case_results/2371007716/history?tab=result&hideFilterPin=true)

**Comment by MarinhoFeliphe** [comment]
it's flacky, [see](https://testray.liferay.com/home/-/testray/case_results/2372003365?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayComponentId%3D1561824843%26testrayBuildId%3D2371993858%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Comment by MarinhoFeliphe** [comment]
ci:forward:force

**Comment by carolmariaabb** [comment]
ci:forward:force

**Pull request closed without merging**
