### PR TITLE
LPS-142438 Make sidebar responsive

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-139387](https://issues.liferay.com/browse/LPS-139387)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by ramonmsp — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
