### PR TITLE
LPD-25930 Unify the routines Workflow and Workflow-metric

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-25930](https://liferay.atlassian.net/browse/LPD-25930)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow-metrics

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:test:workflow-metrics

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:test:random

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
