### PR TITLE
LPS-160959 The Notification Types selection box does not follow the horizontal size of the notification types field

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
LPS: [LPS-160959](https://issues.liferay.com/browse/LPS-160959)

I switched from the ClayDropDownWithItems component to the MultipleSelect component to meet the style needs requested in the ticket.

I took the opportunity to create a new constant to remove repetitive codes in the component and moved some constants around.

Final Result:
image

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:stop

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
ci:stop

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Waiting for the upstream build to be completed to run the command `ci:reevaluate:1257401_4450`

**Comment by naraandrade** [comment]
ci:reevaluate:1257401_4450

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
