### PR TITLE
LPS-142868

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-142768](https://issues.liferay.com/browse/LPS-142768)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by cgmonte** [comment]
Just started reviewing :)

**Comment by cgmonte** [comment]
Just started reviewing :)

**Review by cgmonte — APPROVED** [review]

**Comment by cgmonte** [comment]
ci:forward

**Pull request closed without merging**
