### PR TITLE
LPS-168745 Allow multiple recipients for notifications through XML

### PR DESCRIPTION
**Pull request by naraandrade**
Related issue: https://issues.liferay.com/browse/LPS-168745

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward

**Comment by naraandrade** [comment]
The failures on ci:test:workflow and ci:test:relevant don't seem related to the changes. I'm sending this PR directly to BChan.

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/131616.

**Pull request closed without merging**
