### PR TITLE
LPD-16334 Unauthorized access to workflow definition via API

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by pedro-oliveira446** [comment]
ci:report:2569921859

**Comment by pedro-oliveira446** [comment]
ci:report:2569935772

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/1153

**Pull request closed without merging**
