### PR TITLE
LPS-130976 Create endpoint to get the last process SLA result

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/342

**Pull request closed without merging**
