### PR TITLE
LPS-116986 Fix list apps back navigation

### PR DESCRIPTION
**Pull request by gabrielpramos**
cc @naraandrade @albinojunior

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:app-builder

**Comment by albinojunior** [comment]
Hey @gabrielpramos, 

`Execution failed for task ':apps:app-builder:app-builder-web:packageRunTest`, please fix the frontend tests and resend. 

Thanks!

**Comment by gabrielpramos** [comment]
thanks @albinojunior I've updated the snapshot

**Pull request closed without merging**
