### PR TITLE
LPD-21799 Cannot open order approval request notification

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-21799](https://liferay.atlassian.net/browse/LPD-21799)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:test:workflow-metrics

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Pull request closed without merging**
