### PR TITLE
LPS-133182 Inline

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:forward

**Comment by interaminense** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
already sent here https://github.com/brianchandotcom/liferay-portal/pull/102883

**Pull request closed without merging**
