### PR TITLE
LPD-30649 Extract Details, RevisionHistory,  and VersionRow to their own components, and also add typescript to all of them.

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-30649

Hey @rebsilva , this PR does not need functional or unit tests as I am not changing or introducing any features, I am just improving the readability of the code, and passing the existing Javasctipt code to Typescript, in case of a possible bug, the already existing tests for the Workflow restore function will catch him.

### CODE REVIEW

**Comment by rebsilva** [comment]
great! thanks for the heads up @danvb112 :blush:
just started reviewing! :cherry_blossom:

**Comment by danvb112** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom: great work on this @danvb112! :tada:

**Comment by danvb112** [comment]
ci:test:workflow

**Comment by danvb112** [comment]
ci:report:33486850

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
