### PR TITLE
LPS-107816 Unify the type of the column version in KaleoDefinition and KaleoDefinitionVersion

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
[LPS-107816](https://issues.liferay.com/browse/LPS-107816)

This is a follow-up to https://github.com/liferay-workflow/liferay-portal/pull/449 with additional commits to resolve previous CI test failures.

cc @achaparro @rafaprax

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by jesseyeh-liferay** [comment]
ci:test:upgrade

**Comment by jesseyeh-liferay** [comment]
ci:reevaluate:1277401_599

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hello @jesseyeh-liferay, I asked @anabuchmann to put some tests in quarantine, she opened [this pr](https://github.com/brianchandotcom/liferay-portal/pull/104959) and when this pr will merged by Brian I'll run ci:test:relevant again here.

Thank you and sorry for delay.

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:reevaluate:1277401_698

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:upgrade

**Comment by rafaprax** [comment]
ci:test:relevant
ci:test:relevant

**Comment by achaparro** [comment]
Hi @jesseyeh-liferay, @rafaprax, 

I think the errors in ProcessMetricResourceTest are related, can you verify that?

Thanks.

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/472

**Pull request closed without merging**
