### PR TITLE
LPS-143314 Add connection between Nodes

### PR DESCRIPTION
**Pull request by jotascript**
Story: [LPS-140056](https://issues.liferay.com/browse/LPS-140056)

### CODE REVIEW

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by jotascript** [comment]
ci:test:relevant

**Review by ramonmsp — APPROVED** [review]

**Review by naraandrade — CHANGES_REQUESTED** [review]
- Update some variable names to be more descriptive
- Change 'text' on edge data to 'label'
- Remove first 'if' on isOverlapping

**Comment by naraandrade** [comment]
ci:test:sf

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:stop

**Comment by jotascript** [comment]
ci:test:sf

**Pull request closed without merging**
