### PR TITLE
[TS] LPS-198185 JS errors and Calendar not responding

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
When adding a Calendar widget to a page and setting the "Display Scheduler Only" option in the Display Settings, clicking the "Add Event" button throws JavaScript errors and nothing happens.
This is because `simpleMenu` will be `null` [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/js/calendar_list.js#L280) and thus `defaultCalendar` won't be available [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/js/scheduler.js#L394).

Proposed Solution
========
Adding a null check for `simpleMenu` solves the issue.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
Hi @IstvanD sorry for the late reply,

your changes looks good to me!

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
