### PR TITLE
LPS-177901 Keep "depot" role type name

### PR DESCRIPTION
**Pull request by naraandrade**
Related issue: https://issues.liferay.com/browse/LPS-177901

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by alinedoleron — COMMENTED** [review]
The code looks good!! I have just one quention. The lang keys you've changed the term `id` to `name` already exist?

**Comment by naraandrade** [comment]
> The code looks good!! I have just one quention. The lang keys you've changed the term `id` to `name` already exist?

Thank you for noticing that! I forgot to update the language keys. I'll do it right now :)

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by patriciajeanperez** [comment]
Sent with test fixes in https://github.com/liferay-workflow/liferay-portal/pull/920

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
