### PR TITLE
LPS-123414 Fix action name detection when normalizing the xml definition

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
LGTM

**Review by rafaprax — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
