### PR TITLE
LPS-134977 Display ProcessVersionFilter on PerformanceByStepPage and manage filters result

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-130215](https://issues.liferay.com/browse/LPS-130215)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Review by ramonmsp — APPROVED** [review]

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
