### PR TITLE
LPS-132436 Migrate dynamic data structure selection modals

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey @liferay-workflow!

This is a part of [an ongoing epic](https://issues.liferay.com/browse/LPS-129246) to replace legacy AUI-based modals with Clay/React-based `openSelectionModal`. We have previously migrated DDM modals, in #407, but we were not aware of `openDDMPortlet` utilily. This PR is a 2nd part of the task that migrates `openDDMPortlet` related to `structure`, similar to what is being done with `template` in #454.

I have had to migrate `openWindow` to `openModal` in order to maintain the behaviour of opening modal on top of modal, instead of one inside the other.

# 🧪 Testing
1. Run `ant setup-profile-dxp` before `ant all` to gain access to Kaleo Forms Admin
2. Content & Data > Kaleo Forms Admin
3. Create a new Process
4. On the Fields step click on `Add Fields Step` & click on `Parent Field Set` under `Details`

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:kaleo-forms

**Comment by rafaprax** [comment]
@rodrigocunhaa and/or @anabuchmann, can you please check with these failures are related with these changes?

Thx

**Comment by rodrigocunhaa** [comment]
ci:test:bundle

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
@rafaprax , those tests needed to be fixed for this PR. I resent it here: https://github.com/liferay-workflow/liferay-portal/pull/390

**Comment by rafaprax** [comment]
Thanks Rod(@rodrigocunhaa)

**Pull request closed without merging**
