### PR TITLE
LPS-171298 Use of library with known vulnerability: qs-6.7.0 (portal-workflow)

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-171298](https://liferay.atlassian.net/browse/LPS-171298)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by davisaints** [comment]
No related failures!

**Comment by davisaints** [comment]
ci:forward:force

**Pull request closed without merging**
