### PR TITLE
LPS-167821 ant build-lib-versions

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @seltong, there are related errors here. Can you please sort the commits and move the "patches" to before the "Fake Gradle cache" one?

Thx

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Pull request closed without merging**
