### PR TITLE
LPS-133663 Enable sort by item subject

### PR DESCRIPTION
**Pull request by ramonmsp**
Story: [LPS-133663](https://issues.liferay.com/browse/LPS-130216)

### CODE REVIEW

**Comment by ramonmsp** [comment]
ci:test:sf

**Review by rafaprax — COMMENTED** [review]
Hey @ramonmsp, Are we creating tests for cases like this one(new sort options)?

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
