### PR TITLE
LPS 180052

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
====
In order to fix the related ticket, where you are redirected to the draft page, when you are searching and the page is in a pending status. We need to change the usage of AssetRenderer for WorkflowHandler.

[Link to the issue](https://issues.liferay.com/browse/LPS-180052)

Proposed Solution
====
Replace the usage of AssetRenderer.getURLViewInContext with WorkflowHandler.getURLViewInContext, it that way we can have different view in context urls for different use cases like for example for workflow and for search.

This change doesn't affect the current logic, since WorkflowHandler is calling AssetRenderer.getURLViewInContext if we don't have a custom implementation, so everything should still working in the same way.

In this pr we only change the behavior for content pages since we are handling the logic for Workflow and Search in the same method, and it is generating some issues.

Steps to reproduce
====

1. Add a new Paragraph to the Home page. For example with content "ASDF" --> Publish page
2. Search for "ASDF" in the search bar
3. Checkpoint: The search results contain this page
4. Enable workflow for ASDF2 content pages ( Workflow > Process Builder >Configuration )
5. Edit the page and Submit for publication (Do not do any changes)
6. Search for "ASDF"
7. You get one result: It is the older version of ASDF, click on it.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:workflow

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
@ealonso LGTM, thanks for your changes! I really appreciate!

**Comment by MarinhoFeliphe** [comment]
@ealonso, there is only one integration tests failing from Layout side and I believe it's related to these changes,
could you take a look at this failures? or maybe we can ask to the technical support to take a look at this, what do you think?

[Layout](https://testray.liferay.com/home/-/testray/case_results/2273628363?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2273626501%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by ealonso** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
