### PR TITLE
[7.4 Only] LPS-124515 Fix alignment of top calendar buttons

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielpramos** [comment]
this pr has been update to [pr-163](https://github.com/liferay-workflow/liferay-portal/pull/163)

**Pull request closed without merging**
