### PR TITLE
LPS-127552 Apply openFormViewModal to editFormView buttons on EditAppSidebar and WorkflowStep

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-125141](https://issues.liferay.com/browse/LPS-125141)

### CODE REVIEW

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
