### PR TITLE
LPS-124513 Apply bar-sm class to WorkflowInfoBar call

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Review by albinojunior — APPROVED** [review]
LGTM!

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by albinojunior** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
