### PR TITLE
LPS-120564 Add tests

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:stop

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Pull request closed without merging**
