### PR TITLE
LPS-205016 Add the date on the scheduler event as sr-only

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPS-205016](https://liferay.atlassian.net/browse/LPS-205016)
[LPP-52172](https://liferay.atlassian.net/browse/LPP-52172)

Hello, team!
I am adding a span tag with the event date as content to fix an accessibility issue.

### CODE REVIEW

**Review by cgmonte — CHANGES_REQUESTED** [review]
Hey @vngoliveira, this code is differentiating events and dates from another event are being added to the span elements. See bellow. Please, rework your solution, and let me know if you need any help! 

screenshot-1705071309

**Comment by vngoliveira** [comment]
ci:test:sf

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:forward

**Review by cgmonte — APPROVED** [review]

**Comment by vngoliveira** [comment]
Hi @cgmonte,
I saw that the failures are not related to my fix. Can I run the forward:force or send it manually to BChan?

**Comment by marcelabc** [comment]
Analyzing the CI results :+1:

**Comment by marcelabc** [comment]
ci:test:calendar

**Comment by marcelabc** [comment]
I analyzed the results from `ci:test:calendar` and the failures are not related :+1:

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
ci:forward:force

**Pull request closed without merging**
