### PR TITLE
LPS-189313

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by Luizcarlosqueiroz** [comment]
ci:test:workflow-metrics

**Comment by patriciajeanperez** [comment]
Hey @MarinhoFeliphe, these errors display when the Single Approver is not available in Workflow Metrics

`java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-41848-workflow-metrics-nodes/Shm9elEZR467GHvzDi1_4w] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-41848-workflow-metrics-nodes]]]
java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException`

`2023-09-15 20:00:09.834 ERROR [liferay/background_task-8][BackgroundTaskMessageListener:162] Unable to execute background task
java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-34047-workflow-metrics-nodes] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-34047-workflow-metrics-nodes]]]`

Here is the full [liferay log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-28/test-portal-acceptance-pullrequest(master)/7642/functional-tomcat90-mysql57-jdk8/0/13/liferay-log.txt.gz?authuser=0). Let me know if you need help reproducing any of these errors. Thanks!

**Comment by MarinhoFeliphe** [comment]
Hello @patriciajeanperez, thanks for analysis!

I've changed the approach the Workflow Metrics uses to create and reindex indices on Virtual Instances (Companies) creation,

the problem is that functional tests are executed faster than indices creation because indices are created asynchronously,

unit and integration tests are executed too fast as well, but there we are using an approach to avoid `no such index exceptions`,

I'm in contact with @Luizcarlosqueiroz and we're trying apply some approach to adapt functional tests for this situation.

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/992

cc: @Luizcarlosqueiroz @patriciajeanperez

**Pull request closed without merging**
