### PR TITLE
LPS-177901 Keep "depot" role type name

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Related issue: https://issues.liferay.com/browse/LPS-177901

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hi @naraandrade! I sent in the test fixes and re-run them. Some of them are still failing due to a missing error message when attempting to add a duplicate node name. There used to be `A node with that ID already exists. Enter a unique ID.` It will still not save but no error message displays. Can you take a look please? Thank you!

**Comment by naraandrade** [comment]
> Hi @naraandrade! I sent in the test fixes and re-run them. Some of them are still failing due to a missing error message when attempting to add a duplicate node name. There used to be `A node with that ID already exists. Enter a unique ID.` It will still not save but no error message displays. Can you take a look please? Thank you!

Oh, it should display `A node with that name already exists. Enter a unique name.`. I will take a look to see why it's not working. Thanks, Patricia!

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/923.

**Pull request closed without merging**
