### PR TITLE
LRQA-59713 Remove test from quarantine

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
cc @rodrigocunhaa @albinojunior

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Comment by gabrielpramos** [comment]
ci:test:sf

**Review by albinojunior — CHANGES_REQUESTED** [review]
Hey @gabrielpramos, could you please remove the quarantine flag from the fixed tests?

[UpdateDueDate](https://github.com/gabrielpramos/liferay-portal/blob/LRQA-59713/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoformsUsecase.testcase#L3991) and [ViewProcessWithComments](https://github.com/gabrielpramos/liferay-portal/blob/LRQA-59713/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoformsUsecase.testcase#L4735)

**Comment by gabrielpramos** [comment]
Sure, I might have returned it back by mistake

**Comment by gabrielpramos** [comment]
ci:stop

**Pull request closed without merging**
