### PR TITLE
LPS-146610

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-139392](https://issues.liferay.com/browse/LPS-139392)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/113076

**Pull request closed without merging**
