### PR TITLE
LPD-18445 Use chooseSortOption macro to select descending option

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-18445

### CODE REVIEW

**Review by gabrielwas — APPROVED** [review]
LGTM! Thx

**Comment by gabrielwas** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:workflow

**Comment by danvb112** [comment]
ci failures are not related!

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
