### PR TITLE
LPS-193988 Update parseReassignments according with the new nesting structure

### PR DESCRIPTION
**Pull request by naraandrade**
Related ticket: https://liferay.atlassian.net/browse/LPS-193988

### CODE REVIEW

**Comment by naraandrade** [comment]
Failures are not related. I'll be forwarding the PR now.

**Comment by naraandrade** [comment]
ci:forward:force

**Comment by naraandrade** [comment]
ci:forward:force

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Pull request closed without merging**
