### PR TITLE
LPS-131471 Fix remaining time when the SLA is less than a minute

### PR DESCRIPTION
**Pull request by jotascript**
Issue: [LPS-131471](https://issues.liferay.com/browse/LPS-131471)

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @jotascript, Do we have tests that cover this scenario?

Thx

**Review by ramonmsp — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by jotascript** [comment]
@rafaprax added test to cover when SLA is less than a minute.

**Comment by rafaprax** [comment]
Thank you @jotascript

**Comment by rafaprax** [comment]
ci:forward

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
