### PR TITLE
LPS-138141

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Workflow Team,

This is a follow-up pull request to https://github.com/liferay/alloy-ui/pull/173. Let me know if I should send this to the frontend team instead.

https://issues.liferay.com/browse/LPS-138141

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
When I first sent this pull request, it included a commit which is no longer necessary due to the same commit being made at https://github.com/brianchandotcom/liferay-portal/pull/107492. As such, I have rebased my branch to the latest master and force-pushed it. This caused the commit to be removed from the pull request.

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
Thx @mbowerman

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
