### PR TITLE
LPS-134179 Update the condition to set the slaResult on the script to update sla's of the instance

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:workflow-metrics

**Comment by seltong** [comment]
ci:test:workflow-metrics

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by seltong** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hi @anabuchmann,

if this ci's run doesn't pass, please forward it manually to BChan.

Thank you

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/105724

**Pull request closed without merging**
