### PR TITLE
[TS] LPS-194619 LPS-190884

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-workflow team!

This PR fixes 2 issues caused by [LPS-18625](https://liferay.atlassian.net/browse/LPS-186252):
- [LPS-190884](https://liferay.atlassian.net/browse/LPS-190884): The unit test `testUseJavaScriptingKaleoTaskAssignmentSelector` invokes a method (`multiLanguageKaleoTaskAssignmentSelector.getKaleoTaskAssignments`) that requires a configuration but this will timeout after 15 minutes. To fix it, we should mock the configuration itself. We also mock the value of the configuration to return the default value of 0, i.e., no cache.
- [LPS-194619](https://liferay.atlassian.net/browse/LPS-194619): The key used for the `KaleoTaskScriptedAssignmentCache` was the same for different workflow instances of the same workflow definition. To fix it we make a compound key from the `kaleoInstanceTokenId`, which specifies the workflow instance, and the `currentKaleoNodeId` that specifies the node (task in our case). This key is unique for a given task node and a given workflow instance. (See reproducing steps in LPS for more details.)

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by ricardocousolr** [comment]
Hi @MarinhoFeliphe,

Please let me know if you need further clarification about the PR. 

Thanks!

**Comment by MarinhoFeliphe** [comment]
Hi @ricardocousolr,

Sorry for the late reply, I'm gonna start the review tomorrow 

Thank you!

**Comment by MarinhoFeliphe** [comment]
Taking a look

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/984

I only changed the scope of the cache to kaleoTaskInstanceToken because it found a situation that is possible to reproduce the same issue,

the same kaleoInstanceToken can pass for the same node two or more times, if there is a script that has some logic to provide the task assignments based on the information of the asset entry it can retrieve wrong task assignments,

Thanks for your contribution!

cc: @ricardocousolr

**Comment by ricardocousolr** [comment]
Thanks, @MarinhoFeliphe!

**Pull request closed without merging**
