### PR TITLE
[TS] LPS-129410

### PR DESCRIPTION
**Pull request by jonathanmccann**
The source formatting commit of LPS-20825 made it so that the same description string is used in both the DESCRIPTION and X-ALT-DESC properties - https://github.com/brianchandotcom/liferay-portal/pull/83640/commits/e5e3954fa429164117d9df6f2f9653e28872bd83

The X-ALT-DESC property is allowed to contain HTML so this fix partially reverts LPS-20825 to allow this.

Please let me know if there are any questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Hey @jonathanmccann, related SF error here. Could you please fix and resend?

Thx

**Comment by rafaprax** [comment]
ci:stop

**Pull request closed without merging**
