### PR TITLE
LPS-169224 Allow administrators to publish and edit workflow definition by default on LXC enviroment

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Comment by pedro-michel** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/127395

**Pull request closed without merging**
