### PR TITLE
LPS-142442 Create tests

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-139387](https://issues.liferay.com/browse/LPS-139387)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by jotascript** [comment]
Just started reviewing :)

**Review by jotascript — APPROVED** [review]

**Comment by jotascript** [comment]
ci:forward

**Pull request closed without merging**
