### PR TITLE
LPD-17953 Adding order to running tests

### PR DESCRIPTION
**Pull request by thallescezar**
Related issue: https://liferay.atlassian.net/browse/LPD-17953

### CODE REVIEW

**Comment by thallescezar** [comment]
ci:test:kaleo-forms

**Review by guilhermedcamacho — APPROVED** [review]
LGTM! :tada

**Comment by guilhermedcamacho** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
The KaleoDefinitionVersionLocalServiceTest test continues to pass as reported [here](https://testray.liferay.com/home/-/testray/case_results/2545416375?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3Dcom.liferay.portal.workflow.kaleo.service.test.KaleoDefinitionVersionLocalServiceTest%26testrayBuildId%3D2545416020%26testrayRunId%3D2545416056%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc).

**Pull request closed without merging**
