### PR TITLE
LPS-196932

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by Luizcarlosqueiroz** [comment]
ci:test:startup

**Comment by Kvale1733** [comment]
Hey team. Can we also check that this fixes https://liferay.atlassian.net/browse/LPS-197240.
The affected test is

 Clustering#CanCreateVirtualInstanceWithClustering. 

You can run the test once the build is done on the bundle (with ant -f build-test-tomcat.xml run-selenium-tomcat) since that reproduced consistently for me). Or you can run the clustering suite if you'd like. But it's just one test. 

I already checked on bundle generated above but I see there are more changes.

The test is facing another issue that fixed by https://github.com/brianchandotcom/liferay-portal/pull/141341. So if that's not in upstream yet you would want to apply that locally so you don't run into that issue and get accurate results. This might also pop up on CI if it's not in upstream yet.

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:startup

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:startup

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:startup

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:test:startup

**Pull request closed without merging**
