### PR TITLE
LPS-175354

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/72

Hello,

Please let me know if this there should be any changes to this.
Thank you !

> [LPS-175354](https://issues.liferay.com/browse/LPS-175354) Modified InvalidContentMessage to display when a non-XML file is selected for import, and allowed for special characters to be encoded before decoding is attempted.

### CODE REVIEW

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Hi @fortunatomaldonado, I could not test the issue with the xml file mentioned on the ticket because I'm not authorized to download it. However, I tested other xml definitions to see if they still work after your changes and apparently everything is fine. I'm running the test suites again just to make sure this doesn't introduce a regression, but I'll approve this for now. Let's wait for the tests results :) Thanks for your contribution!

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
@fortunatomaldonado I checked the tests failures and they're not related to your changes. You can send this PR directly to BChan. Thanks you!

**Comment by SelenaAungst** [comment]
@naraandrade Thank you! 
sent https://github.com/brianchandotcom/liferay-portal/pull/131031

**Comment by SelenaAungst** [comment]
ci:close

**Pull request closed without merging**
