### PR TITLE
LPS-201214 Replace AUI() usages in portal-workflow-kaleo-forms-web

### PR DESCRIPTION
**Pull request by Tim-Cao**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-201214)

Steps
Case 1: Export Kaleo Form

Go to Content & Data > Kaleo Forms Admin
Create a Kaleo Form
In the processes view > Click on ellipsis > Export
See the modal
Screenshot 2023-11-10 at 14 29 50
Case 2: Change Kaleo Form fields

With the Kaleo From created
In the processes view > Click on ellipsis > edit
Go to Fields tab > click on "view fields" of any of the fields row > see preview modal shows
Click on any field ellipsis > Choose > see "Selected Field Set" changes
 Screen.Recording.2023-11-10.at.14.36.43.mov 
Case 3: Change Kaleo assigned form

With the Kaleo From created
In the processes view > Click on ellipsis > edit
Go to Forms tab > Click on the form ellipsis > Unassign form > See that in the Form row, the form dissapears
Click on the form ellipsis > Edit Form > see modal appears
https://github.com/liferay-echo/liferay-portal/assets/91208451/b10d92c1-f512-4705-964f-6dbf4b3b9149
Case 4: Change Kaleo workflow

With the Kaleo From created
In the processes view > Click on ellipsis > edit
Go to Workflow tab > Add a workflow
Click on the workflow ellipsis > Edit > see modal appears
Click on the workflow ellipsis > Choose > see "Selected Workflow: " changes
 Screen.Recording.2023-11-10.at.14.44.43.mov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
@DiegoHu97
cc @seltong

**Comment by Tim-Cao** [comment]
ci:test:kaleo-forms

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97, there is a regression issue found, A Preview popup overlay the Forms modal when the window size is changed during edit assigned form. Would you mind having a look at?
https://github.com/liferay-workflow/liferay-portal/assets/52661397/938eb1d6-bafd-4324-81e7-b50be472560a
Without your changes, the Preview popup is under the Forms modal.
image

**Comment by DiegoHu97** [comment]
Hey @Tim-Cao I fixed the regression, thanks for your work!

**Comment by DiegoHu97** [comment]
ci:test:kaleo-forms

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by seltong** [comment]
ci:stop

**Comment by seltong** [comment]
Hi @DiegoHu97, thanks for fix the regression. Could you push your changes before ran the ci please?

**Comment by DiegoHu97** [comment]
Hi @seltong My bad, I thought I was on another branch, I will send the new pr

**Comment by DiegoHu97** [comment]
See https://github.com/liferay-workflow/liferay-portal/pull/1037
CC: @seltong @Tim-Cao

**Comment by DiegoHu97** [comment]
@seltong Could you close this pr please? thanks!

**Comment by seltong** [comment]
Thank you @DiegoHu97!

**Pull request closed without merging**
