### PR TITLE
[TS] LPS-152750

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/liferay-workflow/liferay-portal/pull/801 with merge conflicts resolved.

CC @rafaprax, @naraandrade, @MarinhoFeliphe

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:help

**Comment by MarinhoFeliphe** [comment]
ci:test:reports

**Comment by MarinhoFeliphe** [comment]
Hi @ChrisKian,

thank you for rebase,

I'm not sure if some failed tests like [this](https://testray.liferay.com/home/-/testray/case_results/1970906513?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1970875528%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) are not related,

I'm ran the reports suit to make sure portal-report project is fine,

but I believe we could split this fix in two parts, one for reports and another for commerce and send a pull request to commerce team.

what do you think?

Thank you,
Feliphe

**Comment by ChrisKian** [comment]
Hi @MarinhoFeliphe,

@rafaprax will be a better resource to ask; I merely rebased and regenerated the ant build-lib-versions files.

**Comment by ChrisKian** [comment]
Hey @MarinhoFeliphe,

The only failing tests which would be related would be in the `commerce-report-impl` and `portal-reports-engine-console-jasper` modules, since those are the only places where the patched jar is used.

As for splitting up the PR, I can do that if you'd like, just let me know.  Thanks!

**Pull request closed without merging**
