### PR TITLE
LPS-122601 workflowContext should be a unmodifiable

### PR DESCRIPTION
**Pull request by sammonsjl**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Hey @sammonsjl and @mcgitty, 

We have some scenarios that require that the workflowContext must be modifiable(One of them came to us recently http://issues.liferay.com/browse/LPS-119232). Therefore, we will not forward this pr, but we will update our documents to warn users that the workflowContext is modifiable and not thread-safe, and if they need something thread-safe, they should implement this on their own.

Thanks for reporting this

/cc @rbohl

**Comment by rbohl** [comment]
Created https://issues.liferay.com/browse/LRDOCS-8594

**Pull request closed without merging**
