### PR TITLE
[7.4 only] LPS-124585, LPS-124401, LPS-124353, LPS-124354

### PR DESCRIPTION
**Pull request by albinojunior**
Story https://issues.liferay.com/browse/LPS-121226

/cc @gabrielpramos @rafaprax

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/164

**Pull request closed without merging**
