### PR TITLE
Update httpclient and httpcore dependencies versions

### PR DESCRIPTION
**Pull request by MariMalta**

### CODE REVIEW

**Comment by MariMalta** [comment]
ci:test:sf

**Comment by MariMalta** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
Hey @MariMalta you forgot the LPS-XXXX in the commit msg. Please fix it. Thx

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @MariMalta you forgot the LPS-XXXX in the commit msg. Please fix it. Thx

**Comment by MariMalta** [comment]
ci:test:sf

**Review by rafaprax — APPROVED** [review]

**Comment by MariMalta** [comment]
ci:test:reports

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
