### PR TITLE
LPS-134603 Synchronize instance document when multiples updates are running

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Comment by rafaprax** [comment]
Hey @rodrigocunhaa and @anabuchmann, Can you check if those failures above are related to this fix?

Thx

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
