### PR TITLE
[TS] LPS-143504 In Web Content workflow, Reviewers are not allowed to see Editors' comments after submitting for approval the first version

### PR DESCRIPTION
**Pull request by joseluisbango**
Hello @liferay-workflow team,

See [LPS-143504](https://issues.liferay.com/browse/LPS-143504).

The implemented solution is similar to [LPS-125088](https://issues.liferay.com/browse/LPS-125088), but for "instance" instead of "task". 

[This comment](https://issues.liferay.com/browse/LPS-68599?focusedCommentId=887687&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-887687) might be useful to understand the limitation regarding the Asset Framework.

Please let me know if there is anything wrong with this approach or you have any questions.

Thanks!

/cc @ChrisKian (to let you know, as it is a regression caused by LPS-125088)

### CODE REVIEW

**Comment by joseluisbango** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
Hello @joseluisbango, I'm taking a loking at this.

Thank you!

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
@joseluisbango, it's all right for me, I approved this pull request.

Thank you!

**Comment by joseluisbango** [comment]
Thank you for your review @MarinhoFeliphe. If it is ok, could you move it forward?

Thanks!

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
