### PR TITLE
LPD-34658 Remove Feature Flag for LPD-29635

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-34658

### CODE REVIEW

**Comment by rebsilva** [comment]
@danvb112 it seems you forgot to remove 'featureFlagsTest' from the code so the sf is failing, could you please take a look?

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
> @danvb112 it seems you forgot to remove 'featureFlagsTest' from the code so the sf is failing, could you please take a look?

Done! Thanks @rebsilva!

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
Ci failures are not related!

**Comment by danvb112** [comment]
ci:forward

**Comment by danvb112** [comment]
CI Failures are not related!

**Comment by danvb112** [comment]
ci:forward:force

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
