### PR TITLE
LPD-32664 Escape user name

### PR DESCRIPTION
**Pull request by devpedrotavares**
Related ticket: [LPD-32664](https://liferay.atlassian.net/browse/LPD-32664)

[LPD-32664]: https://liferay.atlassian.net/browse/LPD-32664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
Hi @devpedrotavares, as we talked, we should add a test for this. I believe the fix is ok if you need to deliver an SDH.

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
ci:test:sf

**Comment by devpedrotavares** [comment]
Hi @linolaoj , I just added a commit with the test

**Review by linolaoj — APPROVED** [review]

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
