### PR TITLE
[CLDR] LPD-18592 Fix functional test AddCalendar#DefaultTimeZoneFollowsUserPreferences to work with CLDR locale provider

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:calendar

**Comment by guilhermedcamacho** [comment]
I don't know why the calendar suite is not running the Poshi tests like [here](https://github.com/liferay-workflow/liferay-portal/pull/1083#issuecomment-1961855696).
The [configuration](https://github.com/liferay/liferay-portal/blob/88cf28caf54d71b332b6fd1bc2bb07ed29b847a7/test.properties#L3853-L3858) of the suite is correct.
Do you guys have any clue? @MarinhoFeliphe @julschong

**Comment by guilhermedcamacho** [comment]
I opened this [thread](https://liferay.slack.com/archives/C19PWQ74J/p1709299664152789) on #ci channel, it seems to be a problem on CI side as I found another [thread](https://liferay.slack.com/archives/C19PWQ74J/p1709200156273509) from another team with the same problem.

**Comment by julschong** [comment]
@guilhermedcamacho not sure if this is the case. but I triggered calendar test on my repo PRs here: 
- Just added random commit: https://github.com/julschong/liferay-portal/pull/1165
- CLDR with this PR: https://github.com/julschong/liferay-portal/pull/1157
- JRE with this PR: https://github.com/julschong/liferay-portal/pull/1158
They all seem to ran all 56 jobs

maybe try to sync workflow repo's master and retrigger it?

**Comment by julschong** [comment]
@guilhermedcamacho resumitted here: https://github.com/liferay-workflow/liferay-portal/pull/1095
I retriggered the test suite

**Comment by julschong** [comment]
ci:close

**Comment by julschong** [comment]
ci:reopen

**Comment by julschong** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
Thanks @julschong, I just wanted to double check running this Poshi test in our suite, but I ended up running into a CI issue that they resolved late last Friday, as reported [here](https://liferay.slack.com/archives/C19PWQ74J/p1709333303706769).

**Pull request closed without merging**
