### PR TITLE
LPS-125489 buildLang

### PR DESCRIPTION
**Pull request by gabrielpramos**
story: [LPS-116593](https://issues.liferay.com/browse/LPS-116593)
cc: @naraandrade @albinojunior

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Review by albinojunior — APPROVED** [review]
ci:forward

**Comment by albinojunior** [comment]
@gabrielpramos can you take a look at this failures?

**Comment by gabrielpramos** [comment]
Sure, I'm already looking into it 😉

**Comment by gabrielpramos** [comment]
ci:forward

**Pull request closed without merging**
