### PR TITLE
LPD-31578 Reload after posting a comment on workflow tasks page so the action menu is updated correctly

### PR DESCRIPTION
**Pull request by rebsilva**
Related issue: https://liferay.atlassian.net/browse/LPD-31578

hello reviewer! :cherry_blossom:

could you please take a look if the BE code is correctly following the rules and conventions that we have?

also could you confirm that what i did on `DiscussionTag.java` is indeed necessary or not? i know for sure that the `DiscussionTaglibHelper.java` is needed but i'm not sure about the content on `DiscussionTag.java`.  

thanks a lot!

### CODE REVIEW

**Comment by rebsilva** [comment]
ps: this PR has a playwright test on going that i will be sending soon, this PR is just to confirm the BE code, thanks!

**Comment by linolaoj** [comment]
Hi @rebsilva, the changes on BE look fine. @cgmonte , @igor-franca do you think we need a playwright test for this?

**Comment by igor-franca** [comment]
> Hi @rebsilva, the changes on BE look fine. @cgmonte , @igor-franca do you think we need a playwright test for this?

Hey 😄, As we have a path between java, jsp and the react component. I believe that a functional test that ensures that this information is being passed correctly and arrives as expected in the React component will help us maintain this consistent behavior.

**Comment by rebsilva** [comment]
hi @igor-franca and @linolaoj! thanks a lot for your inputs and reviews :blush: actually i already did a playwright test for this, i'm just fixing the conflicts between the master; thanks a lot! :tulip:

**Review by linolaoj — APPROVED** [review]

**Comment by rebsilva** [comment]
i think some tests will break so i will run them so i can fix before sending to the infra-core team

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:workflow

**Comment by rebsilva** [comment]
ci:test:playwright

**Comment by rebsilva** [comment]
i'm waiting for the content-management review to forward the PR: https://github.com/liferay-content-management/liferay-portal/pull/5783

**Comment by marcelabc** [comment]
we can close this PR since you sent to the https://github.com/liferay-content-management/liferay-portal/pull/5783

**Pull request closed without merging**
