### PR TITLE
LPS 169343

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:calendar

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hi, 

Any update about this?

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
LGTM!! :tada:

**Comment by MarinhoFeliphe** [comment]
Thanks for your changes @robertoDiaz

feel free to forward it!

**Comment by naraandrade** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
Hi @robertoDiaz,

I found a case that I need to think more about,

I believe we shouldn't replace Calendar Booking's user to guest user in case that user were deleted.

We're just using the Calendar Booking's user to get their time zone, so we can only get the guest user's time zone.

I'm afraid of this case below:

- User1 have created an event
- User1 have deleted
- This upgrade was executed
- User1's event has no references of User1 because of all them were replaced to Guest user
-> Something works wrong because we're get the reference of the Guest user instead of a deleted user

 I believe we won't find the deleted user's time zone, so if we do nothing or replace to guest user's time zone, the chances to display the wrong event period is high.
 
We need more time to think a safe fix for that,

make sense to you?

**Comment by robertoDiaz** [comment]
Hi,

> I believe we won't find the deleted user's time zone, so if we do nothing or replace to guest user's time zone, the chances to display the wrong event period is high.
> ...
> > make sense to you?

First of all, the defaultCompanyUser is not guest, is a company administrator (see userLocalService.addCompanyUser method for more info)

The root cause here is that we have an inconsistency in the data (the event belongs to a deleted user and has references to this user).

To solve it, in my opinion, we only have 2 options:

1. remove the event and produce a data loss (this is too overkill)
2. use an arbitrary user to recalculate the start and end and change the removed user from this event, and this is exactly what we are doing here (see https://github.com/liferay-workflow/liferay-portal/pull/869/commits/94c9095eed94a8050702191a3921c512ec47b6b7#diff-e3760159377438f5c6a5cbe89da93dc29ad02a95bac89f1059bb2336f9dc111cR104-R105) 

From my perspective, **yes it is possible that the defaultCompanyUser timezone does not fit with the removed user timezone, but we do not have this information when running the upgrade.**

Saying this, in my opinion, in the scope of an upgrade, no, handling this use case does not make sense because the original information (the original user timezone) was removed with the user data, and at this point the best (and the only thing) we could do is use another arbitrary user, that is a pattern used in other similar cases in upgrades.

Regards

**Comment by MarinhoFeliphe** [comment]
Hi @robertoDiaz,

> he defaultCompanyUser is not guest ...

I confused, sorry,

> we could do is use another arbitrary user, that is a pattern used in other similar cases in upgrades.

Makes sense to me

I'll ask for QA team take a look at these failures just to make sure they are not related.

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
The QA team has reviewed and ensured failures are not related.

**Comment by MarinhoFeliphe** [comment]
@robertoDiaz, feel free to sent to Brian,

please when you open the pull request in Brian's repo, could you close this one and share the pull request here as well?

Thanks in advance

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
I'll send directly to Brian because the failures are not related

**Comment by MarinhoFeliphe** [comment]
@robertoDiaz,

I'm not sure if it's getting the default admin user in `_userLocalService.getDefaultUser(companyId);`,

[here](https://github.com/liferay/liferay-portal/blob/444df912b23d158a4902aa3999f69e6927a20a22/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L3010) we can see the fetch that is performed when `_userLocalService.getDefaultUser(companyId);` is called:

image

the default admin user is create [here](https://github.com/liferay/liferay-portal/blob/d076f63b4ae36b8cce79f0d4abcaddd46071d00b/portal-impl/src/com/liferay/portal/service/impl/CompanyLocalServiceImpl.java#L1993-L1999) that [under the hood](https://github.com/liferay/liferay-portal/blob/444df912b23d158a4902aa3999f69e6927a20a22/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L1136) is not a defaultUser.

If my assumptions are correct, I believe we can continue to get the Guest user's timezone because we don't have to know the timezone of the deleted user, but I believe it's not necessary update the userId and the userName of the calendarBooking.

let me know if I'm missing something.

Best Regards,
Feliphe

**Comment by robertoDiaz** [comment]
From my perspective change the user is safer because if in the future we try to use the event user it could drive to new NoSuchUser errors.

The root cause of the issue is this inconsistency (is see the  upgrade error as a symptom), and with this change we fix it.

Do you agree?

**Comment by naraandrade** [comment]
@MarinhoFeliphe could you take a look at this, please? Thanks :)

**Comment by MarinhoFeliphe** [comment]
@robertoDiaz, 

sorry for the late reply I was on PTO.

> From my perspective change the user is safer because if in the future we try to use the event user it could drive to new NoSuchUser errors.

We have two information, userId and userName, the userId seems to be useless once the user is deleted, but the userName could be used as the only useful reference of the deleted user, so if we don't need to change it to fix the bug we believe we should keep this data and just update the timezone.

Best regards,
Feliphe

**Comment by MarinhoFeliphe** [comment]
> The root cause of the issue is this inconsistency (is see the upgrade error as a symptom), and with this change we fix it.

I agree, but in this case we believe that we should keep this data.

Thank you for bring this discussion here, Calendar is a legacy component that needs to have a special attention, we're going to improve it through of a technology migration and I believe this data could be used for something similar to Jira when a user leaves the company.

image

**Comment by robertoDiaz** [comment]
Ok, 

I'll remove the user changes and resend.

Thanks!

**Comment by robertoDiaz** [comment]
See https://github.com/liferay-workflow/liferay-portal/pull/879

**Pull request closed without merging**
