### PR TITLE
LPS-136354 Create WorkflowInstanceTracker web module

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Story: [LPS-133990](https://issues.liferay.com/browse/LPS-133990)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
