### PR TITLE
LPS-201214 Replace AUI() usages in portal-workflow-kaleo-forms-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-201214)

## Steps

**Case 1: Export Kaleo Form**

- Go to Content & Data > Kaleo Forms Admin
- Create a Kaleo Form
- In the processes view > Click on ellipsis > Export 
- See the modal
Screenshot 2023-11-10 at 14 29 50

**Case 2: Change Kaleo Form fields**

- With the Kaleo From created 
- In the processes view > Click on ellipsis > edit
- Go to Fields tab > click on "view fields" of any of the fields row > see preview modal shows
- Click on any field ellipsis > Choose > see "Selected Field Set" changes

https://github.com/liferay-echo/liferay-portal/assets/91208451/6e8d6e72-8a68-4e3f-a219-e932e3ad9acc

**Case 3: Change Kaleo assigned form**

- With the Kaleo From created 
- In the processes view > Click on ellipsis > edit
- Go to Forms tab > Click on the form ellipsis > Unassign form > See that in the Form row, the form dissapears
- Click on the form ellipsis > Edit Form > see modal appears
https://github.com/liferay-echo/liferay-portal/assets/91208451/b10d92c1-f512-4705-964f-6dbf4b3b9149

**Case 4: Change Kaleo workflow**

- With the Kaleo From created 
- In the processes view > Click on ellipsis > edit
- Go to Workflow tab > Add a workflow
- Click on the workflow ellipsis > Edit > see modal appears
- Click on the workflow ellipsis > Choose > see "Selected Workflow: " changes

https://github.com/liferay-echo/liferay-portal/assets/91208451/940985e8-5e48-4794-bf37-78ba372b2252

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:kaleo-forms

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by seltong** [comment]
Hi @DiegoHu97, could you please take a look in the CI failures? This [failure](https://testray.liferay.com/home/-/testray/case_results/2473967503?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2473967264%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) seems related to your changes.

**Comment by DiegoHu97** [comment]
@Tim-Cao could you take a look? I'm not able to run the functional tests, thanks!

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97, similar issue with https://github.com/liferay-workflow/liferay-portal/pull/1035#issuecomment-1852796010
But happened on add workflow

1. Navigate to the Kaleo Forms Admin
2. Add a new process
3. Fill name then next
4. Choose a field set then next
5. Add workflow
6. Change the window size

image

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:kaleo-forms

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by DiegoHu97** [comment]
@Tim-Cao Thanks for your work 😄 ! Let's see if this time passes

**Comment by Tim-Cao** [comment]
Nice @DiegoHu97, no failures related to your changes at the moment. cc @seltong

**Comment by seltong** [comment]
Thanks for your nice work guys! 😄

The [LocalFile.CPKaleoformsadmin#ViewUnpublishedWorkflowDefinitionsMenulist](https://testray.liferay.com/home/-/testray/case_results/2473967503?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2473967264%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) failed in `ci:test:kaleo-forms`, but I ran the test locally and it passed.

Hey @igor-franca, could you take a look at these changes please?

**Comment by cgmonte** [comment]
> Thanks for your nice work guys! 😄
> 
> The [LocalFile.CPKaleoformsadmin#ViewUnpublishedWorkflowDefinitionsMenulist](https://testray.liferay.com/home/-/testray/case_results/2473967503?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2473967264%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) failed in `ci:test:kaleo-forms`, but I ran the test locally and it passed.
> 
> Hey @igor-franca, could you take a look at these changes please?

Just tested locally and it runs successfully with the changes in this PR applied.

**Comment by cgmonte** [comment]
> Nice @DiegoHu97, no failures related to your changes at the moment. cc @seltong

Yeah, just checked and they are not related.

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:forward:force

**Pull request closed without merging**
