### PR TITLE
LPS-162888 Change the method getProcessInstance to work more like the method _getInstances

### PR DESCRIPTION
**Pull request by kiwm**
Related issue: https://issues.liferay.com/browse/LPS-162888

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by kiwm** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hello @kiwm 

I'm going to review your changes as soon as I can,

sorry for delay!

**Comment by kiwm** [comment]
I tested locally and the tests passed I should run the relevant again?

**Comment by carolmariaabb** [comment]
Hi @kiwm,
I executed the tests with your branch and they didn't pass. Could you please double check? Thanks!

**Steps to reproduce**:
- Run `ant setup-profile-dxp`
- Run `ant all`
- Start the portal
- Go to `liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-rest-test`
- run `gw testIntegration --tests com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.InstanceResourceTest`

**Result**:
image

**Comment by carolmariaabb** [comment]
@kiwm I will close this PR based on the previous message. Feel free to reopen or even open a new one with the test fix so we can review your changes. Thanks!

**Comment by carolmariaabb** [comment]
@kiwm Feel free to contact us if you need any assistance with this issue.

**Pull request closed without merging**
