### PR TITLE
LPS-107816 Make it private

### PR DESCRIPTION
**Pull request by rafaprax**
https://issues.liferay.com/browse/LPS-107816

This is a follow-up to https://github.com/liferay-workflow/liferay-portal/pull/458 with additional commits that deprecated methods that has the version param as String.

cc @achaparro @jesseyeh-liferay

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
just copying the latest message

> Hi @jesseyeh-liferay, @rafaprax,
> 
> I think the errors in ProcessMetricResourceTest are related, can you verify that?
> 
> Thanks.

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/656

**Pull request closed without merging**
