### PR TITLE
[TECHNICAL SUPPORT] LPS-190808 Image in Workflow Preview overflows

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-190808](https://liferay.atlassian.net/browse/LPS-190808),

The image overflowed in preview and I contained it with a max-width attribute. Please review my changes

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Hi @NemethNorbert, I'm having some trouble to reproduce the issue following the steps in the ticket. 
First, I think you forgot to add the json file for the structure, but I created one with a text field and an image field (let me know if I should've created it differently). I followed all the other steps, but when I click in the web content preview in the notification detail, a new tab is opened but nothing is displayed (see the attached screenshot). Am I missing any step?

**Comment by NemethNorbert** [comment]
> Hi @NemethNorbert, I'm having some trouble to reproduce the issue following the steps in the ticket. First, I think you forgot to add the json file for the structure, but I created one with a text field and an image field (let me know if I should've created it differently). I followed all the other steps, but when I click in the web content preview in the notification detail, a new tab is opened but nothing is displayed (see the attached screenshot). Am I missing any step? 

Hey @naraandrade ,
I think once you attach a fresh database to the Liferay instance, you will be able to view the workflow preview, I also run into this issue while I was working on it.
I also uploaded the structure to the ticket.

Thanks,

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]
@NemethNorbert  LGTM! I'm resending these changes in this [PR](https://github.com/liferay-workflow/liferay-portal/pull/966) to sort the file and make it easier to maintain in the future. Thanks for your contribution!

**Comment by naraandrade** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/966

**Pull request closed without merging**
