### PR TITLE
LPD-16334 buildService

### PR DESCRIPTION
**Pull request by seltong**
Related issue: [LPD-16334](https://liferay.atlassian.net/browse/LPD-16334)

This PR has an issue in the `KaleoDefinitionServiceImplTest.testGetScopeKaleoDefinitions()`, but I senr it in case I cannot fing the fix before I lose my access.

Error message:
```
Someone may be trying to circumvent the permission checker: {companyId=81339935609763, name=com.liferay.portal.workflow.kaleo.model.KaleoDefinitionVersion, primKey=32451, scope=4}
```

**Fix:**

Carol helped me on this investigation and we discovered that the fix is just add the `_serviceContext.setCompanyId(_company.getCompanyId());` in the setUp method of `KaleoDefinitionServiceImplTest`.

It was happening because we were checking the KaleoDefinition premission from other company in the test.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Hey @marcelabc I'm gonna review this today,

Thank you!

**Comment by MarinhoFeliphe** [comment]
Taking a look

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
This feature needs to be finished by implementing resource permissions for Kaleo Definition entity (`resource-actions/default.xml`), this way we will be able to perform the proper permissions check:

1 - check if the user is omni admin
2 - or check if the user is an instance admin and the configuration is enabled
3 - and finally the last check that needs to be implemented is the one related to the resource permission.

image

**Comment by samuelromeiro** [comment]
Resent https://github.com/liferay-workflow/liferay-portal/pull/1123

**Pull request closed without merging**
