### PR TITLE
LPS-161977 Add validation and build error for assignments

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
LPS: [LPS-161977](https://issues.liferay.com/browse/LPS-161977) and [LPS-161978](https://issues.liferay.com/browse/LPS-161978)
I added an assignment check for when something changes in the xml.
I also added notifications for errors.
When adding the notifications that i created, I took the opportunity to change the workflow notifications logic to make the code cleaner and more manageable.
Example:
image

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
I identified a problem and I will check it, when I solve it, I'll open another one PR.

**Comment by michaelmdelcavalcanti** [comment]
Problem resolved.

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
