### PR TITLE
LPS-145128

### PR DESCRIPTION
**Pull request by eliasantosf**
Ticket: [LPS-145128](https://issues.liferay.com/browse/LPS-145128)

### CODE REVIEW

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:stop

**Comment by eliasantosf** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
