### PR TITLE
LPS-120451 Update functional tests

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
@rodrigocunhaa @gabrielpramos Could you please take a look at this PR? Thank you :)

**Comment by rodrigocunhaa** [comment]
It looks good to me @naraandrade

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent at https://github.com/liferay-workflow/liferay-portal/pull/69

**Pull request closed without merging**
