### PR TITLE
LPS-128624 Apply delay to dismiss popover after unhovering the icon

### PR DESCRIPTION
**Pull request by naraandrade**
cc: @kevenleone

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:stop

**Comment by rafaprax** [comment]
waiting for liferay-app-builder#243 be merged

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
