### PR TITLE
LPS-137751 Create Join Node

### PR DESCRIPTION
**Pull request by ramonmsp**
Story: [LPS-135890](https://issues.liferay.com/browse/LPS-135890)

### CODE REVIEW

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:stop

**Comment by ramonmsp** [comment]
ci:stop

**Review by naraandrade — CHANGES_REQUESTED** [review]
Changes requested on test

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Review by rafaprax — APPROVED** [review]

**Pull request closed without merging**
