### PR TITLE
LPS-124889 Check if the change has been applied previously

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by jpince** [comment]
@rafaprax upgrade errors
```
LIFERAY_ERROR: Unknown column 'this_.mvccVersion' in 'field list'
LIFERAY_ERROR: Caught unexpected exception
LIFERAY_ERROR: Caught unexpected exception
LIFERAY_ERROR: Error reindexing all com.liferay.portal.workflow.kaleo.model.KaleoInstanceToken for company: 20099
```

**Comment by rafaprax** [comment]
@jpince I'll take a look at this.

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/181

**Pull request closed without merging**
