### PR TITLE
LPD-22890

### PR DESCRIPTION
**Pull request by rijema**
Following PR: https://github.com/liferay-workflow/liferay-portal/pull/1171

Related to this ticket: https://liferay.atlassian.net/browse/LPD-22890

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
Hi @MarinhoFeliphe , let me know if you want me to short the quantity of commits.

**Comment by marcelabc** [comment]
Hey @MarinhoFeliphe @rijema 
It has been a week since this PR was in the queue for review. Can you guys review it, please?

**Comment by MarinhoFeliphe** [comment]
Hi @rijema @marcelabc,

Thanks for your patience, my review is late because I'm focusing on the root model story, as soon as I finish a specific task of this story I'll take a look at these changes.

Thank you!

**Comment by rijema** [comment]
Thanks for the update, Feliphe!! 
image

**Comment by rijema** [comment]
HI @MarinhoFeliphe , please don't forget me :<

**Pull request closed without merging**
