### PR TITLE
LPS-130021 Serialize definition info and display xml content on editor

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-129928](https://issues.liferay.com/browse/LPS-129928)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by jotascript** [comment]
Just started reviewing :)

**Review by jotascript — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Resent here #672

**Pull request closed without merging**
