### PR TITLE
LPD-27977 Move the logic for fetching roles and account roles to the BaseRoleType Component, removing the useResource hook to use the fech API and rebuilding the loading indicator logic

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-27977

Hey @rebsilva, This PR doesn't need unit or functional tests as I'm just redoing the way we were doing the searches before, so all the tests we already have will be needed to cover this PR

### CODE REVIEW

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom:

there isn't a test here but i believe it's because this bug is only visual and it's hard to test something like this, am i right @danvb112? if it's the case, could you please justify on the PR description? thanks!

**Comment by danvb112** [comment]
ci:test:workflow

**Comment by danvb112** [comment]
CI Failures are not related!

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
