### PR TITLE
LPS-187768 Switch iText under AGPL (as dependency of JasperReport) for OpenPDF (an LGPL - licensed fork of iText)

### PR DESCRIPTION
**Pull request by seltong**
Related to: [LPS-187768](https://liferay.atlassian.net/browse/LPS-187768)

### CODE REVIEW

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by seltong** [comment]
ci:test:stable

**Comment by seltong** [comment]
ci:forward:force

**Comment by seltong** [comment]
ci:forward:force

**Pull request closed without merging**
