### PR TITLE
LPS-142243 Change fetch mock on tests

### PR DESCRIPTION
**Pull request by jotascript**
Issue: [LPS-142243](https://issues.liferay.com/browse/LPS-142243)

### CODE REVIEW

**Comment by jotascript** [comment]
ci:test:relevant

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @jotascript, related erros here. Please fix. Thx

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by jotascript** [comment]
ci:stop

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
