### PR TITLE
[7.4 only] LPS-124401 Rename

### PR DESCRIPTION
**Pull request by albinojunior**
Story https://issues.liferay.com/browse/LPS-121226

/cc @gabrielpramos @rafaprax @naraandrade

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:app-builder

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
