### PR TITLE
LPS-129909 Remove Panel component and test file

### PR DESCRIPTION
**Pull request by jotascript**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:forward

**Comment by rafaprax** [comment]
@jotascript Can please fix the conflict here?

> Conflicting files
modules/dxp/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/components/process-metrics/workload-by-step-card/WorkloadByStepCard.es.js

Thx

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
@jotascript sf issue here. :)

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Manually sent here: https://github.com/brianchandotcom/liferay-portal/pull/100949

**Pull request closed without merging**
