### PR TITLE
LPS-147236 Revert "LPS-127317 Remove unnecessary scroll and set min size for calendar modals"

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi @liferay-workflow ,
LPS: https://issues.liferay.com/browse/LPS-147236
**Issue**: Opening the modal from "Add event" in Calendar is not responsive anymore.
**Root cause**: a min-width is defined, it is a regression caused by https://issues.liferay.com/browse/LPS-127317 on 7.3.x.

The reason I removed the code, is because after reverting the fix of LPS-127317, the original problem is not reproducible anymore following its reproduction steps.

Could you please review it?
Thank you!

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @orsolyaDekany, I'll take a look at this.

Thanks!

**Comment by naraandrade** [comment]
Hi @orsolyaDekany, apparently something in the modal structure changed and, even with the revert of that commit, the [LPS-127317](https://issues.liferay.com/browse/LPS-127317) is not happening anymore, as you pointed out. So you can go ahead and revert it 👍🏻 Thank you

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
@orsolyaDekany As the issue occurs on 7.3.x, you will need to sent the pull request to the liferay user and await for they review. I'll close this one now.

**Comment by orsolyaDekany** [comment]
Hi @naraandrade , Should I send the PR only to 7.3.x liferay-user? The issue is on 7.3.x indeed, however, this code seems to be unused on Master, because the css styles are applied from the clay_admin.scss instead when opening the Modal in Calendar. Could you please check it? If it is unused, maybe we should remove it on Master, too. What do you think? Thank you :)

**Comment by naraandrade** [comment]
@orsolyaDekany Oh, I understand. In this case, you can send the PR to the Master indeed and after it's being merged you can do the backport to 7.3.x. I'll reopen the PR and forward it. Thank you :)

**Comment by naraandrade** [comment]
ci:forward

**Comment by orsolyaDekany** [comment]
Thank you @naraandrade !

**Pull request closed without merging**
