### PR TITLE
LPS-131628 Fix double request when filtering for Completed items

### PR DESCRIPTION
**Pull request by jotascript**
Bug: [LPS-131628](https://issues.liferay.com/browse/LPS-131628)

### CODE REVIEW

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Comment by rafaprax** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Review by ramonmsp — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
