### PR TITLE
LPS-144542 Create a task node with the main features

### PR DESCRIPTION
**Pull request by jotascript**
Story: [LPS-130000](https://issues.liferay.com/browse/LPS-130000)

### CODE REVIEW

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by naraandrade — APPROVED** [review]

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by lucasperj** [comment]
Just started reviewing :)

**Pull request closed without merging**
