### PR TITLE
LPD-29408 Use fetch function to get roles from API instead of useResource hook

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-29408

This is the first Workflow PR with Typescript code! Now we can write Typescript in this module :tada:

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGMT! :tada: great work @danvb112!
i will now test manually to see if everything is working as expected :tulip:

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
also i saw you did a modification on frontend-js-web, it looks fine to me but i think we need to send to them to review? @danvb112

**Comment by danvb112** [comment]
ci:test:playwright

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:workflow

**Comment by danvb112** [comment]
CI Failures are not related!

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
