### PR TITLE
LPS-167798 HR_160 The close button aren't being announced properly

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-167798](https://issues.liferay.com/browse/LPS-167798)

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:stop

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:workflow

**Comment by larissacribeiro** [comment]
Hey @naraandrade, I'm running the tests again because I had to change the color used! 😃

**Review by naraandrade — CHANGES_REQUESTED** [review]
@larissacribeiro Based on the comments in the ticket, you should insert the field reference in the aria label in the format "Remove + (Field Reference) + option". So, you should receive a parameter inside the language key to pass the field reference.

**Comment by larissacribeiro** [comment]
ci:test:sf

**Comment by larissacribeiro** [comment]
ci:test:relevant

**Comment by larissacribeiro** [comment]
ci:test:workflow

**Review by naraandrade — APPROVED** [review]

**Comment by larissacribeiro** [comment]
sent it to liferay-forms :blush:

**Pull request closed without merging**
