### PR TITLE
LPS-190884 | Master

### PR DESCRIPTION
**Pull request by davisaints**
**JIRA Ticket: [LPS-190884](https://liferay.atlassian.net/browse/LPS-190884)**

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by Kvale1733** [comment]
ci:test:workflow

**Comment by Kvale1733** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
This pull request has been closed in favor of https://github.com/liferay-workflow/liferay-portal/pull/981

cc: @davisaints

**Pull request closed without merging**
