### PR TITLE
LPS-151540 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:reevaluate:1317401_5867

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
The results were [checked with QA](https://liferay.slack.com/archives/C026UR5976G/p1668453016712099?thread_ts=1668430820.289589&cid=C026UR5976G). 

PR resent here: https://github.com/brianchandotcom/liferay-portal/pull/126218

**Pull request closed without merging**
