### PR TITLE
[TS] LPS-152811

### PR DESCRIPTION
**Pull request by crodriguezy**
Related Issue: https://issues.liferay.com/browse/LPS-152811

### CODE REVIEW

**Comment by liferay-forms** [comment]
Hi, you don’t need to run the CI commands anymore, I’ll do it for you and let you know if any issue happens.

**Comment by liferay-forms** [comment]
ci:test:sf

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
ci:test:relevant

**Comment by liferay-forms** [comment]
Hey @crodriguezy, can you please check if these failures are related to your changes? Thanks

**Comment by liferay-forms** [comment]
Hey @crodriguezy, can you please check if these failures are related to your changes? Thanks

**Comment by MarinhoFeliphe** [comment]
Hi @crodriguezy,

Now the official repository of Workflow is [this](https://github.com/liferay-zulu), could you resent there?

Thank you,
Feliphe

**Comment by crodriguezy** [comment]
Sorry @MarinhoFeliphe , please see https://github.com/liferay-zulu/liferay-portal/pull/141

**Pull request closed without merging**
