### PR TITLE
LPD-27045 Add restrictedFields for rolePermissions

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-27045

Test is not needed. Performance fix

### CODE REVIEW

**Comment by brianikim** [comment]
@linolaoj , tied to LPP

**Comment by linolaoj** [comment]
ci:test:workflow

**Comment by linolaoj** [comment]
Hi @brianikim, it looks good to me. I'll ask for a frontend engineer to take a look to see if we should add a test for this. In case a test is not needed I suggest editing the commit message to explain why the test is not needed.
cc: @igor-franca

**Comment by igor-franca** [comment]
Starting the review

**Comment by igor-franca** [comment]
Hey, after reading the LPP I was able to test the application and compare the requests' returns.

I couldn't find a use for the restricted field property in the application. So, everything is fine with the changes :)

**Review by igor-franca — APPROVED** [review]

**Comment by linolaoj** [comment]
Thank you @igor-franca , changing the commit message here:
https://github.com/liferay-workflow/liferay-portal/pull/1162

**Pull request closed without merging**
