### PR TITLE
LPS-127322 Remove override of getAssetEntry method

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
LGTM

**Comment by rafaprax** [comment]
waiting for https://github.com/liferay-app-builder/liferay-portal/pull/243 be merged to trigger ci:forward again

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Manually sent here: https://github.com/brianchandotcom/liferay-portal/pull/99645

**Pull request closed without merging**
