### PR TITLE
LPS-120023 Update tests

### PR DESCRIPTION
**Pull request by gabrielpramos**
cc @albinojunior

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
@gabrielpramos , Let's hold on this PR since it is not related to a blocker ticket. I added the "on hold" label on that.

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:forward

**Review by inacionery — APPROVED** [review]

**Comment by inacionery** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:forward

**Comment by inacionery** [comment]
ci:forward

**Pull request closed without merging**
