### PR TITLE
LPD-16331 Update the endTimePicker time value

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-16331](https://liferay.atlassian.net/browse/LPD-16331)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:stop

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @guilhermedcamacho,
Could you assign the reviewer, please?

**Comment by guilhermedcamacho** [comment]
Hey @linolaoj, can you do the first review of this PR and then pass it on to @MarinhoFeliphe? Thanks!

**Review by linolaoj — APPROVED** [review]
Looks good to me.

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by vngoliveira** [comment]
ci:test:calendar

**Review by linolaoj — APPROVED** [review]

**Comment by vngoliveira** [comment]
ci:foward

**Comment by vngoliveira** [comment]
Since all suites passed, I will manually forward this fix to BChan.

**Comment by vngoliveira** [comment]
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/147681

**Pull request closed without merging**
