### PR TITLE
LPS-126707 Apply checkRequiredFields function to Custom Object and Form View Creation

### PR DESCRIPTION
**Pull request by gabrielpramos**
cc @rafaprax @naraandrade 
story: [LPS-124979](https://issues.liferay.com/browse/LPS-124979)

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
@rodrigocunhaa does the poshi updates looks good to you?

**Comment by rodrigocunhaa** [comment]
Looks good @gabrielpramos (:

**Pull request closed without merging**
