### PR TITLE
LPS-121134 Use the retry approach as the insertion of the nested object appears to be done asynchronously into elasticsearch

### PR DESCRIPTION
**Pull request by rafaprax**
cc @inacionery @rodrigocunhaa

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:search

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:search-solr

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Forwarded to https://github.com/liferay-workflow/liferay-portal/pull/46

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
