### PR TITLE
Lps 157721 Change Notification link to use always use '/manage' as layout friendlyURL

### PR DESCRIPTION
**Pull request by kristofloneck**

### CODE REVIEW

**Comment by kristofloneck** [comment]
ci:test:sf

**Comment by kristofloneck** [comment]
@MarinhoFeliphe 
What is the status with this PR.

**Comment by MarinhoFeliphe** [comment]
I'm taking a look,

Sorry for the late reply

**Comment by MarinhoFeliphe** [comment]
@kristofloneck,

I resent [here](https://github.com/liferay-workflow/liferay-portal/pull/797), could you test if it's fixing this issue?

Thank you,
Feliphe

**Pull request closed without merging**
