### PR TITLE
[7.4 Only] LPS-123223 Regen

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-105491](https://issues.liferay.com/browse/LPS-105491)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:app-builder

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
LGTM

**Comment by rafaprax** [comment]
@rodrigocunhaa , are these failures related with this changes?

Thx

**Review by rafaprax — APPROVED** [review]

**Comment by rodrigocunhaa** [comment]
@rafaprax , it is not. Those 2 tests have been failing for a while.

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
