### PR TITLE
[TS] LPS-123612

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello,

These changes make it so that an .ics file is attached to the invitation email notification.

I could not see a clean solution that did not involve modifying the API in order to achieve the goal. If you see a different way to pass along the calendar booking or would prefer avoiding a major version increment versus keeping the code clean please let me know. I'd be happy to rework the solution.

Please let me know if there are any questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:calendar

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/138

Thanks for your contribution

**Comment by jonathanmccann** [comment]
@rafaprax Thank you for reviewing it and making those changes.

**Pull request closed without merging**
