### PR TITLE
LPS-187901 Remove unused WorkflowEngineManager, WorkflowEngineManagerImpl and WorkflowEngineManagerUtil

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by JanisZhang** [comment]
Thanks @MarinhoFeliphe!
cc @dantewang

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
Rerun because I added new commits to fix SF issue.

cc: @JanisZhang

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/139347

**Comment by JanisZhang** [comment]
Thanks @MarinhoFeliphe !

**Comment by MarinhoFeliphe** [comment]
No problem :)

@JanisZhang thanks for your contribution!

**Pull request closed without merging**
