### PR TITLE
LPS-120975 Inject  property AppBuilderWebKeys.SHOW_TRANSLATION_MANAGE on request

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:forward

**Comment by inacionery** [comment]
Hey @albinojunior,

The test failed `Execution failed for task ':dxp:apps:app-builder-workflow:app-builder-workflow-web:packageRunTest'.`

Please resend.

Thanks!

**Comment by inacionery** [comment]
ci:close

**Comment by albinojunior** [comment]
Just started reviewing :)

**Pull request closed without merging**
