### PR TITLE
LPS-174984

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you pease check my fix.

**Steps to Reproduce:**

1) Start a Liferay bundle
2) Add Calendar portlet to a page.
3) Go to Configurations of calendar portlet.
4) Go to display settings and do the following settings.
i) Enable only the Agenda view
ii) Select “Maximum Days to Display” as 0
iii) Select “Maximum Events to Display” 4 (default value)
5) Save the settings and publish the page
6) Go to Calendar and click on “Add Event”, give the following details:
i) Title as “My Event”
ii) start date as “03rd Feb 2023”
iii) End date as “07th Feb 2023" check “All day” check box
4 to check with max value as well)
7) Click on Publish.
8) Click on “03rd Feb 2023" to check 03rd Feb events and observe the behaviour. 

**Expected Behaviour:** Only the 03rd Feb 2023 event should be displayed as we have selected maxDaysDisplayed as 0.
**Actual Behaviour:** All 5 days events are displayed. (03rd, 04th, 05th, 06th, 07th) with the same repeating event displayed.
Also, I have checked by changing the Maximum Days to Display value to 1,2,3 & 4 but still, it shows all 5 days events

**Fix**

Using maxDaysDisplayed in the Agende view too.
Additionaly i added more options to the Maximum Days to Display configuration.

Thanks, Roland

https://issues.liferay.com/browse/LPS-174984

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by rolandpakai** [comment]
ci:test:calendar

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by rolandpakai** [comment]
Hi @naraandrade 

could you please push this forward?

Thanks, Roland

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
> Hi @naraandrade
> 
> could you please push this forward?
> 
> Thanks, Roland

Sorry for the delay, I'll be forwarding it now.

**Comment by naraandrade** [comment]
ci:forward

**Comment by rolandpakai** [comment]
Hi @naraandrade

could you please push this forward?

Thanks, Roland

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/130778

**Pull request closed without merging**
