### PR TITLE
LPD-23125 Calendar widget changes start time when editing end time

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-23125](https://liferay.atlassian.net/browse/LPD-23125)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:calendar

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by pedro-oliveira446** [comment]
ci:forward:force

**Pull request closed without merging**
