### PR TITLE
LPS-191270 Avoid permission checker is not initialized error

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by gabrielwas — APPROVED** [review]
LGTM ;)

**Comment by MarinhoFeliphe** [comment]
As soon as the QA team ensure the failures are not related I'll reopen this pull below in Brian's repo.

https://github.com/brianchandotcom/liferay-portal/pull/138208

cc: @samuelromeiro @gabrielwas

**Comment by samuelromeiro** [comment]
Merged ✅

**Pull request closed without merging**
