### PR TITLE
LPS-198185 Check if the simpleMenu variable isn't null to put the aria-controls in the calendar

### PR DESCRIPTION
**Pull request by vngoliveira**
LPP ticket: [LPP-51038](https://liferay.atlassian.net/browse/LPP-51038)
Related issue: [LPS-198185](https://liferay.atlassian.net/browse/LPS-198185)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Pull request closed without merging**
