### PR TITLE
LPS-134779 Change clay charts lib to Recharts

### PR DESCRIPTION
**Pull request by jotascript**
Technical Debt issue: [LPS-133097](https://issues.liferay.com/browse/LPS-133097)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Review by ramonmsp — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by jotascript** [comment]
ci:forward

**Pull request closed without merging**
