### PR TITLE
LPS-161793 Increase default interval of WorkflowMetricsSLAProcessMessageListener to 10 minutes

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:workflow-metrics

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
Hi @anabuchmann,

I noticed that some sla test are failing,

I'm not sure, but I believe we can set `1` for this property `check-sla-job-interval` for those tests,

I believe this property can be defined the same way as the feature flags.

you can try to run these tests with this `check-sla-job-interval=1` defined in your portal-ext.properties,

I can help you to investigate it.

If I'm right we can send this fix with the test changes.

cc: @rafaprax

**Comment by rafaprax** [comment]
Hey @MarinhoFeliphe , @anabuchmann already sent the tests here https://github.com/anabuchmann/liferay-portal/pull/444. We were waiting for the sync to trigger the forward. 

Thx

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
