### PR TITLE
LPS-129909 Remove Panel component

### PR DESCRIPTION
**Pull request by jotascript**

### CODE REVIEW

**Comment by rafaprax** [comment]
@jotascript Related error here.

>[exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dxp:apps:portal-workflow:portal-workflow-metrics-web:packageRunTest

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by naraandrade — APPROVED** [review]

**Comment by rafaprax** [comment]
@jotascript, well done! 👏 👏

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Pull request closed without merging**
