### PR TITLE
LPS-184168 - White screen in Workflow Definition Notifications

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-184168]( https://liferay.atlassian.net/browse/LPS-184168)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relavant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:workflow

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relavant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:workflow

**Review by alinedoleron — APPROVED** [review]
LGTM!

**Comment by alinedoleron** [comment]
ci:forward:force

**Comment by alinedoleron** [comment]
ci:forward:force

**Comment by alinedoleron** [comment]
ci:forward:force

**Pull request closed without merging**
