### PR TITLE
LPS-126591 Check required fields in first step's form when app is undeployed

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Review by gabrielpramos — APPROVED** [review]
LGTM
all right to forward after rebasing to master

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
