### PR TITLE
LPD-34803 Fix Regular Role in Task Timers Reassignment | LPD-34663  Fix playwright tests for the portal-workflow-kaleo-designer-web module

### PR DESCRIPTION
**Pull request by igor-franca**
Related Tickets:

https://liferay.atlassian.net/browse/LPD-34663
https://liferay.atlassian.net/browse/LPD-34803

### CODE REVIEW

**Comment by igor-franca** [comment]
Result in master:

screenshot-1724698313

Result in the react 18 branch:

screenshot-1724700393

**Comment by igor-franca** [comment]
I will run the tests on CI to check if we have the same results found locally

**Comment by igor-franca** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:test:workflow

**Comment by igor-franca** [comment]
ci:test:workflow

**Comment by igor-franca** [comment]
Unable to view results in Testray

I will try to analyze the results in Jenkins and report the problem to the CI/Testray team

**Comment by igor-franca** [comment]
ci:report:72431893

**Comment by igor-franca** [comment]
Everything is fine with the result of playwright and poshi workflow 😄

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by igor-franca** [comment]
ci:test:sf

**Comment by igor-franca** [comment]
ci:forward

**Comment by igor-franca** [comment]
ci:stop

**Comment by igor-franca** [comment]
ci:forward:force

**Comment by igor-franca** [comment]
ci:forward:force

**Pull request closed without merging**
