### PR TITLE
LPS-136355 Create State node type components

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-133990](https://issues.liferay.com/browse/LPS-133990)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Review by ramonmsp — APPROVED** [review]
Amazing o/

**Comment by jotascript** [comment]
Just started reviewing :)

**Review by jotascript — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
