### PR TITLE
LPS-141069 Rename model to modelClass

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Story: [LPS-140647](https://issues.liferay.com/browse/LPS-140647)

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Review by rafaprax — APPROVED** [review]

**Pull request closed without merging**
