### PR TITLE
[7.4 only] LPS-123605 Allow add new form view into any workflow app process steps

### PR DESCRIPTION
**Pull request by albinojunior**
/cc @gabrielpramos @naraandrade

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by albinojunior** [comment]
ci:test:stable

**Comment by albinojunior** [comment]
ci:forward

**Pull request closed without merging**
