### PR TITLE
LPS-172102

### PR DESCRIPTION
**Pull request by holatuwol**
## Motivation

https://issues.liferay.com/browse/LPS-172102
https://issues.liferay.com/browse/PTR-3571

## Problem overview

In the UI for Role Type assignment, we select roles by title, which in turn generates an XML that gets sent to the backend.

The issue is that this serialized XML contains the role title instead of the role name, due to a limitation of the API provided by users admin, which returns the "title" in the "name" field. There is currently no way to retrieve the actual role "name" (which is the "key" in the roles admin UI) from the headless API, and retrieving the key would require either a users admin update or falling back to the JSON-WS API.

## Proposed solution

The PTR has asked to implement a backend update rather than use the JSON-WS API, and so this updates ``RoleUtil`` so that, if it is unable to find any role by name, it searches role titles to see if there is a match.

In order to avoid a related bug, where having a different user locale results in different behavior, this updated code searches against *all* titles in all locales. To avoid potential issues where there are multiple roles with the same title, it throws an exception if it encounters duplicate titles.

## Steps to verify

1. Create a role with title `abc` and key `def`
1. With kaleo designer deployed, navigate to Applications > Workflow > Process Builder
1. Choose to add a new workflow
1. Add a task node and add transitions to the other two existing nodes
1. Select the task node and attempt to update the assignment to the 'abc' role

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @holatuwol @naraandrade, Did you check this behavior with the old Kaleo Designer UI on some previous versions of Liferay?
It could be a migration issue. If so, from my point of view, the solution must restore the old behavior.
Could you please check this?

Thx

**Comment by naraandrade** [comment]
> Hey @holatuwol @naraandrade, Did you check this behavior with the old Kaleo Designer UI on some previous versions of Liferay? It could be a migration issue. If so, from my point of view, the solution must restore the old behavior. Could you please check this?
> 
> Thx

Hi @rafaprax, in the 7.3 the role is represented by its key on the list. The problem is that we don't have access to the role's key through API. I tried following this approach before: "update the frontend to continue showing titles, but store the key instead to submit to the backend" and I have encounter this limitation. I've reach out to the team responsible for Roles to try to retrieve the key through the API, you can see the thread [here](https://liferay.slack.com/archives/CNUCYF7EW/p1673272321816709). If you think we shouldn't follow the approach @holatuwol implemented, I can talk with US&M again to ask for the change in the API. Thanks :)

**Comment by rafaprax** [comment]
Hey @naraandrade,
My main concern here is that even after this fix we still have an issue when we have two Roles with the same title in different locales.

>In order to avoid a related bug, where having a different user locale results in different behavior, this updated code searches against all titles in all locales. To avoid potential issues where there are multiple roles with the same title, it throws an exception if it encounters duplicate titles.

Let's imagine this hypothetical scenario 😄  🍝  📁  :
```
Role 1 : {
     title: {
            en_US: "Pasta",
            pt_BR: "Macarrão" 
    },
    key: "123"
}

Role 2 : {
     title: {
            en_US: "Folder",
            pt_BR: "Pasta" 
    },
    key: "456"
}
```

In an "en_US" site a user that chooses the "Pasta" Role will be unable to save the workflow definition because the Role 2 will match the search in the backend code as well. 

So, from my point of view, we should ask the USM team to add "key" field to the Role API. 

Thanks in advance

**Comment by naraandrade** [comment]
> Hey @naraandrade, My main concern here is that even after this fix we still have an issue when we have two Roles with the same title in different locales.
> 
> > In order to avoid a related bug, where having a different user locale results in different behavior, this updated code searches against all titles in all locales. To avoid potential issues where there are multiple roles with the same title, it throws an exception if it encounters duplicate titles.
> 
> Let's imagine this hypothetical scenario smile spaghetti file_folder :
> 
> ```
> Role 1 : {
>      title: {
>             en_US: "Pasta",
>             pt_BR: "Macarrão" 
>     },
>     key: "123"
> }
> 
> Role 2 : {
>      title: {
>             en_US: "Folder",
>             pt_BR: "Pasta" 
>     },
>     key: "456"
> }
> ```
> 
> In an "en_US" site a user that chooses the "Pasta" Role will be unable to save the workflow definition because the Role 2 will match the search in the backend code as well.
> 
> So to avoid this kind of weird behavior, from my point of view, we should ask the USM team to add "key" field to the Role API.
> 
> Thanks in advance

It totally makes sense. Thanks for explanation, @rafaprax. I'll talk to US&M again :)

**Pull request closed without merging**
