### PR TITLE
LPD-23595, LPD-23661 -  Hide Java options from worfklow ui when allowScriptContentToBeExecutedOrIncluded setting is false

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues: 
https://liferay.atlassian.net/browse/LPD-23595
https://liferay.atlassian.net/browse/LPD-23661

### CODE REVIEW

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :cherry_blossom: :tada:

**Comment by rebsilva** [comment]
the manual tests will be done as soon as possible, i will let you know when i'm done

**Comment by danvb112** [comment]
ci:test:workflow-metrics

**Comment by rebsilva** [comment]
tested manually and LGTM! :cherry_blossom:

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:workflow

**Comment by danvb112** [comment]
ci:test:workflow-metrics

**Comment by danvb112** [comment]
worflow suite failures are note related!

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
Workflow Metrics suite test failures are not Related!

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/149572

**Pull request closed without merging**
