### PR TITLE
LPS-197353 Fixing workflow tests

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
PR sent by @4lejandrito, please read [1c0ffc2](https://github.com/liferay-workflow/liferay-portal/pull/1016/commits/1c0ffc20526f658927caa91847c1431debad953e) and this [comment](https://github.com/liferay-objects/liferay-portal/pull/2796#issuecomment-1815623978) in the original PR.

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:workflow

**Comment by 4lejandrito** [comment]
Hey @guilhermedcamacho , @MarinhoFeliphe ,

[This PR](https://github.com/liferay-workflow/liferay-portal/pull/1014) cannot be merged because it modifies the base class which is autogenerated by rest builder. I will look into the failure @guilhermedcamacho mentioned [here](https://github.com/liferay-objects/liferay-portal/pull/2796#issuecomment-1815623978) and fix it if necessary.

**Comment by MarinhoFeliphe** [comment]
Taking a looking

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/144318

**Comment by MarinhoFeliphe** [comment]
Thanks @4lejandrito for your contribution!

**Pull request closed without merging**
