### PR TITLE
LPS-129019 Add tests to cover MissingRequiredFieldsPopover usage

### PR DESCRIPTION
**Pull request by jotascript**

### CODE REVIEW

**Comment by jotascript** [comment]
cc: @interaminense

**Review by naraandrade — CHANGES_REQUESTED** [review]
Add a few more steps (as I talked to you previously) on MissingRequiredFieldsPopover test to cover 100% of the component.

**Comment by jotascript** [comment]
ci:test:sf

**Comment by jotascript** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by rafaprax** [comment]
closing due to the App Builder freezing

**Pull request closed without merging**
