### PR TITLE
LPS-134559 Add WorkflowTaskTransitionsResourceTest's integration test

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:help

**Comment by rafaprax** [comment]
ci:test:bundle

**Comment by rafaprax** [comment]
ci:forward

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Pull request closed without merging**
