### PR TITLE
LPS-178897 Return a user ID of 0 in the case of a null session

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
@jonathanmccann 

there are some failures related, could you please take a look at them?

you can start taking a look at [this one](https://testray.liferay.com/home/-/testray/case_results/2242141409?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2242083705%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) [[LOG](https://testray.liferay.com/reports/production/logs/2023-03/test-1-32/test-portal-acceptance-pullrequest(master)/8717/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)] because I believe that it will be easier to find the root cause

Thank you!
Feliphe

**Comment by MarinhoFeliphe** [comment]
> Should this be considered an issue with the fix (where we can add in another null check and return early if the request is missing) or with the test since it is not populating?

@jonathanmccann I believe we should provide a null checker for request, because I believe when this snippet of code is called from the Workflow Task Timer it isn't passing the request and I believe we will not be able create a httpRequest to pass

**Comment by jonathanmccann** [comment]
Thanks for the feedback. I've resent it with a null check here https://github.com/liferay-workflow/liferay-portal/pull/913

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/913

**Pull request closed without merging**
