### PR TITLE
[CLDR] LPD-18592 Fix functional test AddCalendar#DefaultTimeZoneFollowsUserPreferences to work with CLDR locale provider

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:report:2546218502

**Comment by julschong** [comment]
ci:report:2546229930

**Review by guilhermedcamacho — APPROVED** [review]
LGTM! :tada: 
Thanks for contributing @julschong, sorry for the delay.

**Comment by guilhermedcamacho** [comment]
The test [AddCalendar#DefaultTimeZoneFollowsUserPreferences](https://testray.liferay.com/home/-/testray/case_results/2546230097?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2546229930%26testrayRunId%3D2546229956%26cur%3D2%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse) passed

**Comment by guilhermedcamacho** [comment]
ci:forward

**Pull request closed without merging**
