### PR TITLE
LPS-120432 Remove unnecessary useMemo occurrences and improve the metrics pages performance

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
Hey @albinojunior,

This failure is real [LocalFile.WorkflowMetrics#DefaultWorkflowMetricsFilterValues](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/299323//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_WorkflowMetrics_DefaultWorkflowMetricsFilterValues_) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/test-1-3/1599685353311/test-portal-acceptance-pullrequest(master)/8167/functional-tomcat90-mysql57-jdk8/11/0/LocalFile.WorkflowMetrics_DefaultWorkflowMetricsFilterValues/summary.html.gz) 

Please resend

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
