### PR TITLE
LPS-132023 Remove slaResults check and add background color to slaStatusIcon

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:stop

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Review by ramonmsp — APPROVED** [review]

**Comment by ramonmsp** [comment]
ci:test:relevant

**Pull request closed without merging**
