### PR TITLE
LPS-177901 Update xml files

### PR DESCRIPTION
**Pull request by naraandrade**
Related issue: https://issues.liferay.com/browse/LPS-177901

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by patriciajeanperez** [comment]
Superseded by https://github.com/liferay-workflow/liferay-portal/pull/928

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
