### PR TITLE
LPS-155539 Delete WorkflowInstanceLink before delete the Layout

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://liferay.atlassian.net/browse/LPS-155539

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:workflow

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hey @mateussgn could you please send this pr to the team responsible for this component since you've only changed on their side?

and I believe you will need to cover other delete methods, because I see more than one method that performs delete operation.

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:stop

**Comment by MarinhoFeliphe** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/14439

**Comment by mateussgn** [comment]
Thanks for the comments and for link the resent PR, @MarinhoFeliphe!

**Pull request closed without merging**
