### PR TITLE
LPD-20217

### PR DESCRIPTION
**Pull request by linolaoj**
https://liferay.atlassian.net/browse/LPD-20217
This issue only happens when creating an event with the Month view.
The idea of the fix is to use the parameter Time when it is present.

### CODE REVIEW

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hey @linolaoj I believe the proper fix is on frontend side because everything works fine when we change the time after uncheck the all day check box, so my assumption is that some values is not beeing passed properly when the click event of this check box is called, here is the place where I believe is the issue:

https://github.com/liferay/liferay-portal/blob/be2d617a815049b787286a32c3a39c9fad6d3047/modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/edit_calendar_booking.jsp#L1006

please feel free to reach me if you would like to debug together :)

Thank you!

**Comment by linolaoj** [comment]
Hi @MarinhoFeliphe , I've pushed the commit https://github.com/liferay-workflow/liferay-portal/pull/1100/commits/c8dc65f5943c436005a4166882dcd1af10f5b201 to edit the file that you suggested.
This fix is similar to https://github.com/brianchandotcom/liferay-portal/pull/147681/commits/82326338a968f25f94d09172cac30465ad781e67.

Let me know if more changes are needed.

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

nice job! @linolaoj

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:forward

**Pull request closed without merging**
