### PR TITLE
LRQA-59704 Fix KaleoFormsEditSingleApprover#CompleteProcessAndViewEmailNotifications path selector

### PR DESCRIPTION
**Pull request by albinojunior**
/cc @rodrigocunhaa

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
@albinojunior , the CompleteProcessAndViewEmailNotifications test still failed on the ci:test:workflow suite. Could you please check it?

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
Hey @rodrigocunhaa, the failed test case is passing on local environment. I'll investigate it.

**Comment by albinojunior** [comment]
ci:close

**Comment by albinojunior** [comment]
ci:test:workflow

**Pull request closed without merging**
