### PR TITLE
[TEST] LPD-15226 Allowing company admins to publish a workflow

### PR DESCRIPTION
**Pull request by rijema**

### CODE REVIEW

**Comment by rijema** [comment]
ci:workflow

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:workflow

**Review by gabrielwas — APPROVED** [review]

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test:workflow-metrics

**Comment by rijema** [comment]
LocalFile.WorkflowMetricsAllItemsList#TaskReassignedToMultipleUsers was not found on the unique failures from this PR.

**Comment by guilhermedcamacho** [comment]
Were you able to successfully run this test locally? If so, maybe it's something related to CI.
Are you going to keep working on this or would you rather close this PR and put this ticket back in the queue?

**Comment by rijema** [comment]
Hi @guilhermedcamacho the error reported through the CI was not reproduced locally, it's always a different error. With the fix passed locally, but I can rerun and see the results nowadays. How should we approach this regarding the different errors? Thanks

**Pull request closed without merging**
