### PR TITLE
LPS-134160 Update filter criteria to take into account the process version

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/103761

**Pull request closed without merging**
