### PR TITLE
LPS-138038 Display nodes labels instead of nodes ids

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-136249](https://issues.liferay.com/browse/LPS-136249)

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Review by rafaprax — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Review by jotascript — APPROVED** [review]

**Comment by ramonmsp** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Pull request closed without merging**
