### PR TITLE
LPS-121674 Apply padding on modal panel

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:workflow

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:test:sf

**Review by naraandrade — APPROVED** [review]

**Review by albinojunior — APPROVED** [review]

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent at https://github.com/liferay-workflow/liferay-portal/pull/71

**Pull request closed without merging**
