### PR TITLE
LPS-196963 Liferay Calendar Accessibility Issue - Text Contrast

### PR DESCRIPTION
**Pull request by larissacribeiro**
Related Issue: [LPS-196963](https://liferay.atlassian.net/browse/LPS-196963)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by rebsilva** [comment]
ci:forward

**Pull request closed without merging**
