### PR TITLE
LPS-125488 Check if all required object-level fields are included in form views

### PR DESCRIPTION
**Pull request by albinojunior**
/cc @naraandrade @gabrielpramos | *Story:* [LPS-116593](https://issues.liferay.com/browse/LPS-116593)

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
Just started reviewing :)<br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by naraandrade — APPROVED** [review]

**Review by gabrielpramos — APPROVED** [review]
LGTM 🔥

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:forward

**Pull request closed without merging**
