### PR TITLE
LPS-181256 Unable to parse definition when importing new workflow definition

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-181256](https://issues.liferay.com/browse/LPS-181256)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:workflow

**Comment by pedro-oliveira446** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
I'm just aligning some details with QA about this ticket before forwarding this PR.

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/135322

**Pull request closed without merging**
