### PR TITLE
Revert "LPS-138476 calendar-web - replace usages of A.merge with Object.assign"

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:help

**Comment by MarinhoFeliphe** [comment]
ci:test:kaleo-forms

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Review by rafaprax — APPROVED** [review]

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:kaleo-forms

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
Hi @kresimir-coko,

the changes in https://github.com/brianchandotcom/liferay-portal/pull/109296 caused 2 regression https://issues.liferay.com/browse/LPS-142037 and https://issues.liferay.com/browse/LPS-142043. So, for now, we are going to send this revert pr to fix them ASAP. Can you please ping us when you have a solution for https://issues.liferay.com/browse/LPS-138476 just to let us run our test suites?

Thx

/cc @anabuchmann

**Comment by kresimir-coko** [comment]
@rafaprax thanks for letting me know, I'll prioritize this 👍

**Comment by kresimir-coko** [comment]
@rafaprax I tested the [blogs assignment revert](https://issues.liferay.com/browse/LPS-142043) on `master` @ 0b87d05f with the commits that were reverted and I couldn't replicate the abnormalities reported.

When it comes to the [kaleo form edit buttons](https://issues.liferay.com/browse/LPS-142037) not working, I've tested it against the same branch on master and with the reverted commits, and both behave the same => `Cancel` button doesn't do anything, the `Save` button fires up the notification that the form has been saved, but nothing can close the modal.

I will test this on fresh `master` to see if it behaves the same and edit this comment with my findings.

**Pull request closed without merging**
