### PR TITLE
LPD-21649 When the “All Day” tick box is selected and saved, default times will show when the event details are opened

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-21649](https://liferay.atlassian.net/browse/LPD-21649)

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:test:relevant

**Comment by pedro-oliveira446** [comment]
ci:test:calendar

**Review by MarinhoFeliphe — APPROVED** [review]
LGTM!! :tada:

**Comment by pedro-oliveira446** [comment]
Sent manually to Brian

**Pull request closed without merging**
