### PR TITLE
LRQA-63325 Remove test out of quarantine

### PR DESCRIPTION
**Pull request by albinojunior**
/cc @rodrigocunhaa

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Review by rodrigocunhaa — APPROVED** [review]

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
@albinojunior , looks like the test is still failing. Could you please check it?

**Comment by albinojunior** [comment]
> @albinojunior , looks like the test is still failing. Could you please check it?

I'll run it again, the fail is not related with the previous.

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:forward

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:close

**Pull request closed without merging**
