### PR TITLE
LPS-138324 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:calendar

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Hey @seltong, Can you please add an integration test to cover this scenario?
Thx

**Comment by seltong** [comment]
Just started reviewing :)

**Comment by seltong** [comment]
Just started reviewing :)

**Pull request closed without merging**
