### PR TITLE
LPD-27022 Enable CX workflow action even if the task doesn't have a user as assignee

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related issue: https://issues.liferay.com/browse/LPD-27022

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:workflow

**Comment by p-albuquerque** [comment]
ci:forward

**Pull request closed without merging**
