### PR TITLE
LPS-154202 Error messages do not make it clear to the user what is wrong with the diagram

### PR DESCRIPTION
**Pull request by michaelmdelcavalcanti**
LPS: [LPS-154202](https://issues.liferay.com/browse/LPS-154202)

I create mapper to display correct message error inside of Process Builder in Workflow.

Final Result:
image

### CODE REVIEW

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @naraandrade,

I suggested these changes to display the same messages that are displayed in the old process builder,

the problem is that this messages are not localized as in the old process builder

so I believe we can open a technical debt or a bug to translate these messages as well.

I reviewed the michael's changes and it looks good to me, I also test some cases.

The failures are not related, I can forward to Brian if you agree.

cc: @michaelmdelcavalcanti

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by naraandrade** [comment]
> Hi @naraandrade,
> 
> I suggested these changes to display the same messages that are displayed in the old process builder,
> 
> the problem is that this messages are not localized as in the old process builder
> 
> so I believe we can open a technical debt or a bug to translate these messages as well.
> 
> I reviewed the michael's changes and it looks good to me, I also test some cases.
> 
> The failures are not related, I can forward to Brian if you agree.
> 
> cc: @michaelmdelcavalcanti

Thank you, Feliphe :) I'll just test it locally too before forwarding it.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
> Hi @naraandrade,
> 
> I suggested these changes to display the same messages that are displayed in the old process builder,
> 
> the problem is that this messages are not localized as in the old process builder
> 
> so I believe we can open a technical debt or a bug to translate these messages as well.
> 
> I reviewed the michael's changes and it looks good to me, I also test some cases.
> 
> The failures are not related, I can forward to Brian if you agree.
> 
> cc: @michaelmdelcavalcanti

I opened this [technical debt](https://issues.liferay.com/browse/LPS-162220).

**Comment by michaelmdelcavalcanti** [comment]
thx, @naraandrade and @MarinhoFeliphe.

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
Hi @michaelmdelcavalcanti,

[This test](https://testray.liferay.com/home/-/testray/case_results/1967284497?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1967278003%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is failing, could you try to solve?, these changes are related.

I believe you can fix by creating another mapper for that exception and pass `Response.Status.NOT_FOUND` instead of `Response.Status.BAD_REQUEST` [at this line](https://github.com/liferay-workflow/liferay-portal/pull/808/files#diff-ae7edf7abe52d266e95421e7661e36121e840874a84a67a20a121fd558c01a28R43)

Feel free to contact me if you need help.

Thank you!
Feliphe

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hi @michaelmdelcavalcanti,

[This test](https://testray.liferay.com/home/-/testray/case_results/1967284497?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1967278003%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is failing, could you try to solve?, these changes are related.

I believe you can fix by creating another mapper for that exception and pass Response.Status.NOT_FOUND instead of Response.Status.BAD_REQUEST [at this line](https://github.com/liferay-workflow/liferay-portal/pull/808/files#diff-ae7edf7abe52d266e95421e7661e36121e840874a84a67a20a121fd558c01a28R43)

Feel free to contact me if you need help.

Thank you!
Feliphe

**Comment by michaelmdelcavalcanti** [comment]
Hello @MarinhoFeliphe, changes made, thanks.

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by michaelmdelcavalcanti** [comment]
ci:test:sf

**Comment by michaelmdelcavalcanti** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
@michaelmdelcavalcanti,

I just made little changes, [see](https://github.com/brianchandotcom/liferay-portal/pull/122887),

Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/122887)

Great job!

**Pull request closed without merging**
