### PR TITLE
LPS-137357 Add graphQL integration test for /reindex/statuses

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by rafaprax — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by anabuchmann — APPROVED** [review]

**Comment by rafaprax** [comment]
Hi @anabuchmann,

if this ci's run don't pass, please forward it manually to BChan. 

Thank you

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/105731

**Pull request closed without merging**
