### PR TITLE
LPS-132186 Fix sort expected in tests

### PR DESCRIPTION
**Pull request by naraandrade**
Story: [LPS-130217](https://issues.liferay.com/browse/LPS-130217)

### CODE REVIEW

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
Hey @naraandrade Can you please rebase this pr and remove the @MarinhoFeliphe's commits? Thx

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by ramonmsp — APPROVED** [review]

**Review by rafaprax — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:bundle

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
