### PR TITLE
LPS-120449 Update functional tests

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
Hey @rodrigocunhaa,

Could you please forward this PR manually?

Thanks!

**Review by inacionery — APPROVED** [review]

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Pull request closed without merging**
