### PR TITLE
LPS-139169

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-139169

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
forwarded to Shuyang here https://github.com/shuyangzhou/liferay-portal/pull/10288.

Thx @mbowerman

**Pull request closed without merging**
