### PR TITLE
LPS-121020 Use WorkflowMetricsPortalExecutor on createIndex and removeIndex to avoid concurrency issues

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
ci:stop

**Pull request closed without merging**
