### PR TITLE
LPS-167188 - Screen reader not announcing elements in Calendar widget properly

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-167188

**Steps to Reproduce**
1. Open JAWS screen reader
2. Navigate to a page with the calendar portlet
3. Under the "My Calendars" section click on the dropdown arrow next to your calendar to open the calendar action menu.
4. Using arrow keys move to the color picker and attempt to select an option.
**Expected Result**
- It should be possible to select a color and steps and feedback should be clearly voiced by the screen reader.
**Actual Result**
- It is not possible to select a color with the keyboard.

@marcoscv-work provided the following fix recommendations that have been followed:
- Dropdown menu separators shouldn't get the focus by tab-key
- When we get to `calendar-portlet-color-picker` it should have:
    - tabindex="0" and aria-label with the selected color, for example: "Selected color: #000000, please use arrows keys to select a new color"
    - Colors should be buttons in order to be pulsed and selected, each button has an aria-label with the color HEX code.
    - All colors should be inside a role="radiogroup", each color button could be inside a role="radio"
    - We will move along color buttons by arrows, 
    - When color is selected a role="alert" with class="sr-only" is created with the message: "Color XXX was selected" and dropdown is not closing since we can make more actions.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by marcoscv-work** [comment]
Tested PR, it works fantastic!

https://user-images.githubusercontent.com/7963804/207733604-94201da0-3ef6-4f93-92e2-2feb06845d83.mov

**Pull request closed without merging**
