### PR TITLE
LPS-138123 Adjust date pattern lang key to get correct return of format function

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by rafaprax — CHANGES_REQUESTED** [review]
Hey @naraandrade, this changes must be made in the Language(pt-br) file. Can you apply these changes there?

I think, now the languages files are in the centralized lang module.

Thx

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
