### PR TITLE
LPS-137357 Update the reindex request url

### PR DESCRIPTION
**Pull request by jotascript**
Issue: [LPS137357](https://issues.liferay.com/browse/LPS-137357)

### CODE REVIEW

**Comment by jotascript** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @jotascript, can you please remove from quarantine the tests ignored by Peter Shin?

@MarinhoFeliphe is there something to do on backend side?

Thx

/cc @anabuchmann

**Comment by MarinhoFeliphe** [comment]
Yes, there is, I'll do this

**Comment by MarinhoFeliphe** [comment]
Just started reviewing :)

**Comment by MarinhoFeliphe** [comment]
Follow up on [this pr](https://github.com/liferay-workflow/liferay-portal/pull/493)

/cc @anabuchmann, @jotascript and @rafaprax

**Pull request closed without merging**
