### PR TITLE
LPS-183752 Dropdown button in Metrics page header is misaligned

### PR DESCRIPTION
**Pull request by kildarep**
Hello Reviewer!
Related Issue: https://issues.liferay.com/browse/LPS-183752

To solve the problem, the container was changed to `nav?.firstElementChild`, moving it to the desired location.

### CODE REVIEW

**Comment by kildarep** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/135323

**Pull request closed without merging**
