### PR TITLE
LPS-165336 Change localStorage to new API

### PR DESCRIPTION
**Pull request by rebsilva**
Related Issue: https://issues.liferay.com/browse/LPS-165336

Hi reviewer! :cherry_blossom: 

This is related to the major task to remove all session and local storage from the code and use the new API created by de FI team, making Liferay stay in complience with the use of data of users from cookies.

On this specific task I've tried to remove the `localStorage` completely by doing the logic different, but I couldn't make it since the page refreshes on the first save/publish, losing the informations about the response; `useState` doesn't work because of the refresh and `useMemo` could work, but I don't have the infos of the response to make it get right. Therefore, I've kept the `localStorage` code, only changing it to the new API.

If you have any suggestions about this I would be happy to hear, thanks a lot! :purple_heart:

### CODE REVIEW

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:workflow

**Review by naraandrade — CHANGES_REQUESTED** [review]
Hi @rebsilva, thanks for your contribution :) I've tested the PR and everything works fine but I think we may need to change the type of local storage from PERSONALIZATION to FUNCTIONAL. See https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/2266300746/User+consent+enforcement+API+for+local+and+session+storage?focusedCommentId=2297103119.

**Comment by rebsilva** [comment]
Hello @naraandrade, thanks for your review! I've read the document you sent and I'm wondering if it should be FUNCTIONAL or PERFORMANCE; we can discuss this tomorrow at our meeting if you want!

**Comment by rebsilva** [comment]
ci:test:sf

**Comment by rebsilva** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
ci:test:workflow

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
