### PR TITLE
LPS-184339 - Created Field Set are only shown by manually refreshing the page

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-184339](https://liferay.atlassian.net/browse/LPS-184339)

### CODE REVIEW

**Comment by kristinonias** [comment]
Hi @Artartur @naraandrade 

I checked the failures on these and they don't seem related to this PR.

**Comment by naraandrade** [comment]
Just started reviewing :)

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:forward:force

**Comment by naraandrade** [comment]
ci:forward:force

**Pull request closed without merging**
