### PR TITLE
[TS] LPS-204766 Role type reassignments were not working correctly

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-204766](https://liferay.atlassian.net/browse/LPS-204766)

For some reason, Role Type reassignments seem to be disabled in the Diagram Editor. This happened in https://github.com/liferay/liferay-portal/commit/ba36e66c2e4aa630f18252681143c0a627174577, although I'm unable to figure out why we decided to do this when reading over [LPS-146642](https://liferay.atlassian.net/browse/LPS-146642).

Nevertheless, examining the [xsd](http://www.liferay.com/dtd/liferay-workflow-definition_7_4_0.xsd) reveals that we still support role-type reassignments in the XML in a format like the following:

```
<reassignments>
	<roles>
		<role>
			<role-type>regular</role-type>
			<name>User</name>
			<auto-create>false</auto-create>
		</role>
	</roles>
</reassignments>
```

However, the code in `utils.js` seems to be expecting a very different format for some reason, which is causing these definitions to fail to publish. This fix updates the code to expect and handle the correct format.

See just my changes: 5ee7bc06176a8ff01622e22e802a71a808e834cc

### CODE REVIEW

**Comment by cgmonte** [comment]
Hey @guilhermedcamacho and @mbowerman, I just started reviewing this. It makes total sense at a first sight, but I need to make sure that this is not going to break other cases. I will get back to this first thing tomorrow and send my review.

**Review by cgmonte — COMMENTED** [review]
Because this is not implemented in UI, if the user: 

1. Edits the XML as needed to add role-type reassignments
2. Goes back to the Diagram Builder
3. Select the node with such reassignments
4. Click on the timer with such reassignments

Then the role-type reassignments are replaced with "Asset Creator" reassignment. Both and XML and UI.

The recommendation to the user would be: don't click on timers with reassignment types other than Asset Creator otherwise you might loose part of your workflow definition if you save or publish after taking such actions.

Is this expected in the state of our current mitigation? I could not find any description of this behavior in the related tickets comments or descriptions.

**Review by cgmonte — APPROVED** [review]
> Because this is not implemented in UI, if the user:
> 
> 1. Edits the XML as needed to add role-type reassignments
> 2. Goes back to the Diagram Builder
> 3. Select the node with such reassignments
> 4. Click on the timer with such reassignments
> 
> Then the role-type reassignments are replaced with "Asset Creator" reassignment. Both XML and UI.
> 
> The recommendation to the user would be: don't click on timers with reassignment types other than Asset Creator otherwise you might loose part of your workflow definition if you save or publish after taking such actions.
> 
> Is this expected in the state of our current mitigation? I could not find any description of this behavior in the related tickets comments or descriptions.

Hey, I just talked to @samuelromeiro and he explained that this a known behavior, so it LGTM!

**Comment by cgmonte** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
ci:forward:force

**Pull request closed without merging**
