### PR TITLE
[7.4 ONLY] LPS-122373 | LPS-105491 Update tests with new app creation step

### PR DESCRIPTION
**Pull request by gabrielpramos**
7.4 only
cc @albinojunior @interaminense @kevenleone

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:forward

**Review by albinojunior — APPROVED** [review]

**Comment by gabrielpramos** [comment]
fixed the test macro and I will rerun ci relevant

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by gabrielpramos** [comment]
ci:stop

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by gabrielpramos** [comment]
ci:forward

**Comment by naraandrade** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielpramos** [comment]
ci:forward

**Pull request closed without merging**
