### PR TITLE
LPS-130988 Modify filter parameters

### PR DESCRIPTION
**Pull request by MariMalta**

### CODE REVIEW

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by MariMalta** [comment]
ci:test:sf

**Comment by ramonmsp** [comment]
ci:test:sf

**Comment by MariMalta** [comment]
ci:test:relevant

**Comment by MariMalta** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
Closing, It will resend by @MarinhoFeliphe

**Pull request closed without merging**
