### PR TITLE
SF

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Review by seltong — COMMENTED** [review]
This commit is an alternative way to validate the default transitions quantity.
Which alternative is the best in this case?

**Review by seltong — COMMENTED** [review]
The source format found these formatting changes to do.
Can I drop this commit? I didn't touch these files

**Comment by seltong** [comment]
ci:test:sf

**Comment by seltong** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @seltong There are some related failures here. Can you please check these and resend? And please add tests for your changes as well.

 Thx

**Comment by rafaprax** [comment]
> The source format found these formatting changes to do.
Can I drop this commit? I didn't touch these files

Yeap. You can remove these changes. Thx

**Comment by seltong** [comment]
Just started reviewing :)

**Pull request closed without merging**
