### PR TITLE
[TS] LPS-174604 Workflow entries are not anonymized when the user data is deleted

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
A deleted user's workflow tasks still display the user's original name, not the Anonymus user's.

Proposed Solution
========
The user's date is:

- `kaleolog`'s `userId`, `userName`, `currentAssigneeClassPK`, and `previousAssigneeClassPK`
- `kaleotaskassignmentinstance`'s `userId`, `userName`, and `assigneeClassPK`.

When a user is deleted, the above fields should be anonymized.

I am using the UAD framework for this.

Steps to Verify
========
Please consult the linked LPS for the reproduction steps:
https://issues.liferay.com/browse/LPS-174604

Thank you and best regards,
István

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
@IstvanD,

LGTM! thanks for your contribution!

Best Regards,
Feliphe

**Comment by MarinhoFeliphe** [comment]
@IstvanD,

Could you please check [this failure](https://testray.liferay.com/home/-/testray/case_results/2187097348?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2187094297%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)?

Thank you,
Feliphe

**Comment by IstvanD** [comment]
Hi @MarinhoFeliphe I force-pushed the corrections.

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow

**Comment by MarinhoFeliphe** [comment]
ci:test:workflow-metrics

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Review by MarinhoFeliphe — APPROVED** [review]

**Pull request closed without merging**
