### PR TITLE
LPS-152750 ant build-lib-versions

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:reports

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Thanks, @rafaprax :)

**Comment by MarinhoFeliphe** [comment]
Got it!

Thanks! @rafaprax

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-workflow/liferay-portal/pull/811

Please close this PR, thanks!

**Pull request closed without merging**
