### PR TITLE
LPD 17037

### PR DESCRIPTION
**Pull request by Marina-Gouveia**
Related Issue: [LPD-17037](https://liferay.atlassian.net/browse/LPD-17037)
Related LPP: [LPP-52612](https://liferay.atlassian.net/browse/LPP-52612)

### CODE REVIEW

**Review by p-albuquerque — APPROVED** [review]
LGTM

**Comment by MarinhoFeliphe** [comment]
Hey guys I've removed myself as reviewer because these changes are only on the frontend side (React).

please feel free to reach me if you need to know something about business rules.

Thank you!

cc: @guilhermedcamacho @Marina-Gouveia @cgmonte

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
ci:test:relevant

**Comment by cgmonte** [comment]
ci:test:workflow

**Comment by Marina-Gouveia** [comment]
ci:test:relevant

**Comment by Marina-Gouveia** [comment]
ci:test:workflow

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:workflow

**Comment by p-albuquerque** [comment]
I had checked the CI results in both: relevant and workflow suites. 
No related failures found.
@Marina-Gouveia you can forward this PR to Brian manually

**Comment by pedro-oliveira446** [comment]
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/147280)

**Pull request closed without merging**
