### PR TITLE
LPS-134253 Add margin to fix layout issue

### PR DESCRIPTION
**Pull request by MariMalta**

### CODE REVIEW

**Comment by MariMalta** [comment]
ci:test:sf

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:test:relevant

**Review by ramonmsp — APPROVED** [review]

**Comment by ramonmsp** [comment]
ci:forward

**Comment by ramonmsp** [comment]
ci:test:relevant

**Comment by ramonmsp** [comment]
ci:forward

**Pull request closed without merging**
