### PR TITLE
[7.4 only] LPS-124401 Baseline

### PR DESCRIPTION
**Pull request by albinojunior**
Story https://issues.liferay.com/browse/LPS-121226

/cc @gabrielpramos @rafaprax  @naraandrade

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:forward

**Comment by albinojunior** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by albinojunior** [comment]
Just started reviewing :)

**Comment by albinojunior** [comment]
Just started reviewing :)

**Pull request closed without merging**
