### PR TITLE
LPS-138748 Fix sort direction function

### PR DESCRIPTION
**Pull request by jotascript**
Issue: [LPS-138748](https://issues.liferay.com/browse/LPS-138748)

### CODE REVIEW

**Review by naraandrade — APPROVED** [review]

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Review by MarinhoFeliphe — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MariMalta** [comment]
Just started reviewing :)

**Comment by rafaprax** [comment]
resent here https://github.com/liferay-workflow/liferay-portal/pull/616

**Pull request closed without merging**
