### PR TITLE
LPS-130222 Add the SLA Results information for each instance

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Review by rafaprax — APPROVED** [review]

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by jotascript** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
ci:forward

**Comment by rafaprax** [comment]
Hey @rodrigocunhaa ,

If this pr fails due to unrelated errors again, could you forward directly to BChan?

/cc @MarinhoFeliphe

**Pull request closed without merging**
