### PR TITLE
[TS] LPS-171646 - calendar bookings should not be listed as selectable when making collections

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-workflow team,

This is to address a client's issue in [LPS-171646](https://liferay.atlassian.net/browse/LPS-171646) which related to them realizing that Calendar Bookings are listed when creating a Collection, but cannot be used with Collection Display fragments. In [PTR-3561](https://liferay.atlassian.net/browse/PTR-3561) it was decided by your team that Calendar Bookings being listed in this was a bug due to not being a part of the info framework. I understood this to mean that we should not be able to make collections at all using a Calendar Booking and therefore added the setSelectable(false) to the asset renderer factory, but please let me know if I'm misunderstanding the intended state of Calendar Bookings. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
Hello @wanderlast,

these two failures below seem related to your change, I'll rerun calendar's test to ensure they're not flacky,

- [com.liferay.calendar.search.test.CalendarBookingIndexerIndexedFieldsTest](https://testray.liferay.com/home/-/testray/case_results/2394085747/history?tab=result&hideFilterPin=true)

- [LocalFile.NewEvent#AddWithRelatedAssetViaAssetPublisher](https://testray.liferay.com/home/-/testray/case_results/2394085677/history?tab=result&hideFilterPin=true)

**Comment by MarinhoFeliphe** [comment]
ci:test:calendar

**Comment by MarinhoFeliphe** [comment]
Hey @wanderlast the tests mentioned [here](https://github.com/liferay-workflow/liferay-portal/pull/969#issuecomment-1653754402) failed again,

could you please take a look?

thanks!

**Review by MarinhoFeliphe — CHANGES_REQUESTED** [review]
Hey @wanderlast the tests mentioned [here](https://github.com/liferay-workflow/liferay-portal/pull/969#issuecomment-1653754402) failed again,

could you please take a look?

thanks!

**Comment by MarinhoFeliphe** [comment]
Block reason:

We need to know how critical it's because the approach applied is breaking some tests and the team needs more time to provide a proper solutions for this.

**Comment by MarinhoFeliphe** [comment]
Closing this pull request in favor of https://liferay.atlassian.net/browse/LPP-50116?focusedCommentId=2434477

**Pull request closed without merging**
