### PR TITLE
LPD-33273 Create condition when creatorName doesn't exists in VersionRow component

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-33273

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Comment by danvb112** [comment]
ci:test:relevant

**Comment by danvb112** [comment]
ci:test:workflow

**Comment by rebsilva** [comment]
just started reviewing! :cherry_blossom:

**Review by rebsilva — APPROVED** [review]
LGTM! :tada:

**Comment by danvb112** [comment]
CI Failures are not related!

**Comment by danvb112** [comment]
ci:forward

**Pull request closed without merging**
