### PR TITLE
LPS-142345 Support Japanese and Chinese characters

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Hey @MarinhoFeliphe,
everything is ok except the message from the last commit. Please fix this and forward. Nice job.

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
