### PR TITLE
LPS-147094 Update Google Protocol Buffers dependency version

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
ci:help

**Comment by MarinhoFeliphe** [comment]
ci:test:drools

**Comment by MarinhoFeliphe** [comment]
ci:test:drools

**Comment by pyoo47** [comment]
ci:stop

Stopping and restarting due to ci-infrastructure bug

**Comment by pyoo47** [comment]
ci:test:drools

**Comment by MarinhoFeliphe** [comment]
Thank you, @pyoo47!

**Comment by seltong** [comment]
ci:test:drools

**Comment by MarinhoFeliphe** [comment]
ci:forward

**Pull request closed without merging**
