### PR TITLE
LPD-18432 Remove the unnecessary condition already performed in the goToTransitionSteps macro

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://liferay.atlassian.net/browse/LPD-18432

### CODE REVIEW

**Comment by danvb112** [comment]
ci:test:sf

**Review by gabrielwas — APPROVED** [review]
LGTM :)

**Comment by gabrielwas** [comment]
ci:test:workflow

**Comment by guilhermedcamacho** [comment]
ci:stop

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:workflow-metrics

**Comment by danvb112** [comment]
ci failures are not related!

**Comment by danvb112** [comment]
ci:forward:force

**Pull request closed without merging**
