### PR TITLE
LRQA-59713 Remove test from quarantine

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:stop

**Comment by rodrigocunhaa** [comment]
@gabrielpramos , please, remove the quarantine property from [ViewProcessWithComments](https://github.com/gabrielpramos/liferay-portal/blob/LRQA-59713/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-test/src/testFunctional/tests/KaleoformsUsecase.testcase#L4733) test as well.

**Pull request closed without merging**
