### PR TITLE
LPS-124203 Set limit to action name size

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:app-builder

**Comment by naraandrade** [comment]
ci:test:relevant

**Review by albinojunior — APPROVED** [review]
LGTM

**Review by albinojunior — COMMENTED** [review]
@naraandrade should you apply the `maxLength` on the secondary action name input?

**Comment by naraandrade** [comment]
> @naraandrade should you apply the `maxLength` on the secondary action name input?

Totally forgot about the other action :p Thanks for noticing

**Comment by naraandrade** [comment]
ci:forward

**Comment by naraandrade** [comment]
ci:forward

**Pull request closed without merging**
