### PR TITLE
LPS-122778

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @liferay-workflow,
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
Hi @rafaprax ,
I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.
Thank you and best regards,
Marci

**Comment by rafaprax** [comment]
Hey @MarcellGyopos , those failures are related to your changes, see below.

     [java] 	at java.lang.Class.getField(Class.java:1703)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.getTableName(UpgradeProcess.java:536)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.alter(UpgradeProcess.java:321)
     [java] 	at com.liferay.calendar.internal.upgrade.v4_1_1.UpgradeCalendarNotificationTemplate.doUpgrade(UpgradeCalendarNotificationTemplate.java:27)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:104)
     [java] 	... 87 more
     [java] 
     [java] Completed Liferay core upgrade process in 243 seconds
     [java] Checking to see if all upgrades have completed... your upgrades have failed, have not started, or are still running.
     [java] Connecting to Gogo shell...
     [java] 
     [java] Type "help" to get available upgrade and verify commands.
     [java] Type "help {command}" to get additional information about the command. For example, "help upgrade:list".
     [java] Enter "exit" or "quit" to exit.
     [java] g! 

According to this article https://grow.liferay.com/group/guest/people/-/wiki/34277/Changing+the+model+in+an+Upgrade+Process, you forgot to generate and use the CalendarNotificationTemplateTable class. Please fix and resend.

Thanks

**Pull request closed without merging**
