### PR TITLE
LPS-163298 Application crashes after switching from Source view to Diagram, when importing attached definition

### PR DESCRIPTION
**Pull request by daiazius**
Related issue: https://issues.liferay.com/browse/LPS-163298

### CODE REVIEW

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
ci:reevaluate:1377401_5294

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by daiazius** [comment]
ci:test:relevant

**Comment by naraandrade** [comment]
Just started reviewing :)

**Comment by naraandrade** [comment]
@daiazius The failures are not related with your changes. Can you send it directly to Brian, please?

**Comment by daiazius** [comment]
@naraandrade Sure, I'll do it right now!

**Comment by daiazius** [comment]
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/124142)

**Pull request closed without merging**
