### PR TITLE
[7.4 only] LPS-124001 Adjust kaleo designer form content width

### PR DESCRIPTION
**Pull request by albinojunior**
/cc @gabrielpramos @naraandrade

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:sf

**Review by gabrielpramos — APPROVED** [review]
LGTM

**Review by rafaprax — APPROVED** [review]

**Comment by rafaprax** [comment]
LGTM

**Comment by gabrielpramos** [comment]
ci:forward

**Pull request closed without merging**
